src/parameters.rs
See issue #16, where someone is sending TransportParameterIds like 0xff00, 0xff01, etc.
=> Ignore unknown `TransportParameterId`s when decoding

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/stream.rs, quinn-proto/src/tests.rs
Corrects a fencepost error in initiator-side flow control budget checking, and a bug that caused remote streams that weren't initially open to never be opened.
=> Test and debug stream ID flow control

quinn/examples/interop.rs, quinn/src/lib.rs
This makes it easier to construct multiple futures that interact with the same connection.
=> Derive Clone for high-level Connection and Endpoint

quinn-proto/Cargo.toml, quinn-proto/examples/connect.rs, quinn-proto/src/connection.rs, quinn-proto/src/crypto.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests.rs, quinn/Cargo.toml, quinn/examples/client.rs, quinn/examples/interop.rs, quinn/examples/server.rs, quinn/src/lib.rs
- Allow configuration of individual clients within an endpoint
- Implement feature-gated config helper for untrusted connections
- Don't enable keylogging by default
- Test rejection of invalid certs
Candidate to address #35.
=> Client configuration API

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs
@djc @Ralith 
I managed to botch the rebase on my previous branch, so starting anew here.
Prior to this patch, we had duplicated lots of error handling logic inside `handle_connected_inner`, mostly in the way of event recording. This patch simplifies this by instead returning a `Result<State, ConnectionError>`, which allows the caller to handle either case and create events more succinctly than `handle_connected_inner` could.
Also, this changeset moves the `app_closed` property from `connection::State` to `connection::Connection` itself, as it is much simpler to manage that piece of state on the `Connection` itself.
Closes #51.
=> Reduce repetitive error handling (take two)

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn/examples/client.rs, quinn/examples/server.rs
Simplifies many signatures.
A lot of things are still a bit awkward about construction, but I think this is a step in the right direction.
=> Move TLS out of state enum

README.md, quinn-proto/src/tests.rs
This prevents routine tests from failing due to UDP port collisions. Because key logging is necessary for UDP packet inspection to be of much use, the same environment variable is used to control both.
=> Only emit UDP packets from tests when logging TLS keys

quinn-proto/src/connection.rs, quinn-proto/src/tests.rs
>  An endpoint that receives a STOP_SENDING frame MUST send a RESET_STREAM frame for that stream [and] SHOULD copy the error code from the STOP_SENDING frame
=> Tweak solicited RESET_STREAM error code to match recommendation

quinn-proto/Cargo.toml, quinn-proto/src/connection.rs, quinn-proto/src/crypto.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests.rs
Creating this pull request to show what I've already done. I don't quite get the part where:
>  it would probably good to store the SigningKey in the ListenKeys and work from that
But I'll work on this now.
=> Remove Blake2 and use SHA512_256 for reset_token instead

quinn-proto/src/connection.rs, quinn-proto/src/crypto.rs
I've rebased and squashed the commits from #94:
```
commit 722fe7ac2b6e9b818c448600c02dfe9329140ea9 (HEAD -> cache-keys, origin/cache-keys, cryptog)
Author: stammw <begue.jc@gmail.com>
Date:   Wed Nov 28 22:11:39 2018 +0100
Get rid of Crypto as an enum and work directly with CryptoContext
commit 8dd8ffd834887c0449b2873d99093f11e00cb439
Author: stammw <begue.jc@gmail.com>
Date:   Wed Nov 28 20:29:38 2018 +0100
Remove commented code in crypto
commit a8a56eac4e0bcdd6fa846c2d7f802abeed60ae64
Author: stammw <begue.jc@gmail.com>
Date:   Wed Nov 28 07:59:01 2018 +0100
Do not use CryptoState in Initial and OneRtt Crypto
commit d9bd6854d41a7fa3a2136451048cad58b91ef3c3
Author: Dirkjan Ochtman <dirkjan@ochtman.nl>
Date:   Thu Nov 29 10:07:54 2018 +0100
Remove unused ZeroRttCrypto type
commit …
```
=> Cache keys

quinn-proto/src/connection.rs, quinn-proto/src/tests.rs
This test is expected to fail under draft 16, but should be enabled when we move to draft 17.
=> Test reordering around key updates

quinn-proto/src/endpoint.rs, quinn-proto/src/tests.rs, quinn/src/lib.rs
This event was always emitted exactly when the close timer expires, which is already known to the caller. Making it implicit lets us reduce bookkeeping.
If #127 moves queuing of the `TimedOut` event into the connection, we will be able to do away with `Context::events` entirely.
=> Remove ConnectionDrained event

quinn/Cargo.toml, quinn/src/lib.rs, quinn/src/platform/cmsg.rs, quinn/src/platform/fallback.rs, quinn/src/platform/linux.rs, quinn/src/platform/mod.rs, quinn/src/udp.rs
Not sure we want to merge this before libc merges my PR there, but there's lots of esoterica to scrutinize in the meantime.
=> Send/receive ECN bits on linux

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/tests.rs, quinn-proto/src/transport_parameters.rs, quinn/examples/server.rs
Integer parameters were moved to varint encoding, and everything was renumbered.
=> Draft 17 transport parameters

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/frame.rs, quinn-proto/src/tests.rs, quinn-proto/src/transport_parameters.rs, quinn/examples/server.rs, quinn/src/lib.rs
This adds support for clients performing stateless resets by transmitting `NEW_CONNECTION_ID` immediately after handshake to establish a reset token, and fixes several bugs encountered along the way.
=> Clientside stateless resets

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs
Pretty much just went through and transcribed the new pseudocode, with minor adjustments along the same lines as the ones made previously. The logic is a little simpler and makes a little more sense this time around (e.g. no always-false bools).
=> Draft 17 recovery logic

quinn-proto/Cargo.toml, quinn-proto/src/connection.rs, quinn-proto/src/crypto.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/frame.rs, quinn-proto/src/packet.rs, quinn-proto/src/tests.rs, quinn/Cargo.toml
This introduces the notion of discrete packet number spaces and the associated crypto and retransmit management. Currently non-functional due to, at minimum, bugs in the rustls `QuicExt::get_handshake_secrets` implementation, which I'll continue to investigate tomorrow.
=> Draft 17 handshake crypto

quinn-proto/src/connection.rs, quinn-proto/src/crypto.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/tests.rs, quinn/src/lib.rs, quinn/src/platform/linux.rs
Fix #154
I wasn't sure whether to branch based on the type of the destination address or the type of the local address. I opted for the former since it allows the OS to provide its usual error message when an unsupported address is used.
It's interesting to note that an "Address family not supported by protocol" error currently brings down the whole endpoint. Perhaps send errors should be propagated back to their associated connection instead?
=> Ipv4 fixes

quinn-proto/src/connection.rs, quinn-proto/src/crypto.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/stream.rs, quinn-proto/src/tests.rs, quinn/src/lib.rs
This adds both the draft-mandated anti-amplification measures, and the clientside changes needed to remain well-behaved in the face of packet loss under those measures.
=> Handshake robustness

quinn-proto/src/endpoint.rs, quinn/examples/interop.rs, quinn/src/lib.rs, quinn/src/platform/cmsg.rs, quinn/src/platform/linux.rs, quinn/src/tests.rs
Where the prior approach broke on even only slightly old Linux, this makes for a simpler, more efficient, more portable, and more robust solution, and the new tests should help avoid any future surprises.
Note that testing dual-stack sockets is a bit dicey since only Linux enables dual-stack mode by default (subject to system configuration), enabling it by hand on the socket takes a bit of effort, and e.g. OpenBSD doesn't support them at all. Still, better than no test at all.
=> IPv4 redux

quinn/examples/server.rs, quinn/src/lib.rs, quinn/src/tests.rs, quinn/src/tls.rs
This decouples an important part of the API from rustls, and greatly simplifies the task of robustly reading a certificate from disk.
Thanks to @est31 for working out how to wrangle this properly.
=> Hide rustls certificate types and parsing methods

quinn-proto/src/connection.rs, quinn-proto/src/crypto.rs, quinn-proto/src/packet.rs, quinn-proto/src/tests.rs, quinn/src/platform/cmsg.rs, quinn/src/platform/linux.rs
0-RTT packets weren't being assigned a packet space, which meant no header crypto was selected for them, which lead to a panic in `PartialDecode::finish` which correctly assumed that all standard-form long-header packets have encrypted headers. This corrects the omission and drops 0-RTT packets prior to decryption since rustls isn't giving us 0-RTT keys yet anyway.
=> Assorted cleanup, panic fix

quinn/Cargo.toml
The git commit that libc had been pinned
to earlier has been part of a release since.
=> Use libc from crates.io

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/stream.rs, quinn-proto/src/tests.rs, quinn-proto/src/transport_parameters.rs, quinn/examples/server.rs, quinn/src/lib.rs, quinn/src/tests.rs
This makes the implementation significantly more flexible and responsive without requiring any particular effort from the application. I'd be interested to hear any thoughts on enabling incoming streams by default; it seems like doing otherwise is a massive gotcha.
Fixes #62
=> Implement dynamic stream ID flow control

quinn-proto/src/crypto.rs, quinn-proto/src/endpoint.rs
I continue to get a lot of mileage out of browsing around at random and second-guessing things.
I almost added a `packet.is_initial()` guard to the `connection_ids_initial` query, but I can't think of any case where it would matter.
=> Assorted fixes

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/stream.rs, quinn-proto/src/tests.rs
This tests the behavior tonight's rustls fixes corrected.
=> Expanded 0-RTT testing, assorted fixes

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests.rs, quinn/src/lib.rs
I opted for using `ch` everywhere except as a field on the `ConnectionInner` type in the quinn crate: since that represents a `Connection`, I felt `handle` made the code easier to read.
Also made it so the type is a little more abstracted.
=> Clearer handling of ConnectionHandles

quinn-proto/src/connection.rs
I think this accounts for the bulk of the strangely pessimal performance I've been observing correlated with early packet loss: the connection was getting stuck in congestion recovery mode, because packet numbers tend to be much smaller than microsecond timestamps.
=> Congestion control fix

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests.rs, quinn/src/builders.rs, quinn/src/lib.rs
Thought about this after that slowdown bug -- it seems pretty okay? Not sure why you went with `u64` in the first place, so curious about your thinking there.
This compiles and passes the -proto tests, but fails the high-level echo tests for now.
=> Use Instant and Duration for timing

quinn-proto/src/connection.rs, quinn-proto/src/packet.rs, quinn-proto/src/tests.rs
We were trying to decrypt version negotiation packets, which aren't encrypted in the first place, leading to the packets being dropped and the connection timing out, taking longer than necessary and giving a less helpful error when connecting to a server that does not support the version we implement.
=> Fix version negotiation on outgoing connections

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs
This prevents a memory exhaustion DoS if a peer issues large amounts of flow control credit without acknowledging stream data.
=> Limit volume of unacked stream data

.travis.yml, quinn/Cargo.toml, quinn/src/platform/cmsg.rs, quinn/src/platform/mod.rs, quinn/src/platform/unix.rs, quinn/src/tests.rs
libc's CMSG macros got built out to many more platforms. There may remain some obscure platforms where this will still fail to build, but we can account for them as they show up in practice.
Note that some bugs remain in the new libc bindings, so we may want to defer merging this until https://github.com/rust-lang/libc/pull/1235 shows up in a release.
=> Expand ECN support

quinn-proto/src/connection.rs
This implements the new time-based persistent congestion threshold added in https://github.com/quicwg/base-drafts/pull/2365, which fixes detection of persistent congestion while sending continuously.
=> Update persistent congestion detection logic

quinn-proto/src/connection.rs, quinn-proto/src/packet.rs
Authentication/correctness is an independent concern. Improves behavior when coalesced 0-RTT is rejected, which could otherwise lead to large parts of the initial packet not being counted for anti-amplification credit.
=> Account for all UDP datagram bytes in anti-amplification

quinn/src/lib.rs, quinn/src/tests.rs, quinn/src/udp.rs
This is especially useful if we were binding to port 0 intending the OS to allocate us a random port. Then we would like to know what port was actually allocated. Besides it's a useful API anyway as it's natural to want to know this detail from a bound socket for completeness.
=> API for obtaining our local endpoint

quinn-proto/src/connection.rs
The error type should contain the frame causing the protocol violation
=> Add more debug info for the PROTOCOL_VIOLATION error

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests.rs, quinn/examples/server.rs, quinn/src/lib.rs, quinn/src/tests.rs
This is the big one.
Currently not quite done: we need to figure out how to handle the connection closing sequence. Since `Endpoint::close()` is no more, `app_closed` never gets set, so the `ConnectionMeta` state doesn't get cleaned up (I think this is why `zero_length_cid` fails). The quinn tests hang and there is some unused code having to do with cancelable timers that probably should be wired up somehow.
Even after all that gets fixed, I'd prefer not to wait for this to be perfect before we merge it, since it's pretty invasive -- I'll follow up with improvements soon after. However, I'd like to get this to pass the tests and not introduce any substantial functional regressions. Things I'd prefer to address after merging this PR:
- Use of unbounded channels
- Lack of documentation …
=> Return Connections from Endpoints after creation

quinn/src/platform/unix.rs
msghdr struct in musl libc has padding fields which are private (introduced with this PR: https://github.com/rust-lang/libc/pull/1164). This commit fixes the struct initialisation code, replacing it with manual fields assingment.
Tests pass on all platforms now.
=> Fix builds on musl environment

quinn-proto/src/connection.rs, quinn-proto/src/stream.rs, quinn/src/connection.rs
Since we've grown a similar enum variant for `ReadError` in the meantime, I figured I'd follow through on @icefoxen's PR #87.
=> Return Err when writing to unknown stream (see #87)

.travis.yml
Also get backtraces for the code coverage run.
Doesn't actually work yet, see https://github.com/xd009642/tarpaulin/issues/219.
=> Change code coverage command to make build job fail when appropriate

quinn-proto/src/connection.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/examples/client.rs, quinn/examples/server.rs
This lead the peer to believe we've processed data that we haven't, causing all manner of inconsistent state.
=> Fix reordered data packets being incorrectly acknowledged

interop/src/main.rs, quinn-proto/src/connection.rs, quinn-proto/src/crypto.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/shared.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/examples/client.rs, quinn/examples/server.rs, quinn/src/builders.rs, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/lib.rs, quinn/src/tests.rs
No significant behavioral change, but lots of quality-of-life improvements. Allowing per-connection loggers to be specified is especially helpful when trying to diagnose problems in code with many concurrent connections as it allows logs to easily be collected separately and only displayed once the relevant subset are identified.
=> Assorted cleanup

quinn/src/platform/unix.rs, quinn/src/tests.rs
Theoretically fixes #245. @djc, please test on the affected machine. Bonus points if you can double-check that the "ECN not acknowledged by peer" message is *not* displayed in the trace logs of the dual stack test.
I'd also like to cite the specific bug report tracking this issue upstream to make it easier to see whether it's still needed in the future, but I'm not sure where to find that.
=> Hack around broken macOS ECN ABI

interop/src/main.rs, quinn/examples/client.rs, quinn/examples/server.rs, quinn/src/streams.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
You can't do anything with a finished receive stream, so there's no point preserving it even under futures 0.1 idioms.
=> ReadToEnd future cleanup

quinn/examples/connection.rs, quinn/examples/insecure_connection.rs, quinn/examples/server.rs, quinn/examples/single_socket.rs, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
Looks like we forgot to update `quinn::Incoming` to yield a stream of handshake futures to represent the fact that its connections are not yet fully established.
Fixes #331
=> Connection lifecycle fixes

quinn-proto/src/connection.rs, quinn-proto/src/crypto.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/packet.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/src/endpoint.rs
Results in 3 fewer datagrams on the `echo_v4` test.
Currently the `server_hs_retransmit()` test is still broken. @Ralith any suggestions if/how this should be fixed?
=> Coalesce outgoing packets

quinn/src/lib.rs, quinn/src/streams.rs, quinn/tests/many_connections.rs
It occurred to me that `ReadError::Finished` is a bit weird because `Finished` isn't really an error. This change fixes that only in the `quinn` crate, where it does seem to achieve a natural alignment with `futures::Stream`-like handling. I looked at extending it to quinn-proto as well, but I'm not sure it's worth it there.
=> Make stream read API more Stream-like

quinn-proto/src/endpoint.rs
Not sure when exactly we stopped needing this, but it clearly makes no sense at all now that we're generic on crypto impl regardless.
=> Remove dead error case

.travis.yml, quinn-proto/Cargo.toml, quinn-proto/src/connection.rs, quinn-proto/src/crypto.rs, quinn-proto/src/crypto/ring.rs, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/packet.rs, quinn-proto/src/transport_error.rs
This doesn't yet fix the parameter defaults as discussed, but it does show that we can compile most of the quinn-proto crate without rustls or ring (although it will only run a few tests).
=> Optional rustls

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs
We're probably not benefiting from having an explicit RNG field at this point, but it'll save time if we want to swap it out (e.g. with *ring*'s) in the future.
=> Fix deprecated rand API use

interop/src/main.rs, quinn-proto/src/streams.rs, quinn/examples/client.rs, quinn/examples/server.rs, quinn/src/streams.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
Constantly unwrapping this was bugging me, and reasonable users might want this after having read a prefix anyway. The behavior when used following an unordered read may bear some consideration.
=> More flexible RecvStream::read_to_end

quinn-proto/src/connection.rs, quinn-proto/src/shared.rs, quinn-proto/src/spaces.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/transport_error.rs
I feel like there should be a better way to determine whether an acknowledged packet was sent with 1-RTT keys than the `first_1rtt_sent` field.
=> Backwards-compatible draft 21 updates

quinn/src/platform/cmsg.rs, quinn/src/platform/unix.rs
Corrects some UB and fixes deprecation warnings.
=> Replace uses of `mem::uninitialized` with `mem::MaybeUninit`

quinn-proto/src/endpoint.rs
e.g. current Google QUIC, and peers shouldn't be able to make us panic regardless.
=> Don't panic if a misbehaving peer reuses a reset token

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/packet.rs
It's not clear why downstream code would need this.
=> Don't export VERSION constant

README.md, quinn/Cargo.toml
In the initial setup, I skimmed too fast over the paragraph that stated that
Azure DevOps projects must be aligned to GitHub organizations/users. Since
I want to use Azure Pipelines for other projects, too, I've reorganized the
setup a bit, which means the badge links need to be updated.
=> Use different project for Azure Pipelines

azure-pipelines.yml
- Run ignored tests, used for slow tests (we used to have this on Travis)
- Run coverage on nightly for now due to (see #336)
Enabled by the changes from https://github.com/crate-ci/azure-pipelines/pull/42.
=> Tweak CI config with latest template changes

quinn-proto/src/connection.rs
Stateless reset tokens are no longer mandatory.
=> Fix panics when a server doesn't issue a stateless reset token

quinn-h3/examples/h3.rs, quinn-h3/src/body.rs, quinn-h3/src/client.rs, quinn-h3/src/frame.rs
I'm not sure about the RecvBodyReader::buf_{pop,push}() method names.
And about their implementation, I tried to limit the number of copies and allocations by storing the DataFrame(Bytes)'s buffer only. It makes read() returned size possibly very small compared to the passed buffer size. I'd like some feedback on this as I'm not sure about this choice.
The only example has been updated to exercise this new API.
=> H3: body AsyncRead implementation

quinn-proto/src/shared.rs
A user reported uncertainty about proceeding without fully understanding the available options. Quinn tries to be extremely configurable, so it's important to communicate that most options don't need to be changed for most applications.
=> Improve configuration advice

interop/src/main.rs, quinn-h3/src/client.rs, quinn-h3/src/qpack/prefix_string/decode.rs, quinn-h3/src/server.rs, quinn/benches/bench.rs, quinn/examples/client.rs, quinn/examples/connection.rs, quinn/examples/insecure_connection.rs, quinn/examples/server.rs, quinn/examples/single_socket.rs, quinn/src/connection.rs, quinn/src/lib.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
This enables forwards-compatibility with future extensions such as a datagram stream.
Partially unblocks #395.
=> Restore NewConnection struct for parts of a connection

quinn-h3/examples/h3.rs, quinn-h3/src/body.rs, quinn-h3/src/client.rs, quinn-h3/src/frame.rs, quinn-h3/src/proto/frame.rs, quinn-h3/src/proto/headers.rs, quinn-h3/src/server.rs
This PR makes it possible to use the `body.rs` reading API in server code. Reading a request body from the
server code has something particular compared to reading body from the client: it needs to cary a `SendStream`
to the next step. So response can be sent back.
I added a type parameter that receives this `SendStream`, so APIs can use the same implementation underneath,
while having a slightly different chain of steps:
```
Client:
RecvResponse.body_reader() -> BodyReader<()> -> DecodeHeader<()>
Server:
RequestReady.body_reader() -> BodyReader<SendStream> -> DecodeHeader<Sendstream>.into_sender() -> Sender.send(response)
```
I created a trait to extract this `SendStream` and turn it into a `Sender`:
```rust
impl IntoSender for RecvBodyStream<SendStream> {
fn into_sender(self) -> Sender …
```
=> H3 streamed body server

quinn-proto/src/assembler.rs
If a chunk of data ends at `self.offset` exactly, we can discard it immediately.
No changes in intended or actual semantics, just a trivial optimization.
=> Don't bother copying empty slices

quinn-proto/src/connection.rs, quinn/src/connection.rs
The low-level API would unintuitively appear to succeed until the
window is exhausted, at which point the high-level API would yield
futures that would never resolve.
Remarkably, this PR applies cleanly on both master and std-futures, so no need to delay!
=> Fix bad behavior opening streams on a closed connection

quinn-proto/src/connection.rs, quinn-proto/src/shared.rs, quinn-proto/src/transport_parameters.rs, quinn/src/tests.rs
Handshake recovery logic changes still TODO, since an undocumented requirement for probe packets to retransmit CRYPTO data seems to have been introduced (see https://github.com/quicwg/base-drafts/issues/3056).
=> Partial draft 23 reliability changes plus miscellany

quinn-proto/src/crypto/ring.rs, quinn-proto/src/lib.rs, quinn-proto/src/packet.rs, quinn/examples/common/mod.rs
This passes the tests at least, and it gets VHDR with quicly.
=> Update initial salt and QUIC version to draft 23

quinn-proto/src/connection.rs, quinn-proto/src/spaces.rs, quinn-proto/src/tests/mod.rs
Modifies our probe strategy to retransmit in-flight data rather than
sending a PING frame. This gives us a chance of accelerated loss
recovery and allows adoption of the new draft's simplified handshake
retransmit logic.
Took me a while to decide how to do this, but in the end we've got (theoretically) improved robustness *and* a net code reduction!
=> Draft 23 handshake retransmit, data-bearing probes

interop/src/main.rs, quinn-h3/examples/h3.rs, quinn-h3/examples/simple_client.rs, quinn-h3/examples/simple_server.rs, quinn-h3/src/server.rs, quinn/benches/bench.rs, quinn/examples/client.rs, quinn/examples/common/mod.rs, quinn/examples/insecure_connection.rs, quinn/examples/server.rs, quinn/src/builders.rs, quinn/src/lib.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
Improves consistency with Endpoint::connect and removes the
possibility of silent blocking should the user pass in a domain
name. The generic API was originally motivated by the convenience of
passing in numeric addresses as strings, but `.parse().unwrap()` is
pretty easy too.
=> Remove ToSocketAddrs from EndpointBuilder::bind

quinn-h3/src/client.rs, quinn-h3/src/connection.rs, quinn-h3/src/server.rs, quinn-proto/src/connection.rs, quinn-proto/src/tests/mod.rs, quinn/benches/bench.rs, quinn/examples/server.rs, quinn/src/connection.rs, quinn/src/lib.rs, quinn/src/streams.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
The order in which streams are opened is preserved only between streams of the same directionality, and backpressure similarly exists only within streams of the same directionality. As a result, if an application wants to process a certain stream identified by opening sequence (e.g. the first unidirectional stream, perhaps containing important session parameters), it must accept and buffer an arbitrarily large number of streams of the other type.
To correct this, we need to allow applications to be notified of and accept streams of a specific directionality, while allowing others to remain pending.
The incidental renaming improves concision substantially, and I don't think the increase in ambiguity is significant.
=> Per-directionality accept

quinn/src/streams.rs
This was causing compilation issues for me which are now fixed.
=> Removed 'Initializer' import and use as it seems to not exist anymore

quinn-proto/src/connection.rs, quinn-proto/src/frame.rs, quinn-proto/src/lib.rs, quinn-proto/src/shared.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/transport_parameters.rs, quinn/src/broadcast.rs, quinn/src/connection.rs, quinn/src/lib.rs
Fixes #207.
~This extension isn't stable yet, and (partly in the interest of avoiding rebase churn in std-futures branch) I haven't yet implemented the high level API, but this is the bulk of the work, and the API is ready to receive feedback.~
=> Implement the unreliable datagram extension

quinn-proto/src/crypto.rs, quinn/src/connection.rs
Moreover, shouldn't a future we provided for the user to wait for the connection to be done with handshaking? This would be useful for a protocol that transmit idempotent metadata to the peer at the connection start, but then needs a proper session once that is done.
=> Fixed doc for Session::is_handshaking

quinn-h3/src/client.rs, quinn-h3/src/connection.rs, quinn-h3/src/lib.rs, quinn-h3/src/proto/connection.rs, quinn-h3/src/proto/frame.rs, quinn-h3/src/proto/mod.rs, quinn-h3/src/server.rs, quinn-h3/src/streams.rs
This PR adds `Uni` stream management and a partial `control stream` implementation (#358). Only `Settings` frames are handled for now, as other frame types will need more work to implement their respective behaviour:
- `GoAway`: Error management for a connection-wide scope and `StreamId` tracking.
- `CancelPush` and `MaxPushId`: PushStreams implementation.
`quinn-h3::Connection::set_error()` is only a stub function, waiting to be implemented in a future error management related PR.
=> H3 control stream

quinn-proto/src/connection.rs, quinn/src/connection.rs
By deferring allocation of the stream ID until the futures synchronously completes, we guarantee that either no ID is allocated or ownership is successfully taken by the Send/RecvStream struct(s).
Thanks to @stammw for noticing that the semantics here were poorly thought out!
=> Fix stream ID leak when stream opening futures are dropped

quinn-h3/src/body.rs, quinn-h3/src/client.rs, quinn-h3/src/connection.rs, quinn-h3/src/frame.rs, quinn-h3/src/headers.rs, quinn-h3/src/lib.rs, quinn-h3/src/proto/connection.rs, quinn-h3/src/proto/mod.rs, quinn-h3/src/server.rs, quinn-h3/src/streams.rs
This PR addresses connection and stream abrupt closures and errors. It contains the implementation of Goaway graceful shutdown from the server.
It also includes stream reset features, part of Goaway procedure. Every stream reset cases have been changed to use them as well, according to the specification. 
Lastly, this introduce an API to let a client or server application cancel a request at any step.
=> H3 goaway implementation

quinn-proto/Cargo.toml, quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/spaces.rs, quinn-proto/src/streams.rs, quinn-proto/src/tests/util.rs
This had no visible performance benefit and may have created a HashDoS vulnerability.
Fixes #88.
=> Remove fnv hash

quinn-h3/src/body.rs, quinn-h3/src/client.rs, quinn-h3/src/connection.rs, quinn-h3/src/frame.rs, quinn-h3/src/proto/connection.rs, quinn-h3/src/qpack/dynamic.rs, quinn-h3/src/streams.rs
These are quick fixes to make the current H3 implementation work in an acceptable way.
A lot more is to come, as I've been working on the Stateful QPACK encoding for #360. But I think a separate PR to make things reasonably functional is necessary, before applying bigger architectural changes in the H3 connection driving part.
I've got #360 figured out, in a messy research branch [here](https://github.com/stammw/quinn/tree/h3-qpack-integration) and I'm starting over from the code of this very PR to bring a clean and comprehensive patch.
=>  H3: Trivial fixes for driver bugs

quinn/src/platform/unix.rs
These would fail decryption anyway, so this saves us some CPU.
=> Drop truncated UDP packets

quinn/src/connection.rs
ConnectionRef::clone was 7% of runtime for the small datagram benchmark.
=> Borrowing datagram futures

quinn-proto/src/assembler.rs, quinn-proto/src/frame.rs, quinn-proto/src/packet.rs, quinn-proto/src/spaces.rs, quinn-proto/src/streams.rs, quinn-proto/src/timer.rs
From the https://github.com/djc/quinn/issues/444 discussion, @Ralith said "I'm not necessarily opposed to it.", which was about improving encapsulation, therefore I decided to create this PR.
**Changes:**
- Added `pub(crate)` where possible `quinn-proto`. 
**Motivation:**
* I always prefer to limit the access and only expose public when needed. 
* All updated types are not used outside the crate and are not re-exported
* Reads cleaner, because the reader can know whether a type is used outside the crate or not
* Programmer does not expose types by accident.
**Prerequisites:**
* No breaking changes.
* Only updated quinn-proto
**Notice:**
* Structs with public fields can only be made `pub (crate)` when the struct it's self can also be `pub(crate)`. Please review and look for changes in …
=> Added 'pub (crate)' where possible quinn-proto.

Cargo.toml, bench/Cargo.toml, bench/src/bulk.rs
This produces vastly more comprehensible profiling output due to less nonsense in the stack samples. We'll probably ultimately want a collection of these.
=> Add minimal self-contained benchmark for easy profiling

quinn/src/endpoint.rs, quinn/src/platform/cmsg.rs, quinn/src/platform/fallback.rs, quinn/src/platform/mod.rs, quinn/src/platform/unix.rs, quinn/src/udp.rs
I noticed `sendmsg` was 35% of the flame graph for the large streams benchmark, so I finally had a go at this. It yields a roughly 15-30% improvement in each one of the throughput benchmarks! Oddly, `sendmmsg` is *still* about 35% of the flame graph, and cranking the batch size way up doesn't seem to help any. We'll probably need to dive into libc or the kernel or even investigate [generic segmentation offload](http://vger.kernel.org/lpc_net2018_talks/willemdebruijn-lpc2018-udpgso-paper-DRAFT-1.pdf) or similar to make further headway on this particular bottleneck.
=> Use sendmmsg to reduce system call overhead

quinn-h3/src/proto/headers.rs
Not quite sure why `local_addr` and `echo_v6` are failing under tarpaulin only...
=> Improve on some CI issues

quinn-h3/Cargo.toml
Otherwise `cargo update` fails.
Fixes #514
=> Fix the hyper upstream repository

quinn/src/connection.rs
This is the same PR as #512, which I accidentally closed.
=> Expose the peer address of a `Connecting`

interop/src/main.rs, quinn-h3/examples/h3.rs, quinn-h3/examples/shared/mod.rs, quinn-proto/src/crypto.rs, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/shared.rs, quinn-proto/src/tests/util.rs, quinn/src/builders.rs, quinn/src/lib.rs, quinn/src/tls.rs
These were not successful at removing rustls from our public API, and made specifying custom cryptographic configurations unintuitive. Removing them reduces the scope of our public API while preserving the friendliness of the high-level quinn API.
=> Remove quinn-proto rustls config newtypes

interop/Cargo.toml, quinn-h3/Cargo.toml
The 0.2.x branch got rebased to master, invalidating the commit we were
depending on previously. Depend on an older commit that has the HTTP 3
version but has not upgraded to bytes-0.5 for now.
=> Update the dependency on http to a rebased commit

quinn/examples/client.rs, quinn/src/connection.rs, quinn/src/endpoint.rs
Non-obvious details identified in the course of assisting a new user.
=> Document a NewConnection footgun and the meaning of server_name

quinn-proto/src/connection.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/frame.rs, quinn-proto/src/shared.rs, quinn-proto/src/streams.rs, quinn/src/connection.rs, quinn/src/streams.rs
A few errors were spared because they were using std::io::Error
internally.
Fixes #549
=> Add PartialEq, Eq impls to errors throughout the library

quinn/Cargo.toml, quinn/src/connection.rs
Backports #553 to the (newly created) 0.5 branch. Let's release this in a 0.5.1 as it's affecting @LaylConway's published crate.
=> Fix missing wakeup on datagram send (backport to 0.5)

quinn/src/lib.rs
Noticed this low-level-only enum exported from the high level crate when skimming the docs.
=> Remove inappropriate reexport

interop/Cargo.toml
CI probably missed this because it's implied by another crate.
=> Fix missing tokio feature in interop tool

quinn-proto/Cargo.toml, quinn/Cargo.toml
Need this too due to aa80f285ad7d89110ce5a2d86508141eb861120a, whoops!
=> Bump quinn-proto version to 0.5.2

quinn-proto/src/connection.rs, quinn-proto/src/lib.rs, quinn-proto/src/shared.rs, quinn-proto/src/tests/mod.rs, quinn/benches/bench.rs, quinn/src/connection.rs, quinn/src/lib.rs
Applications sending datagrams are expected to prioritize freshness, at the cost of reliability if necessary. Blocking datagram sends when the buffer is full is inconsistent with that, particularly if congestion arises due to a low-priority bulk data stream. Instead, we should opt to discard old data in favor of newly sent data. The significant API and implementation simplification (including the capacity to trivially send datagrams from synchronous code!) is a nice bonus.
CC @LaylConway for thoughts, as the current known user of this API. Note that this only changes behavior on congested links.
=> Simplified, synchronous datagram send API

interop/Cargo.toml, interop/src/main.rs, quinn-h3/src/client.rs, quinn/src/lib.rs
If you guys see other subjects to adress, I'd be pleased to implement them.
Do we have to stick with the manual runtime syntax ?
Could it be interesting to run each endpoint interop in parallel ?
=> Interop client enhancement

quinn-proto/src/lib.rs, quinn-proto/src/transport_parameters.rs
@Ralith I was trying to figure out how to add doc attributes to your macro contraption (by prepending `#[$doc:meta]` to the pattern lists) but so far didn't succeed. Any clues on this?
Interestingly, `TransportParameters` is already somewhat public (cannot be made `pub(crate)`) since it appears in a public interface, but it cannot be named from external crates as far as I can tell. This makes it available (but not at the top-level, since most implementers shouldn't need it).
Doing this on the maintenance branch first, we can then merge it into master. Going in that direction can be slightly more straightforward than going the other way around.
=> Pub transport params

interop/src/main.rs, quinn-h3/examples/h3_client.rs, quinn-h3/examples/h3_server.rs, quinn-h3/src/body.rs, quinn-h3/src/client.rs, quinn-h3/src/connection.rs, quinn-h3/src/proto/connection.rs, quinn-h3/src/proto/frame.rs, quinn-h3/src/proto/headers.rs, quinn-h3/src/proto/mod.rs, quinn-h3/src/streams.rs
Fixes needed to get better results at interop, along with some tooling and tracing.
=> H3 interop fixes

quinn-proto/src/connection.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests/util.rs, quinn-proto/src/timer.rs, quinn/src/connection.rs, quinn/src/tests.rs
=> Simplified timers and a bugfix

interop/src/main.rs, quinn-proto/src/connection.rs, quinn-proto/src/crypto/ring.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/shared.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn-proto/src/transport_parameters.rs, quinn/benches/bench.rs, quinn/examples/common/mod.rs, quinn/examples/server.rs, quinn/src/builders.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
=> Opaque config structs

quinn-proto/src/constant_time.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/shared.rs
Fixes #585. Opted to inline the constant time eq comparison based on the (CC0) constant_time_eq crate in the spirit of keeping the depgraph down.
=> Compare reset tokens in constant time

bench/src/bulk.rs, interop/src/main.rs, quinn-debug, quinn-h3/examples/h3_client.rs, quinn-h3/examples/h3_server.rs, quinn-h3/src/client.rs, quinn-h3/src/connection.rs, quinn-h3/src/server.rs, quinn-proto/src/endpoint.rs, quinn/Cargo.toml, quinn/benches/bench.rs, quinn/examples/client.rs, quinn/examples/common/mod.rs, quinn/examples/connection.rs, quinn/examples/insecure_connection.rs, quinn/examples/server.rs, quinn/examples/single_socket.rs, quinn/src/broadcast.rs, quinn/src/builders.rs, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/lib.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
We're already reliant on tokio's thread locals for UDP socket and timer registration, and [`Handle::enter`](https://docs.rs/tokio/0.2.6/tokio/runtime/struct.Handle.html#method.enter) provides adequate mechanism to route spawns to a particular runtime if absolutely needed, so passing driver tasks to the user explicitly wasn't buying us much considering how big a footgun it is.
=> Spawn driver tasks implicitly

quinn/src/connection.rs
=> Expose client-supplied server name

quinn-proto/src/assembler.rs
Here's an attempt at solving that old memory fragmentation issue. The 32 threshold is just a simple heuristic: in the worst case we accept 32 1-byte chunks from 32 different datagrams, 32k of unnecessary allocations, but hopefully most applications would not get up to 32 chunks in the buffer so that they would not trigger the (relatively slow) defragmentation code.
Let me know what you think!
=> Defragment incoming stream chunks (fixes #431)

interop/Cargo.toml, interop/src/h3_server.rs, quinn-h3/src/body.rs, quinn-h3/src/connection.rs, quinn-h3/src/frame.rs, quinn-h3/src/proto/frame.rs
I've been working on this `H3` interop server to deploy on h3.stammw.eu.
I'm not sure we'll want to merge this into quinn as it may be out of scope?
The reasons why I think we need to separate h3 interop from the example code are:
- Interop already needs / will need a different set of features. For example transfer tests are based on urls like `https://example.com/100M`
- The example code will be kept simple
- It may be interesting to implement remote logging for people running their interop client against this endpoint. They could filter by IP or CID with a simple web app served via h1/h2.
~For the moment I'm stuck on a bug where requesting more than 1,6M  results in the client missing the tail of a `Data` frame. Receiving the start of a fresh Data frame instead.~
This PR also contains …
=> H3 interop server and assorted fixes

quinn-proto/Cargo.toml
This isn't used anywhere outside of tests.
=> Make lazy_static a dev-dependency only

quinn-h3/Cargo.toml, quinn-h3/src/client.rs, quinn-h3/src/connection.rs, quinn-h3/src/lib.rs, quinn-h3/src/qpack/vas.rs, quinn-h3/src/server.rs, quinn-h3/src/tests/helpers.rs, quinn-h3/src/tests/mod.rs, quinn/src/builders.rs
This PR mainly fixes the `IncomingRequest` stream not resolving when a driver error occurs.
It also fixes driver behaviour when an on error: depending on the error type, it should send a `CONNECTION_CLOSE` frame or not. 
Logging the driver stop reason as an error is also not always pertinent. It depends on what  triggered it.
I'm currently writing a test to check the `IncomingRequest` resolving, but once again i'm blocked because I try to create a generic helper that helps to shorten the test itself.
=> H3 fix user's facing Futures behaviors on driver errors

quinn/src/platform/unix.rs
Hi there! We recently updated the quinn version used in [maidsafe/quic-p2p](https://github.com/maidsafe/quic-p2p) to 0.5.3. But after this update we noticed that our Android & iOS builds were failing. This is because `rustls-native-certs` doesn't support Android and iOS (See ctz/rustls-native-certs#3).
Since it's a feature-enabled dependency (enabled by default), I disabled the default features and tried compiling quinn for Android & iOS. The Android build [was successful](https://github.com/maidsafe/safe_client_libs/runs/443170367?check_suite_focus=true), but the iOS [build failed](https://github.com/maidsafe/safe_client_libs/runs/443170238?check_suite_focus=true#step:9:876).
The platform-native API for Mac and iOS are the same so adding this condition gave us a [passing …
=> Include iOS in the conditional compilation for mac platforms

quinn/src/connection.rs, quinn/src/tls.rs
So this would be my take on #567. 
It turns out that there is already a wrapper for `rustls::Certificate`, so we're not leaking implementation details. The bigger design concern, iiuc, is that TLS is not the only possible crypto protocol for QUIC -- however, `quinn` already commits to TLS. It is also the case that the SNI hostname (which is quite TLS-specific) is accessible at various places even in `quinn-proto`.
An alternative, but much more intrusive approach I considered first was to define an associated datatype for `quinn_proto::crypto::Session`, which abstracts over the type of authentication data applicable to the concrete session. Something like this:
```rust
pub trait Session: Sized {
// ...
type AuthenticationData;
fn authentication_data(&self) -> Self::AuthenticationData;
}
// …
```
=> QUINN: Allow retrieving the peer's certificate chain from a connection

interop/src/main.rs, quinn-h3/src/client.rs, quinn-h3/src/connection.rs, quinn-h3/src/lib.rs, quinn-h3/src/proto/connection.rs, quinn-h3/src/proto/frame.rs, quinn-h3/src/proto/mod.rs, quinn-h3/src/proto/settings.rs
This PR brings to settings:
* A way to validate the settings as the user set them
* This will make it possible to make some `Settings` usage infallible in lower layers, as a `Settings` struct is always valid now.
* Addressing  #521, only protocol's non-default values are sent.
* Differentiate protocol's defaults and crate's recommended values (used as default).
=> Refactor H3 settings for validation and defaults management

quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/tests.rs
Fixes one of the issues found in #645.
=> Expose established connections even if they were later lost 

quinn-h3/src/tests/mod.rs
Another tentative to fix the flakyness of `incoming_request_stream_ends_on_client_*()`. The test was actually wrong, because making a request here will advance server beyond `incoming.next().await`. Which _is_ the line we want to test.
Hope it will remove the flakiness.
There was this problem happening:
Calling server's `body_writer.close().await` will timeout if the client's connection is closed beforehand. 
Client closure uses `quinn::Connection::reset()` under the hood: I guess the server receives something even if it is not `.await`able ?
So any call should resolve on the server at the moment it receives the `CONNECTION_CLOSE` (including `BodyWriter::close()`)?
=> H3: don't run request before client closure tests

bench/Cargo.toml, quinn-h3/src/frame.rs
Mainly addresses #355.
This PR sets the size of the framed read buffer to the size of one UDP packet payload. Thus reducing the chances of reallocations needed to parse an entire http frame.
It uses a new feature of `tokio-util` made available in `0.3.0`.
Some benchmarks have been added to assert the throughput enhancement.
Also brings connection closure fix and its test.
=> H3 adjust read buffer size form decoding

quinn-proto/src/crypto/types.rs
Trying to integrate #644 I realise I'm kind of back to square one, because I can't get at the actual certificate :)
=> Provide an iterator for CertificateChain

quinn-h3/src/tests/mod.rs
As a quick response to #673, let everyone use the CI as async tests are broken and tiemout or fail when run under tarpaulin.
Fixing the test is currently addressed in the mean time.
=> H3: Temporarily disable async tests in coverage

quinn-h3/src/tests/mod.rs
To see if #686 has fixed them.
=> H3: Test re-enabling h3 async tests after busy-loop fix

quinn-proto/src/cid_queue.rs, quinn-proto/src/connection.rs
Fixes #689, which turned out to be a regression introduced in #683.
This bug caused unintended `RETIRE_CONNECTION_ID` frames to be sent for active remote CID when a duplicate `NEW_CONNECTION_ID` frame was received containing it. The peer responded to that packet with a `NEW_CONNECTION_ID` to replace the retired CID, triggering a false `CONNECTION_ID_LIMIT_ERROR`. Additionally, future packets received by the peer elicited a stateless reset, as they still bore the retired CID. These stateless resets raced with the `NEW_CONNECTION_ID`, sometimes causing an unexpected connection reset before the `CONNECTION_ID_LIMIT_ERROR` was triggered.
Thanks to @DemiMarie-parity for the brute-force testing that identified this issue! As an issue that only arose when certain packets are spuriously …
=> Connection ID fixes

interop/src/main.rs, quinn-h3/src/client.rs, quinn-h3/src/connection.rs, quinn-h3/src/lib.rs, quinn-h3/src/proto/connection.rs, quinn-h3/src/proto/mod.rs, quinn-h3/src/qpack/encoder.rs, quinn-h3/src/server.rs, quinn-h3/src/tests/mod.rs
Response cancellation and GoAway were not exposed to the public API and the former was unfinished. 
This PR is based on #653, so we should merge this one first.
=> H3 expose missing features in the public API

bench/Cargo.toml, interop/Cargo.toml, quinn-h3/Cargo.toml, quinn-h3/benches/bench.rs, quinn-proto/Cargo.toml, quinn/Cargo.toml, quinn/benches/bench.rs
I never found criterion's statistics to be correct, and it has a *lot* of dependencies. Results in 32 fewer dev-dependencies.
=> Replace criterion with bencher

quinn-proto/Cargo.toml, quinn-proto/src/connection.rs, quinn-proto/src/streams.rs, quinn-proto/src/tests/mod.rs, quinn/Cargo.toml
Although we were correctly setting the data limit for the send half of initially-available remotely-initiated bidirectional streams, we neglected to apply the limit to streams made available by stream ID flow control updates. As a result, the application would be erroneously prevented from writing to the send half of bidirectional streams opened by the peer after the initial stream_window_bidi streams.
Fixes #694.
=> Fix initial data limit for remotely initiated bidirectional streams

interop/Cargo.toml, interop/src/main.rs, interop/src/server.rs
Introducing a `HTTP/2` endpoint in interop tests to compare throughput with current implementation pair. Feat. `hyper`.
=> Interop throughput

quinn-h3/benches/bench.rs, quinn-h3/src/server.rs
The new bench tool call top-level bench functions multiple times (`throughput_1k` for example). Kill the server at the end of each call fixes the failures this introduced.
=> H3 fix bench

quinn-h3/Cargo.toml, quinn-h3/src/qpack/prefix_string/decode.rs, quinn-h3/src/qpack/prefix_string/encode.rs
bitlab was a bit of an odd dependency, providing some convenience wrappers for writing bits across byte slices. It additionally pulled in the num crate. Replace it by writing our own version of the bit reading/writing routines, which should amount to much less code and is more optimized for our use case since a number of checks can be elided.
I'm not a very experienced bit twiddler and it took me way too long to get the encode side working. Happily we have pretty good regression tests for this stuff! Any feedback is welcome.
=> Replace bitlab dependency with homegrown bit twiddling

quinn-proto/src/connection.rs, quinn-proto/src/frame.rs, quinn-proto/src/lib.rs, quinn-proto/src/range_set.rs, quinn-proto/src/send_buffer.rs, quinn-proto/src/spaces.rs, quinn-proto/src/streams.rs, quinn-proto/src/tests/mod.rs
Improves stream frame packing and establishes groundwork for intelligent selection of which stream to transmit for.
Fixes #561.
This is a major internal refactoring; prior drafts broke a bunch of tests and non-obvious further breakage is very possible. In the interest of making a robust release, let's take care not to merge this prior to 0.6.1.
=> Store outgoing stream data with stream state

interop/Cargo.toml, quinn-h3/examples/h3_server.rs
Fixes #743. In most environments, this will produce a dual-stack socket, supporting both IPv4 and IPv6.
=> Listen on IPv6 by default in h3 server example

interop/Cargo.toml, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/crypto.rs, quinn-proto/src/crypto/ring.rs, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/packet.rs, quinn-proto/src/tests/mod.rs
Allows more graceful handling of the one-directional 0-RTT keys, and paves the way for secrets to no longer be exposed from rustls.
Motivated by #740. Merging this separately will avoid severe rebase hazards, given that the rustls release cycle is quite slow.
=> Decouple secrets from keys, split keys

bench/Cargo.toml, interop/Cargo.toml, quinn-h3/Cargo.toml, quinn-proto/Cargo.toml, quinn/Cargo.toml
From the Cargo docs:
"Previously multiple licenses could be separated with a /,
but that usage is deprecated."
https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
=> Update license to proper SPDX expression

quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs
As of current master in the datagram draft, you no longer need to accept datagrams to send them. See https://github.com/quicwg/datagram/pull/11.
=> Update datagram transport parameter to one-way semantics

quinn/src/builders.rs
Helps avoid apparently expensive `ClientConfig::default()` calls.
=> Endpoint client config reuse

quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/transport_parameters.rs, quinn/src/endpoint.rs
Reduces memory use a bit, a benefit which will be compounded dramatically when we switch to receiving multiple packets per syscall, via `recvmmsg` or other means.
=> Allocate exactly the necessary receive buffer size

quinn/src/streams.rs
By treating the read error as a component of, rather than an incidental ancestor to, the enclosing error we reduce the odds of unhelpful diagnostics.
=> Include ReadError in ReadToEndError::Read display

interop/src/main.rs, quinn-proto/src/config.rs, quinn-proto/src/congestion.rs, quinn-proto/src/congestion/new_reno.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/lib.rs
As discussed in #693. ~Draft until the abstractness of the interface has been validated by the addition of at least one other controller (probably CUBIC/HyStart++).~
=> Pluggable congestion control

quinn-h3/src/tests/helpers.rs, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/tests/mod.rs
Fixes #441. Mild hack, but brings us closer to compliance, helps prevent people from relying on incorrect behavior, and will be easy to improve if rustls gets a richer API.
=> Reject connections on ALPN failure

quinn-proto/src/connection/assembler.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams.rs, quinn-proto/src/tests/mod.rs, quinn/src/streams.rs
Previously, flow control credit would not be issued for data received
on stopped streams unless the application continued reading them
indefinitely. This produced a flow control leak in the high level API,
causing applications which dropped streams with unread data to
eventually grind to a halt.
Discarding data immediately should also improve performance when data
is being received on stopped streams, and allows us to discard stream
state earlier.
=> Proactively discard data on stopped streams

quinn-h3/src/connection.rs, quinn-h3/src/frame.rs, quinn-h3/src/proto/frame.rs, quinn-h3/src/tests/helpers.rs, quinn-h3/src/tests/mod.rs
Addresses the two failing tests on [quic tracker](https://quic-tracker.info.ucl.ac.be/grid).
=> H3 ignore unknown frames and uni streams

quinn-h3/src/connection.rs, quinn-h3/src/data.rs, quinn-h3/src/server.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams.rs, quinn-proto/src/tests/mod.rs, quinn/src/streams.rs
Improves consistency with other stream interfaces. H3 logic was
updated to ignore errors to preserve existing behavior, but future
work might want to insert some unwraps there if static correctness
guarantees are available.
=> Return UnknownStream from Connection::reset for closed/reset streams

Cargo.toml
Disables the forbidden legacy_session_id field in ClientHello and fixes our key updates.
=> Update rustls for interop fixes

quinn-proto/src/config.rs
We'll want to shrink this back down when we implement recvmmsg or uring support, but for now this should improve interop.
=> More generous default receive buffer size

quinn-h3/src/data.rs, quinn-h3/src/lib.rs, quinn-h3/src/tests/mod.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams.rs, quinn-proto/src/tests/mod.rs, quinn/src/connection.rs, quinn/src/lib.rs, quinn/src/streams.rs
Addresses #723.
It adds a `StreamEvent::Stopped` variant to carry a `STOP_SENDING` event to the user.
=> H3 poll reset

quinn-proto/src/connection/assembler.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams.rs, quinn-proto/src/range_set.rs, quinn/src/streams.rs, quinn/tests/many_connections.rs
Fixes #735. Should marginally improve performance for ordered reads due to isolation of the (now somewhat more) complex `RangeSet` operations to the unordered case where they're necessary, leaving simple cursor-based logic for ordered behavior.
=> Refactor receive stream buffering

quinn-proto/src/endpoint.rs, quinn-proto/src/packet.rs
It's unreasonable to emit a version negotiation packet that permits the version the peer requested.
=> Ensure version negotiation grease is valid

quinn-h3/src/body.rs, quinn-h3/src/client.rs, quinn-h3/src/lib.rs, quinn-h3/src/proto/connection.rs, quinn-h3/src/proto/headers.rs, quinn-h3/src/server.rs, quinn-h3/src/tests/helpers.rs, quinn-h3/src/tests/mod.rs
This is part of draft-28 update for #785. Adressing draft's [3558](https://github.com/quicwg/base-drafts/pull/3558/files).
Authoritative header values still have to be checked against certificates values. Do you have some recommendations before I start to look for a solution on my own ?  Here is the extract I'll address:
> Once a connection exists to a server endpoint, this connection MAY be reused for requests with multiple different URI authority components. In general, a server is considered authoritative for all URIs with the "https" scheme for which the hostname in the URI is present in the authenticated certificate provided by the server, either as the CN field of the certificate subject or as a dNSName in the subjectAltName field of the certificate; see [RFC6125]. For a host that …
=> H3: check :authority and Host headers

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/spaces.rs
> [ECN counts are maintained separately for each packet number space.](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-ecn-counts-2)
=> Separate ECN counters per space

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/spaces.rs
Improves ergonomics and simplifies borrowing.
We tried this originally but were, iirc, blocked by a rustc coherence checker limitation which has since been resolved.
=> Replace space accessors with indexing

quinn/src/connection.rs, quinn/src/lib.rs, quinn/src/streams.rs
Specifically, this PR enables the use of `StreamId`s from `SendStream`/`RecvStream`, implements `Hash`, `PartialEq`, and `Eq` for `Connection`, and adds a way to get a static ID for a `Connection` since IP addresses may change during the lifetime of a QUIC connection.
I'm not sure `Connection::index()` is the greatest name for a function that does that last part, but it's consistent with how `StreamId`s work. It might be more discoverable if it were named something like `quic_address()`, but I'll leave it to the maintainers to make that decision.
=> Expose some inner workings of quinn-proto in quinn

quinn-proto/src/connection/mod.rs, quinn-proto/src/tests/mod.rs
The behavior of the client in this case is a bit weird, but [correct](https://tools.ietf.org/html/rfc8446#appendix-E.1.2).
CC @DemiMarie-parity, particularly regarding the added state documentation.
=> Test rejection of client connections missing a required certificate

quinn-h3/src/data.rs, quinn-h3/src/server.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams.rs
Fix some documentation links in `quinn-proto` and `quinn-h3` that `cargo doc` was complaining about.
`quinn-proto` had some links that did not point to the correct locations, so these were updated to point to `enum` variants as well.
`quinn-h3` made references to structs that no longer seem to exist so this was updated too.
=> Fix documentation in quinn-proto and quinn-h3

quinn-proto/src/config.rs
See https://github.com/quicwg/base-drafts/pull/3823.
=> Correct default initial RTT

quinn/src/builders.rs, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/streams.rs
Add documentation links and references to some of the main parts of the API so
that relevant structs, enums and methods can be navigated to more quickly. This
reduces the need for the search bar and thus makes it easier to find related
content wherever it is mentioned.
=> Add documentation links to improve navigation

.github/workflows/codecov.yml, .github/workflows/rust.yml
It won’t work, as those builds don’t have access to the CodeCov API
token.
=> Don’t try to run code coverage on PRs

quinn-proto/src/crypto/types.rs
I found `quinn::Certificate` missing a `from_pem` function when I use pem format certificates, just add it.
=> certificate: accept pem format

quinn-h3/src/client.rs, quinn-h3/src/connection.rs, quinn-h3/src/data.rs, quinn-h3/src/proto/connection.rs, quinn-h3/src/server.rs, quinn-h3/src/tests/helpers.rs, quinn-h3/src/tests/mod.rs, quinn-proto/src/lib.rs
Make it possible to gracefully shutdown the connection from the client, as described in draft-29. 
This is not very useful as long as server push is not implemented.
=> H3: accept goaway from client

quinn-proto/src/crypto/rustls.rs
This enables deriving `Debug` for other structures used in `quinn` that use `TlsSession` as a session type (for example `Incoming`, `Endpoint` etc),  which in turn enables 3rd parties structures to derive `Debug` easily when they use said structures in their code.
Addresses #841
=> Derive Debug for TlsSession and SessionKind

quinn/src/platform/unix.rs
fix  https://github.com/djc/quinn/issues/848
=> fix iOS setsockopt invalid params

bench/Cargo.toml, interop/Cargo.toml, quinn-h3/Cargo.toml, quinn-proto/Cargo.toml, quinn-proto/src/crypto.rs, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/tests/mod.rs, quinn/Cargo.toml, quinn/src/connection.rs, quinn/src/tests.rs
This PR adds support for the export_keying_material method from rustls. Specifically:
- adds a trait, `proto::crypto::ExportKeyingMaterial`, that can be implemented on a `proto::crypto::Session`. I did this rather than implement it as part of `Session` because future crypto impls might not provide this functionality. Of course, can move it to `Session` if that would be better.
- implements `ExportKeyingMaterial` for `proto::crypto::rustls::TlsSession`, which calls the corresponding method on the rustls `Session` object.
- implements `export_keying_material` method on `quinn::Connection<S> where S: ExportKeyingMaterial`, which is just plumbing.
- tests `export_keying_material` in both `proto` and `quinn`.
To test this, you'll need to point to the current main branch of rustls in quinn and …
=> expose export_keying_material from rustls

quinn-proto/src/cid_generator.rs, quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/shared.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/token.rs, quinn-proto/src/transport_parameters.rs
Currently Quinn generates cid using random number only. Some use case may require a more sophisticated cid structure. This change mainly add a `ConnectionIdGenerator` trait that allows to use any customized cid generator.
=> Support customized Cid generation

quinn-proto/src/config.rs, quinn-proto/src/crypto.rs, quinn-proto/src/crypto/ring.rs, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/token.rs
**DISCLAIMER**: I am a first time contributor (Rust and QUIC).
I would like some feedback on the direction of this :slightly_smiling_face: 
Resolves #783 , following changes have been introduced,
- `master_key` has been added to `ServerConfig` for aiding AEAD key derivation
- A new trait `AeadKey` has been introduced which provided following API,
- `from_hkdf` : derive a AEAD key using `master_key` and some `random_bytes`
- `seal`: seal a message with the given AEAD key
- `open`: open a message with a given AEAD key
~TODO~
- `[test]` scenario when a garbage retry token is received and the opening operation fails
=> [#783] Encrypt retry token

quinn/src/connection.rs
This dates from when connection drivers were external.
=> Remove dead code

quinn-proto/src/connection/assembler.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests/util.rs, quinn/examples/server.rs
The conversion from Vec<u8> into Box<[u8]> is not always for free.
It will call `Vec::into_boxed_slice`, which will call `shrink_to_fit`.
https://github.com/rust-lang/rust/blob/28f03ac4c08fc7ec62428d0b914e1510ce7ee2cb/library/alloc/src/vec.rs#L689
If the `Vec` isn't fully utilized before, this will cause a reallocation
and a copy of all data. This might currently happen with every
outgoing packet.
This change simply keeps things as `Vec<u8>`, which works just fine since
the IO layer can deal with it.
=> Use vectors instead of boxed slices

README.md, quinn-proto/src/connection/mod.rs, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/packet.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/transport_parameters.rs
Incorporates all documented changes between draft 29 and the wg master, excluding h3. Nothing major.
=> Update to draft 32

quinn-proto/src/connection/streams.rs
The current version of Quinn tries to enqueue a MAX_STREAM_DATA
update after every read from the stream. Those could potentially be
tiny. Besides wasting network capacity with sending tiny packets, that
behavior also causes a wakeup on the connection task.
This change triggers MAX_STREAM_DATA frames only to be enqueued
if they are deemed significant enough. In the version here, this means
is bound to 12.5% of the overall window - but this could be changed.
Note that the general connection task wakeup after reads is still there.
A similar change would need to be performed for updating the
connection window, in order to determine whether the connection task
wakeup is still necessary.
I gathered some example metrics for the amount and increment of window
updates in the benchmark:
Before:
Num …
=> Send only significant MAX_STREAM_DATA updates

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/stats.rs, quinn-proto/src/connection/streams.rs
This change adds some structs which track connection-level statistics.
These are rather helpful to determine how the implementation performs,
and which impact certain changes have.
The implementation is not complete. It's just a first step on getting
some more visibility into the transmitting side of the library. More
statistics - e.g. around congestion control, retransmission, timing, etc
could be added.
The stats are currently private, and I just debug printed them so far
where found useful. They could however be public if the API is fine.
Another possibility is to have the stats behind a feature flag if people
are concerned about extra memory usage.
=> Add connection level statistics

quinn-proto/src/cid_queue.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/shared.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/transport_parameters.rs
As requested in https://github.com/quinn-rs/quinn/pull/860, this PR extracts code change particularly for fixing existing bugs when processing cid retirement.
Currently in quinn-proto, retire_prior_to field in `NEW_CONNECTION_ID` frame is constantly set to 0 which means the logic for cid retirement is not properly tested and thus a few bugs are found.
1. quinn-proto maintains both `rem_cid` (as active remote cid) and `rem_cids` (in CidQueue as cid candidates). In a corner case, we may need to pick one candidate from `rem_cids` to replace `rem_cid`. However, current code cannot properly handle this case as `update_rem_cid` is always called after `insert` function of CidQueue. Please follow the added unit test to understand the details.
2. Based on RFC, "An endpoint SHOULD supply a new …
=> Bug Fix when accepting and retiring connection ID

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/stats.rs
This adds the same set of stats for received datagrams
that have been merged previously for transmitted datagrams.
=> Packet reception stats

quinn/examples/README.md, quinn/examples/client.rs, quinn/examples/connection.rs, quinn/examples/insecure_connection.rs, quinn/examples/server.rs, quinn/examples/single_socket.rs
Create a new example README, this should provide the user with a single entry point for the examples. As a new user of this library, I found it somewhat hard to get a quick idea of what each example its purpose was and how to navigate them quickly.
- Create an example readme with detailed instructions. 
- Change module comments from example files to a redirection to this README.
=> Create example README

quinn/src/builders.rs
A CID generator interface was implemented in transport layer https://github.com/quinn-rs/quinn/pull/851 but there is still no way to actually enable this feature when HTTP/3 endpoint is built. This PR provides an API in `EndpointBuilder` to allow customization on CID generator.
=> Expose cid genearator customization API in endpoint builder

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams.rs, quinn-proto/src/frame.rs
This is an update to #893 which uses a newtype to indicate whether an outgoing frame needs to be enqueued.
The update is in the second commit.
#893 could be merged before this - or this can be extended and replace the orginal CR.
=> Send only significant MAX_DATA frames (2)

quinn/examples/client.rs, quinn/examples/server.rs
Just one proposal to prevent issues like #77 (which I think we've seen a few times). Bikeshedding on the most lucent and concise way to explain this welcome. (Also, do we need something like this in other places, maybe the example's docstrings?)
=> Add README note about address families

quinn-proto/src/endpoint.rs, quinn/src/endpoint.rs
Catches some common user errors that would otherwise manifest as difficult-to-diagnose I/O errors.
=> Sanity-check remote addresses before trying to connect

quinn/src/streams.rs
Ensures that the resulting io::Error's dynamic type is constant and
its Display impl includes the "connection closed: " clarifying
context.
=> Always preserve outer type when converting to io::Error

quinn-proto/src/connection/streams.rs
The current version of send multiplexing tries to send as much data from
a single stream as possible before switching over to the next stream.
The only situation where data from another stream than the original one
is sent is if there are no peer flow control credits available anymore,
or if the application didn't feed new data.
If none of this situations occur, other streams will be starved.
This is typically not what people expect, and can lead to high latencies
on streams which are queued behind earlier streams.
This change makes the send behavior "fairer" by enqueuing stream which
just have sent data **after** all other pending streams instead of in
front of them. This is simply achieved by switching to a `VecDeque` and
using the the right insert/remove orders.
Stats (obtained via …
=> Improve fairness on stream transmissions

quinn/benches/bench.rs
This extends the "cargo bench" benchmark to test transmission of data
on multiple streams in parallel.
Ideally we would want all transmission to take a similar amount of time
(bandwidth shared fairly), and the overall throughput to stay the same
or increase (but never degrade) when multiple streams are in use.
The benchmark can not show the fairness aspect very well, since it only
prints an overall throughput. But it shows that performance with
multiple streams stays similar.
Output:
```
running 4 tests
test large_data_10_streams  ... bench: 180,761,260 ns/iter (+/- 12,090,679) = 58 MB/s
test large_data_1_stream    ... bench:  18,459,500 ns/iter (+/- 3,804,219) = 56 MB/s
test small_data_100_streams ... bench:   4,600,890 ns/iter (+/- 373,842)
test small_data_1_stream    ... bench: …
```
=> Extend benchmark for concurrent streams

quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/platform/fallback.rs, quinn/src/platform/unix.rs, quinn/src/tests.rs, quinn/src/udp.rs
When a listener is bound to multiple network interfaces (e.g. `::0`),
it is not obvious which IP the peer used to send a packet. We however
might need this information to send packets back to the peer with the
same source address.
This problem is described in #508.
This change makes the destination IP address which was used to send
the initial packet available in the `Conneting` and `Connection` types.
The information is far available only on Linux due to missing test on
other platforms.
=> Allow to lookup the initial local IP address

bench/Cargo.toml, bench/src/bulk.rs
This change improves the bulk benchmark:
- The total amount of requests the benchmark performs can be configured
- The amount of concurrent requests on a given connection can be
configured
- The amount of data to transfer per stream can be configured
E.g.
```
bulk --streams 300 --max_streams 100 --stream_size 10
```
will create 300 streams - with a maximum of 100 active streams at a time,
and send 10MB of data on each stream.
The "short" cli flags are taken form h2load where applicable.
The benchmark now also shows metrics which indicate the performance
of individual streams, which allows to judge fairness. Example output:
```
Overall stats:
Sent 3145728000 bytes on 300 streams in 12.11s (247.81 MiB/s)
Stream metrics:
│  Throughput   │ Duration
──────┼───────────────┼──────────
AVG  │ …
```
=> Extend bulk benchmark

quinn-proto/src/connection/mod.rs, quinn-proto/src/lib.rs, quinn/src/connection.rs
So far those haven't been consumable by applications.
This makes the struct public, and adds an accessor
for `quinn_proto::Connection` and `quinn::Connection`.
=> Make connection stats public

quinn-proto/src/config.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/src/endpoint.rs
Enables stronger latency guarantees, along the same lines as #961.
=> Limit concurrent connections rather than accept queue size

quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn/Cargo.toml, quinn/src/platform/fallback.rs, quinn/src/platform/mod.rs, quinn/src/platform/unix.rs
This splits out the platform/socket parts for UDP GSO support
from #953 to reduce the amount of code to review.
This change mainly implements setting the segment size
socket option, and adds a runtime detection mechanism for
GSO support.
=> GSO platform support

quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn/src/platform/unix.rs
This is a follow-up for #943. When a socket is bound to a wildcard
IP address, sending the outgoing IP might use a different source IP
address than the one the packet was received on, since the OS might
not be able to identify the necessary route. This would lead packets
not allowing to reach the client.
This change adds a setting which will set an explicit source address
in all outgoing packets. The source address which will be used is
the local IP address which was used to receive the initial incoming
packet.
=> Allow to use the incoming IP address for sending outgoing packets

README.md
Update logo link as discussed in gitter, currently it doesn't show in the book because it is a relative link.
=> Logo update to static link.

quinn-proto/src/connection/assembler.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams.rs, quinn-proto/src/tests/mod.rs, quinn/src/streams.rs
Hello !
I've started trying to implement #929.
Still I'd better be adding some tests before its ready. So I'm setting this PR WIP for a first feedback.
=> Read ordered chunks from RecvStream

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/stats.rs
This adds frame stats for the receiving part, which had been
missing so far.
=> Rx frame stats

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/stats.rs
This is an alternative version of #972, where we add the new stats
to ConnectionStats instead of exposing additional accessors.
The naming of `recovery` could probably be improved. `path` might
be an option. But where would we add something like packet loss?
That seems more like an overall stat.
=> Add recovery stats as part of ConnectionStats

quinn-proto/src/congestion.rs, quinn-proto/src/congestion/new_reno.rs, quinn-proto/src/connection/mod.rs
This change fixes 2 issues in the congestion controller:
Extra slow slow start
===
The congestion controller had an issue where it didn't ramp up by
doubling the window in the slow start phase as expected. The reason
here was the usage of the "congestion_blocked" field, which aims to
remove the avoid growing the window when there is no data to send.
The issue with the field was that the first incoming ACK for every batch
would increase the congestion window, which would let the next
call to `congestion_blocked()` return false, and thereby let the
congestion controller ignore all of the following ACKs in a received
batch up the point where the next `poll_transmit()` call is made and
the window is filled again. Since often all ACKs for one round-trip
arrive in a single batch that means only …
=> Congestion controller fixes

docs/book/src/SUMMARY.md, docs/book/src/quinn/certificate.md
This PR is part of a series of PR's regarding the book creation as described in #865. Each page of this chapter will have its own PR for reducing PR size.
- Network Introduction (#917)
- QUINN Introduction (#868)
**- Certificate Configuration (#920)**
- Connection Setup (#921)
- Data Transfer (#922)
A live version of this page can be found [here](https://timonpost.github.io/quinn/). This book shows all the work that I have up-to-now. The pages that are visible but don't have a PR yet should are welcome to have general feedback.
This chapter will go through the protocol by examples. The chapters are in the required order, first, we look at configuring a certificate which is **required**, then at setting up a connection, and finally at sending data about this connection. In the future, more …
=> (2) Quinn Introduction Chapter, Certificate Configuration Page

quinn-proto/src/connection/send_buffer.rs, quinn-proto/src/connection/streams.rs, quinn-proto/src/range_set.rs
During testing with a multithreaded runtime I discovered that threads
block a fair amount of time on Mutexes, even though everything in the
state machine should be non-blocking.
By inserting some more timing checks I discovered that the `poll_write`
call took more than 10ms and locked the Mutex for this duration. This
happened due to the `BytesMut::extend_from_slice` taking this time.
The reason here is that extending the buffer require a reallocation of
the buffer and a copy of the complete data. This can be a big size
(up the maximum internal buffer size) - even if only a tiny chunk of
data is added.
This change improves on this by using a non-contiguous send buffer.
New data is appended as a new `Bytes` segment, which only requires
an allocation for this particular size. The 10ms …
=> Non contiguous Send buffer

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/pacing.rs, quinn-proto/src/connection/paths.rs
The pacing implementation did so far not do anything. The reason for
that is the timestamp when tokens had been last generated was never
updated. Therefore each Pacer::delay call where not enough tokens
had been available calculated tokens based on the time back to when
the Pacer was initially created, which fully refills the capacity.
This is easily fixed by storing the timestamp when tokens are replenished.
However only changing this without changing the pacers capacity would
be extremely inefficient. Each `Pacer::delay` call would only allow a single
datagram to be sent, and then instruct the connection to wait a tiny
time-slice (which is far smaller than the timer granularity). when the timer
really elapses (e.g. a tokio timer after 1ms) only 1 packet can be sent
again.
This change …
=> Fix pacing

quinn-proto/src/connection/mod.rs, quinn/src/streams.rs
Add a has_pending_retransmits method to
quinn_proto::connection::Connection and use it inside of
quinn::RecvStream::poll_read_generic to decide if we should wake up the
connection driver.
=> Wake up the connection driver only if flow control needs to be issued (based on #991)

quinn/Cargo.toml, quinn/src/platform/unix.rs
Fixes #968 for the upcoming release.
=> Sound addr

docs/book/src/SUMMARY.md, docs/book/src/quinn/set-up-connection.md
This PR is part of a series of PR's regarding the book creation as described in #865. Each page of this chapter will have its own PR for reducing PR size.
- Network Introduction (#917)
- QUINN Introduction (#868)
- Certificate Configuration (#920)
**- Connection Setup (#921)**
- Data Transfer (#922)
A live version of this page can be found [here](https://timonpost.github.io/quinn/). This book shows all the work that I have up-to-now. The pages that are visible but don't have a PR yet should are welcome to have general feedback.
This chapter will go through the protocol by examples. The chapters are in the required order, first, we look at configuring a certificate which is **required**, then at setting up a connection, and finally at sending data about this connection. In the future, more …
=> (2) Quinn Introduction Chapter, Connection Setup Page

quinn-h3/src/proto/frame.rs
Fixes #994.
As suggested by @djc here: https://github.com/quinn-rs/quinn/pull/995#issuecomment-769044498
=> quinn-h3: partially revert limiting decoded data

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams.rs, quinn-proto/src/connection/streams/send.rs, quinn/src/streams.rs
I tried to implement stream prioritization in a way that should not have an huge impact for users who do not need this feature.
Instead of a single queue, it uses a vector of (priority, queue) pairs, sorted by descending priority, so that we can iterate over it in `write_stream_frames`. Pushing a new pending stream will take O(log n) time to find the correct queue, where n is the number of already used priority levels.  
Current drawback: The vector of (priority, queue) pairs is never shrunk, which is a problem if a lot of different priority levels are used. Therefore it might make sense to change the priority type to `i8` to limit the maximum size of the vector to 256.
=> Implement stream prioritization (fix #165)

quinn-proto/src/connection/send_buffer.rs, quinn-proto/src/connection/streams.rs, quinn-proto/src/lib.rs
This change will increase the amount of data that will be written in
STREAM frames. The previous approach was pessimistic and assumed
- 8 bytes are used for Stream ID
- 8 bytes are used for the offset
- 8 bytes are used for the length
This change calculates the available size better on the amount of actual
bytes required to encode the stream ID and length. It also allows to
omit the length field if enough information is available to fully utilize the
datagram.
This allows to store up to 22 byte more payload data per MTU.
=> Increase datagram utilization

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/stats.rs
This adds a new metric for the amount of either loss or ECN
related congestion events.
=> Add stats for congestion events

bench/Cargo.toml, bench/src/bulk.rs
This extends the benchmark to make the consumer either utilize the
ordered or unordered read API.
The ordered read API is now set to the default, since it might be
applicable to more applications.
=> Allow to use the vectored ordered read API in benchmark

quinn/Cargo.toml, quinn/src/connection.rs, quinn/src/lib.rs, quinn/src/mutex.rs, quinn/src/streams.rs
This change adds an optional feature which allows to track how much
time was spent inside locks on connections, as well as which other
tasks held the lock (in case there is lock contention).
This makes it easier to determine which code path are currently not
as non-blocking as they should be.
Examples of output:
```
Feb 04 22:05:42.293  WARN quinn::mutex: Utilizing the connection for poll took 165.2318ms
```
```
Feb 04 22:05:42.128  WARN quinn::mutex: Locking the connection for poll took 1.1284ms. Last owners: [("SendStream::poll_write", 7.6µs), ("SendStream::poll_write", 46.4µs), ("SendStream::poll_write", 792.8µs), ("drop", 100ns), ("clone", 100ns), ("OpenUni::next", 1.3µs), ("clone", 295.2µs), ("poll", 14.1546ms), ("drop", 100ns), ("drop", 100ns), ("drop", 439.2µs), ("poll", 9.7657ms), …
```
=> Lock tracking

quinn-proto/Cargo.toml, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/connection/streams.rs, quinn-proto/src/frame.rs
When packets are transmitted, the most common case them is to contain at
most a single STREAM frame. For this common case the current system does
still 2 allocations: One for the `SentPacket` structure which tracks the whole
packet, and one for the stream metadata. This double allocation places
some additional pressure on the allocator. This change changes
`SentPacket::stream_frames`  to make use of vector with small element
optimization, in order to be able to handle the common case of sending
1 stream frame without any further allocation.
Benchmark results
===
Overall the differences don't seem huge. However they become bigger when other
optimizations (like bigger MTUs and size reduction for `SentPacket` are also
enabled).
Without GSO
--
**Before:**
> Sent 4294967296 bytes on 1 streams …
=> Use inline storage for the common case of 1 STREAM frame per packet

bench/Cargo.toml
This causes nom to be pulled in, which currently causes the CI error and build
conflict between `funty` and `bitvec`: https://github.com/myrrlyn/funty/issues/3
We don't need the feature in this scenario anyway.
=> Disable hdrhistogram features

quinn-proto/src/connection/assembler.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams.rs, quinn-proto/src/connection/streams/recv.rs
=> Add and use over-allocation metric to decide when to defragment

quinn-proto/Cargo.toml, quinn-proto/src/crypto/rustls.rs
Testing showed that there is a huge performance boost using AES ciphers
due to hardware acceleration. Therefore those should be preferred.
As an example, a benchmark run using CHACHA20 reached a throughput
of 350MB/s, whereas the same configuration using AES128 reached 520MB/s.
While CHACHA20 might have higher performance on devices without
hardware acceleration for AES, this set of devices might now be tiny.
=> Prefer AES cipher suites

bench/src/bulk.rs
rustls defaults to CHACHA20, which is rather slow on desktop hardware.
This change allows to specify a single cipher suite for this test, and
sets the default to AES128.
CHACHA20 (default):
> Sent 4294967296 bytes on 1 streams in 14.86s (275.68 MiB/s)
AES128:
> Sent 4294967296 bytes on 1 streams in 12.21s (335.59 MiB/s)
=> Allow to specify the cipher suite in bulk test

quinn-proto/src/config.rs
for a moment I thought there might be a window pin.
=> Fixed typo allow_wpin -> allow_spin

quinn-proto/src/bytes_source.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/send_buffer.rs, quinn-proto/src/connection/streams.rs, quinn-proto/src/connection/streams/send.rs, quinn-proto/src/lib.rs
Add a `Bytes` array based send interface to `quinn-proto`
This change modifies quinn-proto to allow callers to submit a list
of one or more owned `Bytes` chunks for transmission instead of
pure byte slices. This will provide a more efficient zero-copy
interface for applications which already make use of owned
`Bytes` buffers.
The internals of quinn-proto have been refactored in order to keep
the ability to pass `&[u8]` buffers and defer the conversion into
`Bytes` as long as possible, in order to avoid unnecessary allocations
if no data can be stored due to flow control.
=> Add a `Bytes` array based send interface to quinn-proto

quinn-proto/src/connection/send_buffer.rs
When a frame contained data for an offset of 0, the transmit logic did not
fully fill a packet. The reason for this is that the logic reserved 1 byte for
writing an offset. However storing offset 0 doesn't require 1 byte,
because it will be encoded with a special flag in the message header.
Without GSO, this isn't a huge issue. It mostly means we are wasting
1 byte per datagram.
However with GSO, this actually leads to data corruption:
When using GSO, and  packet isn't fully filled, it later gets padded
to MTU size. Padding a packet ending with a STREAM frame that
doesn't contain a length information is however invalid, and will let
the receiver assume the padding is part of part of the data. This means
the receiver will receive an extra `0` at the end of a stream - and
depending on the …
=> Account for offset=0 requiring no space

bench/src/bulk.rs, quinn/src/send_stream.rs
This extends the public quinn API to offer support for writing owned buffers.
Besides the universal `write_chunks` API which supports a variable amount
of buffers the API also offers convenience methods for writing either a
single buffer completely or an arbitrary amount of buffers completely.
=> Make owned bytes write APIs available in quinn

perf/Cargo.toml, perf/src/client.rs, perf/src/server.rs
This change aggregates a couple of improvements for the perf client and server.
Some changes make the client and server more efficient.
Two other commits add stats to the client.
Output is now created in 2s intervals and looks like:
```
Overall stats:
RPS: 0 (2 requests in 14.01s)
Success rate: 100.00%
Stream metrics:
│ Duration  │ FBL       | Upload Throughput | Download Throughput
──────┼───────────┼───────────┼───────────────────┼────────────────────
AVG  │     4.96s │    0.00ns │      404.00 MiB/s │        402.62 MiB/s
P0   │     4.94s │    0.00ns │      400.50 MiB/s │        397.00 MiB/s
P10  │     4.95s │    0.00ns │      400.75 MiB/s │        397.25 MiB/s
P50  │     4.95s │    0.00ns │      400.75 MiB/s │        397.25 MiB/s
P90  │     4.97s │    1.00ms │      407.50 MiB/s │ …
```
=> Perf client and server improvements

perf/src/client.rs, perf/src/server.rs
Use zero-copy APIs when sending data in perf application.
Performance difference:
1. First line is before
2. Second line is after (but with only the download write change)
```
│ Duration  │ FBL       | Upload Throughput | Download Throughput
──────┼───────────┼───────────┼───────────────────┼────────────────────
AVG  │    5.00ms │    1.00ms │      332.82 MiB/s │        334.20 MiB/s
AVG  │    5.00ms │    0.00ns │      332.64 MiB/s │        335.96 MiB/s
```
=> Makes less than 1%. Still neat to have
=> Perf: Use owned buffers

quinn-proto/src/connection/mod.rs
This changes makes sure we don't lose close frames when the first send attempt
is blocked by congestion control.
=> retry transmitting close frames

quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/connection/streams/state.rs
This contains 2 changes which will report a Stream only as writeable if both the connection as well as stream windows are not empty.
=> Reduce stream wakeups

quinn/src/platform/unix.rs
These will cause spurious panics once https://github.com/rust-lang/rust/pull/78802 is merged.
CC @est31: this will need to be added to the backport PRs.
=> Remove obsolete safety asserts

quinn-proto/src/connection/mod.rs
Quoth the spec: a server MUST expand the payload of all UDP datagrams
carrying ack-eliciting Initial packets to at least the smallest
allowed maximum datagram size of 1200 bytes.
Found in @Matthias247's recent interop testing
=> Pad initial-space datagrams from servers, too

quinn/Cargo.toml, quinn/src/platform/unix.rs
0.6.x backport of #987 . Only the second commit is needed, see https://github.com/quinn-rs/quinn/issues/968#issuecomment-789294218
=> [0.6.x] Don't assume representation of SocketAddr

quinn/Cargo.toml, quinn/src/platform/unix.rs
0.5.x backport of #987 . Only the second commit is needed, see https://github.com/quinn-rs/quinn/issues/968#issuecomment-789294218
=> [0.5.x] Don't assume representation of SocketAddr

perf/Cargo.toml, perf/src/client.rs, perf/src/server.rs, perf/src/socket.rs
- Allows to overwrite socket buffer sizes
- Change server logging to use `debug` instead of `trace` logs
=> perf test improvements

quinn-proto/src/connection/mod.rs, quinn-proto/src/tests/util.rs, quinn/src/connection.rs, quinn/src/platform/fallback.rs, quinn/src/platform/mod.rs, quinn/src/platform/unix.rs
This set of changes will automatically activate GSO on Linux. In order to do this, the platform is queried for the maximum amount of supported segments per transmit call. This amount is capped at a certain level, and then passed to the `poll_transmit` call.
=> Automatically activate GSO based on platform capabilities

quinn-proto/Cargo.toml, quinn-proto/src/connection/cid_state.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/connection/streams/state.rs, quinn-proto/src/endpoint.rs, quinn/Cargo.toml, quinn/src/connection.rs, quinn/src/endpoint.rs
Rusts default HashMap and HashSet use siphash as a hash method to protect again malicious input. The downside of siphash is that it is slightly more expensive than a more primitive mechanism. The siphash operations currently show up in quinn flamegraphs - even if they only act on 8byte input data like Stream IDs.
The security properties of siphash are not really required in the context of quic, where the hashmaps are used with 2 key types:
- Stream IDs: The valid range for those is predetermined by the maximum concurrent stream setting. The peer can't pick from a bigger range in order to get more hashes into the same bucket. Besides this, the risk of resource exhaustion via purely creating more requests/streams is already much higher than exhaustion of the pure maps.
- Connection IDs: …
=> Use a cheaper hash function

quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/connection/streams/state.rs
Fixes https://github.com/quinn-rs/quinn/issues/1061. This will deadlock connections after the maximum concurrent number of streams is reached, so we should probably backport to 0.7.
=> Fix stream leak on stop after finish

docs/book/src/SUMMARY.md
This one is already mentioned under 'QUIC introduction'.
=> Remove link to QUIC protocol page

perf/src/bin/perf_client.rs
For large requests and high latency connections the number
showed 0 most of the time which isn't too helpful.
=> Print perf_client RPS in floating point format

quinn/src/builders.rs
Creating a `ClientConfig` can on some platforms take an excessive amount
of time, likely due to rustls scanning the systems cert store.
This slows down all functions which make use of `quinn::Endpoint::builder()`,
even if the client config is known upfront and shared between mutliple connections.
In some tests I noticed an extra connection establishment time of 1s for
creating a client.
This changes will create the `ClientConfig` only if the Endpoint is built
when the `ClientConfig` hasn't been set by the application.
Server side code still suffers from the issue, since `ClientConfig`s there are not
known. However it might be less impacting, since a second of startup time for
a server matters less than for a client.
=> Create `ClientConfig` lazily in EndpointBuilder 

quinn-proto/src/range_set.rs
(cherry picked from commit ab61ef89f534e0c9ce82379c0b954591e5f2d99a)
=> Backport "Replace deprecated collections::Bound with ops::Bound" to 0.7

quinn/Cargo.toml, quinn/src/builders.rs, quinn/src/endpoint.rs
Pure servers never need this. once_cell is already a transitive dep, and is expected to eventually land in std, so it's free to add.
Fixes #1079.
I realized after writing this that a perhaps more natural fix for pure servers wasting time on certificate loading is to disable the `native-certs` feature, so I'm not sure this is needed. Still, this is a small change, so worth considering. Thoughts?
=> Lazily initialize Endpoint::default_client_config

quinn-proto/src/connection/mod.rs
Fix overflowing when doing things like `TransportConfig::crypto_buffer_size(usize::MAX)`.
=> Fix overflow in `crypto_buffer_size`

quinn-proto/src/connection/spaces.rs, quinn-proto/src/connection/streams/recv.rs, quinn-proto/src/connection/streams/state.rs, quinn-proto/src/tests/mod.rs
This should turn into a point release, since the current behavior will cause long-lived connections to become stuck on connection-level flow control.
=> Chunks fixes

quinn/src/tests.rs
This set of changes maxes the end to end tests in the `quinn` crate a bit more exhaustive, by transferring bigger data streams, checking for data corruption, and using low flow control windows to determine whether flow control updates work properly.
This set of changes catches the connection flow control bug which is addressed in #1087 . I added a set of distinct tests that aim to stress test one particular aspect of the system.
=> End to end test improvements

quinn-proto/src/connection/mod.rs, quinn-proto/src/crypto.rs, quinn-proto/src/crypto/rustls.rs
A crypto session cannot return 1-RTT keys before handshaking is finished.
Currently, rustls contains unwrap() calls to deal with this, but hoisting
out the unwrap to the `Connection` level here seems more sensible.
We can adjust the call into rustls once we update rustls for other reasons.
=> crypto: return Option from next_1rtt_keys()

quinn-proto/src/connection/mod.rs
Ensures that 1-RTT stream events are delivered after `Event::Connected`, without interfering with the placement of connection errors at the end of the event stream.
Fixes #1094. Moots #1096.
=> Improve connection event ordering consistency

.github/workflows/rust.yml, README.md, interop/src/main.rs, interop/src/qif.rs, interop/src/server.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/connection/streams/recv.rs, quinn-proto/src/connection/streams/state.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs
Backports changes from https://github.com/quinn-rs/quinn/pull/1087. We could maybe strip this down to just 
a095410a50e5182aa76e8d8c8acacb5baf1b30b4, but the refactoring makes me more confident in correctness and the more minor fixes along the way shouldn't hurt, and if we have to touch this again it'll be easier without divergence.
I'll prepare a point release once this is merged.
=> Backport flow control fixes

.github/workflows/rust.yml, README.md, quinn-proto/src/cid_queue.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/frame.rs, quinn-proto/src/range_set.rs, quinn-proto/src/range_set/array_range_set.rs, quinn-proto/src/range_set/btree_range_set.rs, quinn-proto/src/range_set/mod.rs, quinn-proto/src/range_set/tests.rs
This change introduces a second `RangeSet` type which is based on a
linear array/vector instead of a tree. For the purpose of tracking
ACK ranges we usually should not have a big number of disjoint ranges,
since those would only occur with severe fragmentation. Therefore the
main benefit of a tree which is able to find ranges in the middle is
rarely used.
The array-based RangeSet provides 2 benefits:
- There exists an inline representation, which avoids the need of heap
allocating ACK ranges for `SentFrames` for small ranges.
- Iterating over ranges should usually be faster since there is only
a single cache-friendly contiguous range.
Performance differences:
With the `BTreeMap` based `RangeSet`:
```
Sent 1073741824 bytes on 1 streams in 1.90s (538.89 MiB/s)
```
With the `TinyVec` based …
=> Use an array-based RangeSet for tracking outgoing ACKs

quinn-proto/src/connection/mod.rs
Backports #1104 to 0.7.x branch.
=> Allow returning keys before the next frame.

fuzz/fuzz_targets/packet.rs, quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/packet.rs, quinn-proto/src/tests/mod.rs
Allows configuring the supported versions in `EndpointConfig`.
Closes #719
=> Allow overriding supported versions in EndpointConfig.

quinn-proto/src/connection/mod.rs
This change increases the amount of `CRYPTO` data sent in packets during handshakes.
Instead of reserving a fixed amount of 17 bytes for frame overhead,
we reserve the exactly required amount of bytes to encode frame type
and offset, and only 2 bytes for the frame length. This leads to an
additional 12-13 bytes of payload data being used.
=> Maximize `CRYPTO` data

quinn-proto/src/frame.rs
This adds a manual `Debug` implementation for Ack frames, to make them understandable
in logs.
Old:
```
got frame Ack(Ack { largest: 11, delay: 0, additional: b"\x02", ecn: None })
```
New:
```
got frame Ack(Ack { largest: 9, delay: 0, ecn: None, ranges: "[8..=9]" }
```
=> Ack frame `Debug` implementation

quinn-proto/src/packet.rs, quinn-proto/src/shared.rs, quinn-proto/src/transport_parameters.rs
When reading CIDs from packets the current code makes some short-lived
allocations due to the use of `copy_to_bytes`, which allocate for 1.5% of
CPU samples. This change avoids this.
**Before:**
```
Sent 1073741824 bytes on 1 streams in 1.72s (594.74 MiB/s)
```
**After:**
```
Sent 1073741824 bytes on 1 streams in 1.70s (602.78 MiB/s)
```
=> Avoid allocations for CIDs

quinn/src/endpoint.rs, quinn/src/lib.rs
This contains 2 commits which in combination try to prevent the endpoint task from using too many executor resources while keeping performance or event improving on it.
Performance difference various a bit between the machinesI tested. On one there is no change, on another an increase in througput:
**Before:**
```
Sent 10737418240 bytes on 1 streams in 22.50s (455.04 MiB/s)
```
**After:**
```
Sent 10737418240 bytes on 1 streams in 21.92s (467.06 MiB/s)
```
=> Improve fairness of endpoint task

quinn/src/connection.rs, quinn/src/endpoint.rs
This introduces two further limits which place bounds on task iterations.
This significantly reduces RTT for a loopback connection since the connection
is no longer busy producing packets and not doing any reception work.
Raw throughput can be a bit slower since a lot more ACK packets are now
processed in the loopback test. However RTT is halfed. The difference
in ACK packets (7200 vs 83000) and RTT (800us vs 400us) is very
visible in the benchmark:
**Before:**
```
Overall stats:
Sent 1073741824 bytes on 1 streams in 1.70s (603.88 MiB/s)
Server connection stats:
ConnectionStats {
frame_tx: FrameStats {
ACK: 7199,
},
frame_rx: FrameStats {
ACK: 903129,
},
path: PathStats {
rtt: 459.755µs,
cwnd: 12320,
},
}
Client connection stats:
ConnectionStats {
frame_tx: FrameStats {
ACK: 903129,
}, …
```
=> Improve fairness between tasks further

perf/src/bin/perf_client.rs, perf/src/bin/perf_server.rs
This adds the `--conn-stats` flag to both CLI tools, which will print
the connection statistics together with other data every 2s.
=> Print connection statistics in perf client and server

quinn-h3/examples/h3_server.rs
Hi, thank you very much for the wonderful project! I corrected a simple typo.
=> concurently → concurrently

quinn/Cargo.toml
=> quinn: only depend on rt-multi-thread as a dev-dependency

quinn-h3/src/client.rs, quinn-h3/src/connection.rs, quinn-h3/src/data.rs, quinn-h3/src/server.rs, quinn-h3/src/streams.rs, quinn/src/connection.rs, quinn/src/recv_stream.rs, quinn/src/send_stream.rs
The warning message is taken verbatim from the futures crate.
=> Add must_use warnings for all Future types

quinn-h3/Cargo.toml
This got lost when #1137 was merged and breaks the build
=> Add rt-multi-thread tokio feature to quinn-h3

quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/connection/streams/send.rs, quinn-proto/src/connection/streams/state.rs
This avoids duplicate emission of various events
=> Handle STOP_SENDING only once

quinn-proto/src/connection/mod.rs, quinn-proto/src/tests/mod.rs
When path migration happened, the data received was accounted for
the old path, and provided the server less anti-amplification budget
to respond to the client.
By accessing path only after the first packet had been processed and
migration was initiated we make sure the new path gets the budget.
=> Account received data for the most recent path

quinn-proto/src/connection/mod.rs
This case is handled by the usual path validation timeout, and by the ACK elicited from the peer by a PATH_CHALLENGE on a legitimate path.
Context:
[§9.3.2](https://datatracker.ietf.org/doc/html/rfc9000#section-9.3.2):
> To protect the connection from failing due to such a spurious
migration, an endpoint MUST revert to using the last validated peer
address when validation of a new peer address fails.
[§9.3.3](https://datatracker.ietf.org/doc/html/rfc9000#section-9.3.3):
> In response to an apparent migration, endpoints MUST validate the
previously active path using a PATH_CHALLENGE frame.  This induces
the sending of new packets on that path.
[§1.2](https://datatracker.ietf.org/doc/html/rfc9000#section-1.2):
> Ack-eliciting packet:  A QUIC packet that contains frames other than
ACK, …
=> Remove incorrect spurious migration handling

quinn-h3/src/tests/mod.rs
The response body in those tests was never read. Therefore it was possible
for the test to drop the connection before the stream was actually read to
completion.
=> Fix some h3 test races

quinn/src/endpoint.rs, quinn/src/lib.rs, quinn/src/work_limiter.rs
While the hardcoded numbers might work good on some machines, they can be problematic on others.
They also make it harder to distinguish on how much time is spent on send vs receive.
This introduces a dynamic `WorkLimiter` which measures the elapsed time per operation, and allows to configure how much time we intend to spend on send vs receive.
This change integrates it so far for `recv` which is at the moment more problematic, but it can easily be extended for the send path.
Performance differences are negligible on this machine (probably because
`IO_LOOP_BOUND` was set to a number which works for it), but it can improve
things on less known environments.
I instrumented the endpoints receive method to see how much time it spends
on average in `drive_recv`.
**Baseline:**
```
Recv time: …
```
=> Dynamically determine the amount of work that can be performed in an endpoint iteration

quinn-h3/src/qpack/dynamic.rs, quinn-h3/src/qpack/prefix_string/encode.rs, quinn-h3/src/qpack/vas.rs, quinn/src/connection.rs, quinn/src/tests.rs
Fixes two instances of
> warning: all if blocks contain the same code at the start
=> Fix Rust 1.53 clippy issues

quinn-proto/src/connection/datagrams.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/pacing.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/connection/paths.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs
As mentioned in #1154, it seems quinn sends UDP datagrams with a payload 1232 bytes by default.
This is easily reproducible with the client.rs/server.rs quinn example, making a GET request and serve a reasonable big file.
```
cargo run --example client https:/server:1234/README.md
```
```
[...]
Jul 06 02:59:45.746 TRACE drive{id=0}: quinn_proto::connection: sending 1232 bytes in 1 datagrams
[...]
```
---
Looking at the QUIC spec, ([quic-draft-32 #14](https://datatracker.ietf.org/doc/html/draft-ietf-quic-transport-34#section-14)) , it seems the protocol should supports networks where the maximum UDP payload is 1200 bytes.
Any larger value should be discovered using PMTUD.
This PR contains two changes:
* Renaming the [`const MIN_MTU: u16 = …
=> Bounding UDP payload size to 1200 and renaming

quinn/src/endpoint.rs, quinn/src/platform/unix.rs
When packets failed to transmit - e.g. due to being blocked by iptables - the
quinn endpoint kept them around and tried to retransmit them later on. This
usually failed for the same reason, which resulted in an infinitely growing list
of packets to transmit.
To prevent this, this change drops all packets where sending fails for a
a non-fatal reason.
=> Drop outgoing packets on permission errors

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/paths.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn-proto/src/transport_parameters.rs
This change contains a first set of improvements to ACK handling, on the way to sending ACKs more efficiently.
In these changes the number of ACKs is actually not yet reduced, and the previous strategies are kept.
It however introduces some refactorings and prerequesites for adding ACK delay successfully:
1. The ACK state is moved into a separate struct
2. ACK delay is reported to peers, in order not to disturb RTT calculations in case ACK delay is applied
3. Pending ACKs are sent with `CONNECTION_CLOSE` frames
=> Ack improvements

quinn/src/recv_stream.rs
=> Don't falsely report end-of-stream when reading into an empty slice

quinn-proto/src/config.rs
@Matthias247 reports dramatic throughput increases over realistic WAN paths.
=> Default to Cubic congestion control rather than NewReno

quinn-proto/src/config.rs, quinn-proto/src/endpoint.rs
This is less error-prone and consistent with other configuration values.
=> Encode token lifetime configuration as a Duration

quinn/src/platform/fallback.rs, quinn/src/platform/mod.rs, quinn/src/platform/unix.rs
Some more transient transmit errors have been observed. E.g. for some
peers transmission failed with
```
error: Os { code: 101, kind: Other, message: "Network is unreachable" }
```
That lead the endpoint to shut down and not process any messages for any
other clients.
To prevent this, this changes the behavior to ignore errors inside the endpoint.
In order to not lose all visibility, the change however adds low frequency
logging for the errors.
=> Log and ignore transmit errors

quinn-proto/src/congestion/cubic.rs
`config.minimum_window` is already in bytes - it doesn't have to be multiplied by them..
=> Fix cubic minimum congestion window handling

perf/Cargo.toml, perf/src/bin/perf_client.rs, perf/src/lib.rs, perf/src/stats.rs
This change adds a `--json` option to the  perf_client, allowing for throughput statistics to be output in a style partially matching that of iperf3. An `--interval` option is also added, to allow specifying the interval (in seconds) at which the statistics are gathered. This will allow the data gathered by the perf client to be used in a variety of ways, including through tools built for iperf3, such as https://github.com/rkost/iperf3Vis.
Example output (truncated):
```
{
"start": {
"timestamp": {
"timesecs": 1627418034
}
},
"intervals": [
{
"streams": [
{
"id": 0,
"start": 0.010186108,
"end": 1.010887858,
"seconds": 1.00070175,
"bytes": 10000000,
"bits_per_second": 79943899.36861807,
"sender": false
},
{
"id": 4,
"start": 0.010186108,
"end": 1.010887858,
"seconds": 1.00070175,
"bytes": …
```
=> Output json throughput statistics from perf client

quinn-proto/src/endpoint.rs
There has been no implicit conversion to this variant since the switch
to `thiserror` (1bca0f7c), since `#[source]` does not imply `#[from]`.
There has never been any explicit construction of this variant, so it
likely became unused some time before during various configuration
refactors.
BREAKING CHANGE: The `ConnectError::Config` variant is removed.
=> Remove unused `ConnectError::Config` variant

quinn/Cargo.toml
Prevents quinn-proto's default features from infecting anything that depends directly on quinn but doesn't necessary want them.
=> Disable default features in proto dependency

quinn/Cargo.toml
There's a test in the quinn crate that uses `futures_util::join!` which is behind a feature gate the quinn itself doesn't enable.  (Other crates in the workspace do enable that feature, so it only errors if you run cargo test from within quinn before running it for the workspace).
This adds a line to dev-dependancies which enables that feature when testing quinn.
=> Fix inner crate test

bench/src/bulk.rs, interop/src/main.rs, interop/src/server.rs, quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/transport_parameters.rs, quinn/benches/bench.rs, quinn/examples/common/mod.rs, quinn/examples/server.rs, quinn/src/lib.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
Based on the discussion in #1176, I've updated the relevant `TransportConfig` setters to take `VarInt`, so they become infallible. In most cases, this is just a case of applying `.into()`/`.try_into()` to the argument (particularly with the addition of `TryFrom<Duration> for VarInt`).
In that issue one thing suggested was using `impl Into<VarInt>`, in the end I left that out since it doesn't do much for literal arguments, which still need to be ascribed with a relevant type (e.g. `1u8`).
---
- 0f840f01 **Use `VarInt` in `TransportConfig`'s `VarInt` field setters**
Rather than taking a `u64` and returning a `ConfigError::OutOfBounds`,
these methods are now infallible by taking a `VarInt` directly.
In many cases, call-sites can be updated simply by adding a `.into()` or
`.try_into()` to the …
=> Infallible `TransportConfig` setters

quinn-proto/src/endpoint.rs, quinn/src/endpoint.rs
The idea here is to reload the server configuration allowing a new setup for incoming connections without dropping the endpoint and closing existing ones.
The main rationale is the fact that, in some circumstances, on long server sessions, it is needed to reload its TLS configuration. In particular, to have the possibility to renew an expiring TLS certificate keeping the server/service operative.
---
<details>
<summary>Pseudo Code Usage Idea</summary>
```
let (endpoint, mut incoming) = endpoint.bind(&listen_addr).unwrap();
loop {
select! {
Some(incoming) = incoming.next() => {
// Handle new incoming connection
}
new_config = config_reload.next() => {
let new_server_config = build_new_server_config(&config);
endpoint.override_server_config(new_server_config);
}
}
}
```  
</details>
=> Endpoint - allowing override server configuration

quinn/src/endpoint.rs, quinn/src/lib.rs, quinn/src/work_limiter.rs
This adds time-based yielding to the send loop in the same fashion it
had been previously added ot the receive loop.
In my performance testing this didn't show a noticeable difference - likely
because in the current benchmark the client is the bottleneck. But it should
make things more deterministic.
=> Use WorkLimiter also for sending data

bench/src/lib.rs, interop/src/server.rs, perf/src/bin/perf_client.rs, perf/src/bin/perf_server.rs, quinn-proto/Cargo.toml, quinn-proto/src/config.rs, quinn-proto/src/crypto.rs, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/Cargo.toml, quinn/benches/bench.rs, quinn/examples/client.rs, quinn/examples/common/mod.rs, quinn/examples/insecure_connection.rs, quinn/examples/server.rs, quinn/src/builders.rs, quinn/src/endpoint.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
Extracts the parts of #1150 that don't rely on rustls 0.20 (now released) and the rustls-native-certs update (not yet done). Arguably should have done this sooner to avoid the rebase, but let's get it done now?
=> Explicit TLS configuration setup

.github/dependabot.yml, .github/workflows/rust.yml, .gitignore, fuzz/Cargo.toml, quinn-proto/Cargo.toml, quinn-proto/src/lib.rs, quinn-proto/src/varint.rs, quinn/Cargo.toml, quinn/tests/many_connections.rs
Needs const generics, so this also updates the MSRV (which needs a bump for the rustls update, anyway).
=> Upgrade to arbitrary 1 and crc 2

quinn/Cargo.toml, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/lib.rs, quinn/src/tests.rs
Otherwise, a client that is only receiving will lose its connection on rebind.
=> Send ping on rebind to ensure peers notice migration

quinn-proto/src/congestion.rs, quinn-proto/src/congestion/bbr/bw_estimation.rs, quinn-proto/src/congestion/bbr/min_max.rs, quinn-proto/src/congestion/bbr/mod.rs, quinn-proto/src/congestion/cubic.rs, quinn-proto/src/congestion/new_reno.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/paths.rs, quinn-proto/src/tests/mod.rs, quinn/src/connection.rs, quinn/src/lib.rs
implements BBR congestion control based on google's quiche. There are some differences in implementation due to chromium's CCA having a different API, especially around sending vs acking packets.
It's a pretty rough first implementation but from my testing it seems to work well. It is very resistant to packet loss especially in high BDP situations.
Please critique and suggest changes as needed.
I've added additional fields and traits for debugging using stats which can be removed if needed.
Closes #693
=> feat(cca): BBR

quinn/src/tests.rs
These were causing coverage to time out.
=> Skip slow tests under tarpaulin

quinn-proto/src/connection/datagrams.rs, quinn-proto/src/tests/mod.rs
This is, unfortunately, the specified behavior.
=> Apply datagram frame size to entire frame, not just payload

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/connection/paths.rs
Minor correctness tweaks that should allow faster recovery and reduce spurious persistent congestion determinations.
=> Persistent congestion fixes

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/connection/streams/state.rs, quinn/Cargo.toml
Fixes https://github.com/quinn-rs/quinn/issues/1196. Probably.
These fixes add extra work and don't address the complexity that led to the bug in the first place. https://github.com/quinn-rs/quinn/issues/1226 discusses possible future work to make this logic more fundamentally robust.
=> Fix cases of spurious transmit readiness

quinn-proto/src/config.rs, quinn-proto/src/endpoint.rs
This better reflects the final RFC terminology. See https://www.rfc-editor.org/rfc/rfc9000.html#name-retry-packet.
=> Rename "stateless retry" to "retry"

bench/src/lib.rs, perf/src/bin/perf_client.rs, quinn-proto/src/config.rs, quinn-proto/src/crypto.rs, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/packet.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/examples/client.rs, quinn/examples/insecure_connection.rs, quinn/src/tests.rs
Inspired by conversation with @Dessix. Allows the upcoming Quinn release to remain backwards-compatible with 0.7.x.
=> Backwards-compatibility with late draft versions

quinn/src/lib.rs
The link to `Endpoint` in [the documentation for the new release](https://docs.rs/quinn/0.8.0/quinn/) (in the sentence "The entry point of this crate is the `Endpoint`." at the top of the page) points into the no longer existent "generic" directory. This fixes that link.
=> Adjust link to quinn crate entry point in docs

quinn-proto/src/congestion.rs, quinn-proto/src/congestion/bbr/mod.rs, quinn-proto/src/congestion/cubic.rs, quinn-proto/src/congestion/new_reno.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/paths.rs, quinn-proto/src/lib.rs
Attempt to fix this: #1242 
---
*Feedback on documentation are more than welcome* :smile:
=> Make pub visibility for RttEstimator used by pub trait quinn::Congestion

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/frame.rs
Saves a great deal of redundancy when transmitting bulk data, and gives the receiver less work to do. If an ACK is lost, we'll necessarily retransmit it, because packets are only deemed lost when an ACK is received from the peer which does not cover them.
Reduces the number of ACKs sent by the server in the bulk download benchmark from e.g. 930818 to 4228.
=> Only send ACKs when they've changed

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/connection/stats.rs
These are a bit more explicit than just tracking congestion events, since a
congestion event can cover multiple packets.
The total amount of sent packets is now also logged, in order for applications
to calculate the relative amount of packet loss. The amount of packets can
be different from the amount of datagrams in case of coalesced packets.
=> Add additional metrics for lost packets and bytes

quinn/examples/insecure_connection.rs
Introduced by a copy-paste error in 9daaa15da231f56559d771cf8d674ccdbe98890e
=> Fix ALPN misconfiguration in example

perf/src/bin/perf_client.rs, perf/src/bin/perf_server.rs, quinn/Cargo.toml, quinn/benches/bench.rs, quinn/examples/connection.rs, quinn/examples/insecure_connection.rs, quinn/examples/server.rs, quinn/examples/single_socket.rs, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/lib.rs, quinn/src/recv_stream.rs, quinn/src/send_stream.rs
A trivial amount of additional code lets us save another dep and be a bit more accessible to new users (see e.g. #1262).
=> Replace futures-util with optional futures-io dep

quinn/src/lib.rs, quinn/src/recv_stream.rs, quinn/src/send_stream.rs
`SendStream` futures weren't reexported, making them rather obscure, and using `async fn` in general makes for clearer docs (because the yielded type is displayed directly and there are fewer structs cluttering the index) and places fewer constraints on implementation.
=> Standardize on async fn for I/O methods

bench/Cargo.toml, bench/src/bin/bulk.rs, perf/Cargo.toml, quinn-udp/Cargo.toml, quinn-udp/src/fallback.rs, quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn/Cargo.toml, quinn/examples/server.rs, quinn/examples/single_socket.rs, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/send_stream.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
This drops 6 packages from the workspace-scoped Cargo.lock, and should save a decent amount of buildtime, both locally and downstream.
=> Strip down futures-* dependencies

docs/book/src/quinn/certificate.md, docs/book/src/quinn/data-transfer.md, docs/book/src/quinn/set-up-connection.md
Hi!
This PR updates the book.
- adjust links that point into the no longer existent "generic" directory
- `quinn::ClientConfigBuilder`, `ServerConfigBuilder` and `EndpointBuilder` have already been removed (#1213), so adjust
- `quinn::Certificate` have already been removed (#1214), so adjust
I referred to [quinn/examples/insecure_connection.rs](https://github.com/quinn-rs/quinn/blob/0.8.0/quinn/examples/insecure_connection.rs), [quinn/examples/client.rs](https://github.com/quinn-rs/quinn/blob/0.8.0/quinn/examples/client.rs) and [quinn/examples/server.rs](https://github.com/quinn-rs/quinn/blob/0.8.0/quinn/examples/server.rs) to adjust the book.
=> Adjust the book with version 0.8.0

docs/book/src/quinn/set-up-connection.md
`endpoint.connect` returns NewConnection so I think we should rename from connection to new_connection.
And `let connection = new_connection.connection;` is easy to understand but it's not good because of partial move.
Any ideas?
=> Rename variable of example

.github/workflows/rust.yml, README.md, quinn-proto/src/congestion/bbr/mod.rs, quinn-proto/src/connection/pacing.rs, quinn-proto/src/connection/streams/state.rs, quinn/src/recv_stream.rs
Very minor drive-by doc fixes removing the warnings from `cargo doc --document-private-links` but also enables the `#[warn(rustdoc::broken_intra_doc_links)]` to catch these earlier. With the additional `--document-private-items` in workflow the private links are checked as well.
=> Minor doc fixes, document private items on ci

quinn-udp/Cargo.toml
Closes #1303
This feature flag was always needed, and in some situations, tokio was
enabling that feature flag as well. With the new release of tokio 1.17,
the lack of this flag causes runtime errors because mio 0.7 doesn't have
the required flag as tokio is enabling it in 0.8.
When running tests locally, server_alpn_unset fails, but that happens regardless of this feature flag change.
=> Add os-poll feature to mio

quinn-proto/Cargo.toml
Will release 0.8.1 as soon as this is merged.
=> Backport: Require rustls version with working QUIC 0-RTT support

quinn-udp/Cargo.toml, quinn/Cargo.toml
These received (minor) backports as well.
=> 0.8.x: Bump quinn/quinn-udp versions

quinn-proto/src/config.rs
This constructor doesn't require rustls.
=> Relax feature guard on ServerConfig::with_crypto

quinn/Cargo.toml
Enabling it pulls in `[proto/]ring` regardless, so it's unnecessary and confusing for `Endpoint::client`/`server` to be disabled under `default-features = false, features = ["tls-rustls"]`.
=> tls-rustls feature should imply ring

quinn/src/lib.rs
There is no `generic` module in version 0.8.x, so fix the link.
=> docs: fix broken item link

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/state.rs, quinn/src/connection.rs
Fixes #1313.
This is useful when multiple application protocols are hosted on the same endpoint, or when application logic such as authentication might want to adjust the limits of pre-existing connections.
=> Allow adjustment of per-connection concurrent stream limits

quinn-proto/src/congestion/bbr/bw_estimation.rs, quinn-proto/src/connection/assembler.rs, quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/packet.rs, quinn/examples/server.rs
(cherry picked from commit c0ac7c5234a975edee8e51597cd6edb21e2c7bfe)
=> Backport: Fix handling of invalid retry token lengths

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs
Resolves some correctness issues detected in interop testing, and makes us a bit better at detecting them ourselves.
=> Retry token fixes

quinn-udp/Cargo.toml, quinn-udp/src/unix.rs
Unless I overlooked something, we don't use the mio UdpSocket for anything other than the `only_v6`, which can be easily replaced
=> remove direct mio dependency

quinn/src/connection.rs
This moves a super verbose info span to debug. In addition to reducing clutter, it turns out that when running with RUST_LOG=info, this span actually takes significant cpu time
=> connection: change overly verbose info span to debug

quinn-udp/src/fallback.rs, quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn/src/endpoint.rs
Hello! Thanks for such a great lib! 🤗
As a way to learn quinn I started looking into the IO code and noticed that while GSO is supported, GRO isn't yet. This PR is my first stab at implementing it. Initial results seem promising:
No GRO:
```
Client 0 stats:
Overall download stats:
Transferred 1073741824 bytes on 1 streams in 2.96s (345.49 MiB/s)
Stream download metrics:
│  Throughput   │ Duration 
──────┼───────────────┼──────────
AVG  │  345.62 MiB/s │     2.96s
P0   │  345.50 MiB/s │     2.96s
P10  │  345.75 MiB/s │     2.96s
P50  │  345.75 MiB/s │     2.96s
P90  │  345.75 MiB/s │     2.96s
P100 │  345.75 MiB/s │     2.96s
```
With GRO:
```
Client 0 stats:
Overall download stats:
Transferred 1073741824 bytes on 1 streams in 2.51s (407.22 MiB/s)
Stream download metrics:
│  Throughput   │ …
```
=> Enable UDP GRO

quinn-udp/src/unix.rs
Welp, this was a bit of a head scratcher.
While running `perf_server` and `perf_client` from two different hosts (and so not on loopback), I noticed that occasionally I was getting the following debug logs:
```
2022-05-10T02:53:58.233887Z DEBUG drive{id=0}: quinn_proto::connection: failed to authenticate packet
```
It turns out that these logs are due to truncated GRO segments.
After some kernel spelunking, I noticed this: https://github.com/torvalds/linux/blob/1e8a3f0d2a1ef544611a7ea4a7c1512c732e0e43/net/core/gro.c#L543. The GRO segment size (what we call `stride`), is set dynamically depending on the first datagram that starts a GRO list. Unless the receive buffer passed to `recvmmsg()` is an exact multiple of the segment size, segments can be truncated since `recvmmsg()` will happily …
=> Increase GRO segments to 64

bench/src/stats.rs, perf/src/stats.rs, quinn-proto/Cargo.toml, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/state.rs, quinn-udp/Cargo.toml, quinn-udp/src/unix.rs, quinn/Cargo.toml, quinn/src/connection.rs
Fixes https://github.com/quinn-rs/quinn/issues/1352. This addresses a pressing downstream demand while leaving us more time to work on in-flight breaking API changes (#1357, #1346) without risking excessive breaking-release churn.
=> Prepare 0.8.3 release

quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/paths.rs, quinn-proto/src/lib.rs
Motivated by prospective user request. Also potentially useful for benchmark experimentation.
=> Allow initial maximum UDP payload size to be configured

.github/workflows/rust.yml, README.md, quinn-proto/Cargo.toml, quinn/Cargo.toml
This is >6 months old and should address the CI failure.
=> Bump MSRV to 1.57

bench/Cargo.toml, bench/src/bin/bulk.rs, bench/src/lib.rs, perf/Cargo.toml, perf/src/bin/perf_client.rs, perf/src/bin/perf_server.rs, quinn/Cargo.toml, quinn/examples/client.rs, quinn/examples/server.rs
=> Replace structopt with its successor, clap 3

quinn-proto/Cargo.toml, quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/recv.rs, quinn-proto/src/connection/streams/state.rs
This fixes a handful of basic things so that `quinn-proto` (with no default features) cleanly builds under the `wasm32-unknown-unknown` target, and can be used with a browser-based `wasm-bindgen-test` runner.
* One of the transitive dependencies `getrandom` needs an additional feature to work in the browser
* There is a warning about an unused import when the `ring` feature is not in use
* There were some odd type inference failures:
```
Compiling quinn-proto v0.8.0 (/home/tk/repos/quinn/quinn-proto)
error[E0283]: type annotations needed
--> /home/tk/repos/quinn/quinn-proto/src/connection/streams/recv.rs:150:23
|
150 |             if offset != final_offset.into() {
|                       ^^ ------------------- this method call resolves to `T`
|                       |
| …
```
=> Fix build errors so quinn-proto can be used under wasm32-unknown-unknown

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/recv.rs, quinn-proto/src/connection/streams/state.rs, quinn/src/connection.rs
Problem:
Currently the receive_window on the server side is obtained from the ServerConfig stored in the Endpoint, which will make all connections having the same receive_window and making per connection data limits difficult.
Solution:
Create interfaces to set the receive_window per connection. 
This is to address https://github.com/quinn-rs/quinn/issues/1342 to make receive_window configurable per connection. It only handles receive_window not the stream_receive_window which can be addressed in a separate PR.
=> Configure receive window per connection

quinn-udp/src/unix.rs
I saw that the IP types are changing in Rust... I also saw that this library updated in #987 but (and I could be wrong here) I think there's still an issue on recv? As far as I can tell, `decode_recv` still assumes the layout to be either `sockaddr_in` or `in_addr`
If I'm misunderstanding something here, sorry. I am not a libc or unsafe expert by any stretch.
I copied some of the conversion code from mio: https://github.com/tokio-rs/mio/blob/master/src/sys/unix/net.rs#L143
=> code still assumes memory layout?

.github/workflows/rust.yml, quinn-udp/Cargo.toml, quinn-udp/src/unix.rs
I guess we should yank 0.1.{0,1,2}?
cc @est31 I'm not quite motivated to backport this to older versions than 0.8, but you might be interested.
=> Port fix for address layout reliance to 0.8

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/state.rs, quinn/src/connection.rs
Backport:  Made receive_window  tweak-able per connection on the server side.
=> Backport: Made receive_window  tweakable per connection

quinn-proto/src/connection/assembler.rs, quinn-proto/src/crypto/rustls.rs, quinn-udp/src/unix.rs, quinn/src/connection.rs
This has come up several times, most recently in https://github.com/quinn-rs/quinn/issues/1395. While equivalent behavior is already possible by waiting for e.g. `IncomingUniStreams` to yield `Err` or `None`, this is substantially more discoverable.
=> Define `Connection::closed` helper to await connection termination

.github/workflows/rust.yml, quinn-proto/Cargo.toml, quinn/Cargo.toml
Fixes CI failures with `time`. In theory we could avoid this because AFAICT it's only a dev-dependency, but I'm not sure how we can test without pulling in dev-dependencies, and 1.59 is ~6 months old onw anyway.
=> Bump MSRV to 1.59

quinn-proto/src/packet.rs
Hi!
This PR would allow `Connection` to check Short Header Packets greasing QUIC Bit.
`PlainHeader::decode()` can check Long Header Packets with the QUIC Bit set to a value of 0. If `EndpointConfig` is not set grease_quic_bit with false, it raise `PacketDecodeError::InvalidHeader("fixed bit unset")`. But, in my understanding, Short Header Packets should be checked QUIC Bit too.
- https://www.rfc-editor.org/rfc/rfc9287.html#section-3.1-2
- https://www.rfc-editor.org/rfc/rfc9287.html#section-3.1-3
Thanks.
=> Check QUIC Bit that Short Header Packet set too

bench/src/bin/bulk.rs, bench/src/lib.rs, perf/src/bin/perf_client.rs, perf/src/bin/perf_server.rs, quinn/Cargo.toml, quinn/benches/bench.rs, quinn/examples/client.rs, quinn/examples/connection.rs, quinn/examples/insecure_connection.rs, quinn/examples/server.rs, quinn/examples/single_socket.rs, quinn/src/connection.rs, quinn/src/lib.rs, quinn/src/recv_stream.rs, quinn/src/send_stream.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
Experimenting with a return to named 'static futures, motivated by downstream use cases. See e.g. https://github.com/hyperium/h3/pull/80.
Open questions:
- Which interfaces specifically need to be named?
- Is 'static needed, or just names?
- Are GATs + TAIT close enough that none of this matters?
Also included is an idea to drop `NewConnection` in favor of unobtrusive async methods on `Connection`, bundled because they would have to be rewritten to match this PR's approach if it move forwards. I'd like feedback on this change before I invest the effort to actually remove `NewConnection` and update all the examples/docs.
=> Named futures + replace NewConnection with Connection methods

quinn/src/connection.rs
Convenient for applications which inspect the state of a connection lazily. Motivated by user request in the chatroom.
=> Expose a getter for the close reason

quinn-proto/src/connection/datagrams.rs, quinn/src/connection.rs
Useful for applications which can adapt to variable bandwidth on the fly, such as video streaming. Motivated by discussion with an interested prospective user in that space.
Possible future work: a mechanism to be notified when the space increases, or perhaps reaches a threshold.
=> Accessor for free datagram send buffer space

quinn-udp/Cargo.toml, quinn/Cargo.toml
quinn-proto is a public dependency of quinn-udp (for example, `RecvMeta` exposes `EcnCodePoint`). #1429 bumped the version for quinn-proto and the dependency for quinn-udp, but not quinn-udp's version; do that here.
Since I was building in an old working directory I also noticed that I was unable to compile quinn with the tokio 1.9 that `Cargo.lock` was set to. Bump the tokio dependency up to 1.13 which is the oldest version that seems to compile.
=> quinn-udp: bump version to 0.3

perf/src/bin/perf_client.rs, perf/src/bin/perf_server.rs
This allow dumping crypto keys to disk using SSLKEYLOGFILE env var.
=> Add --keylog command line option for perf client and server binaries.

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/connection/streams/recv.rs, quinn-proto/src/connection/streams/send.rs, quinn-proto/src/connection/streams/state.rs, quinn-proto/src/frame.rs, quinn/examples/server.rs, quinn/src/connection.rs
When the application observes a stream finish or reset, we dispose of its state via `StreamsState::stream_freed`, and queue a transmit of stream flow control credit directly on the `Connection`. `stream_freed` however also sets `StreamsState::max_streams_dirty`, which is polled each time we receive a packet to see whether a stream has become fully closed due to an incoming frame. Together, these led to a MAX_STREAMS frame being transmit both immediately, and following the next packet receipt. We prevent that by unsetting the appropriate `max_streams_dirty` flags when sending `MAX_STREAMS`.
=> Fix duplicate MAX_STREAMS transmit

quinn/src/connection.rs, quinn/src/tests.rs
After a spurious wakeup, `Connection::open_uni` and `open_bi` would switch to waiting for notifications about incoming streams, rather than the intended notification about new stream ID flow control budget. This was probably a copy-paste error from `poll_accept`.
Let's get a patch release out as soon as this is merged.
=> Fix stream open futures sometimes waiting on the wrong notification

.github/workflows/rust.yml, README.md, quinn-proto/src/connection/assembler.rs, quinn-proto/src/connection/streams/send.rs, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/frame.rs, quinn-udp/src/unix.rs, quinn/examples/server.rs
old macOS versions don't have it, so if you try say `connection` example on macOS 10.11, it'll error with IoError 42 - Protocol not available.
I'm not sure if you're wanting a tracing log, or if you're planning on another 0.8.x release but we're still on it until we do our next non-bugfix release where we'll go to 0.9. Easily can be applied to 0.9/main too.
=> fix: don't bail if setting IP_RECVTOS fails

quinn-udp/Cargo.toml
Preparation for a release including #1448 for quinn 0.8's benefit.
=> Bump quinn-udp for old macOS compat

quinn-udp/src/unix.rs
One of my Linux test machine has IPv6 disabled. While doing some bench and test on it, i noticed that GSO / GRO were not enabled. Here is a small fix to fallback to an IPv4 loopback in case it failed on IPv6 loopback.
=> Fix GSO / GRO auto detection when IPv6 is disabled.

quinn/Cargo.toml, quinn/src/connection.rs, quinn/src/tests.rs
The previous logic assumed that a datagram must be available if the future was notified, but this might not be the case if e.g. two futures are concurrently waiting for datagrams, but only one datagram has been received, since we use notify_waiters to wake all waiting futures to be robust in the face of cancellation.
Fixes #1454.
=> Fix panic on concurrent read_datagram completion

quinn/src/connection.rs, quinn/src/send_stream.rs
In the event that the SendStream Stopped future is polled once and then dropped before the remote side has stopped the stream, and instead the stream has been finished, the waker registered in the connection stopped map is never removed and is effectively "leaked" until the connection is closed. This can lead to a large amount of memory being retained when a connection is very long lived and many streams are used over the life of that connection.
This particular issue can be seen with this type of usage of SendStream::stopped: https://github.com/bmwill/anemo/blob/main/crates/anemo/src/network/request_handler.rs#L170-L177.
This is one such way to fix this memory retention, although it may not be the project's preferred way. Another option would potentially be to remove the waker from the …
=> connection: wake 'stopped' streams on stream finish events

.github/workflows/rust.yml, quinn-udp/src/unix.rs, quinn/src/connection.rs, quinn/src/tests.rs
=> add FreeBSD IP_RECVDSTADDR support

quinn-udp/src/unix.rs
Let's get #1447 in first, but I think something like this would be a bit nicer?
=> udp: add safe wrapper for setsockopt()

quinn-proto/src/connection/mod.rs
This has no effect with our default minimal MTU, but if the MTU is configured higher manually it's required for conformance.
=> Respect max_udp_payload_size transport parameter

docs/book/src/quic.md
=> Update Wording About Quick Being a Draft

quinn-proto/src/endpoint.rs
Silent failure here has tripped up multiple users, most recently in https://github.com/quinn-rs/quinn/issues/1472.
=> Fail gracefully on attempts to connect to an unspecified IP address

quinn-proto/Cargo.toml, quinn-udp/Cargo.toml, quinn/Cargo.toml
Prompted by #1472. The inter-crate edges aren't strictly necessary since `tracing`'s features will be unified across all crates, but ensuring a consistent feature state seems tidy.
=> Route logs via `log` crate by default when `tracing` isn't used

quinn/src/lib.rs
To implement `AsyncUdpSocket` Trait from `quinn` crate, we must use the types `RecvMeta` and `UdpState`. However, current version of quinn does not re-export them, so anyone who wants to implement the trait needs importing another `quinn-udp` crate. This PR fixes this problem by re-export them in `quinn` crate.
=> Re-export udp::{RecvMeta, UdpState} for AsyncUdpSocket

quinn-proto/src/endpoint.rs
If the cryptographic layer supports a version not in the local endpoint's supported versions list, a connection was initiated but all packets returned by a compatible peer were dropped. This is a relatively easy configuration error to make.
Fixes #1481.
=> Improve error when connecting with an unsupported version

perf/Cargo.toml, perf/src/bin/perf_client.rs, perf/src/bin/perf_server.rs, perf/src/lib.rs, perf/src/noprotection.rs
This can be use when doing performance tests to reveal other hot-spots than packet encryption and decryption.
This is for testing purpose and should not be used in production.
=> Add dangerous_packet_null_cipher feature to disable packet encryption.

quinn/src/lib.rs
With https://github.com/quinn-rs/quinn/pull/1364 `quinn` is no longer restricted to `tokio`. Commit updates the crate heading accordingly.
Note that I don't feel strongly about this. Just a drive-by contribution.
=> docs(quinn): remove restriction to tokio

quinn/src/recv_stream.rs
It is not trivial to correctly close a stream without errors and knowing everything is fully acknowledged.  Describe some details around this.
=> Document how to close a stream correctly

quinn/Cargo.toml, quinn/examples/client.rs, quinn/examples/server.rs, quinn/src/recv_stream.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
Allows `RecvStream::stop` to be called with custom error codes if `ReadToEndError::TooLong` is encountered.
See also discussion in #1493.
=> Borrow `self` in read_to_end, rather than consuming

quinn-udp/src/unix.rs
Some Android phones use older 2.x kernels
and do not support `sendmmsg`
which is available only since Linux 3.0.
Similarly, `recvmmsg` is only available
since Linux 2.6.34.
=> Implement fallback for `sendmmsg` and `recvmmsg`

quinn-udp/src/lib.rs, quinn-udp/src/unix.rs
On Linux <3.13 sendmsg/sendmmsg system calls
return EINVAL without sending anything if they encounter an `IP_TOS` cmsg. To ensure we can still send
on such systems, remember if we got an EINVAL error and switch to "fallback mode" in which we do not try to transmit ECN at all and only use well-supported features.
=> Fallback to not using ECN if IP_TOS is not supported

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/connection/streams/state.rs
Would you prefer VarInts here?
Fixes #1517
=> Getters for stream concurrency metrics and related documentation

quinn-proto/src/crypto.rs, quinn-proto/src/transport_error.rs
These changes are needed for the BoringSSL crypto provider (#1488), which will reside in a separate repository.
=> Support external crypto implementations.

quinn-udp/src/fallback.rs, quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn-udp/src/windows.rs, quinn/src/runtime.rs, quinn/src/runtime/async_std.rs, quinn/src/runtime/tokio.rs
I am currently running into the issue that it requires a large amount of locking when implementing a custom `AsyncUdpSocket`, because `poll_send` at the moment requires `&mut self`. 
So I looked into the reason that is (given that a regular `UdpSocket::send` does not require mutable access), and it turned out to only need write access to the `last_send_error` time. As the simplest option I put that behind a `Mutex`, which I think will be fine, but open to discussion of other variants, e.g. storing it in an atomic type or similar.
=> Do not require &mut self in AsyncUdpSocket::poll_send

quinn-proto/Cargo.toml
Provides API changes needed by https://github.com/quinn-rs/quinn-boring/pull/2.
=> Bump quinn-proto version

bench/Cargo.toml, perf/Cargo.toml, quinn-proto/Cargo.toml, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/tests/mod.rs, quinn-udp/Cargo.toml, quinn/Cargo.toml
Update branch for quinn-proto v0.10.0, using Rustls v0.21.0
This commit updates Quinn's dependency on Rustls from v0.20.3 to v0.21.0.
This release includes a handful of small breaking changes which are resolved alongside the upgrade.
As part of upgrading the quinn-proto rustls dependency we must do a semver incompatible version bump since rustls is exposed as part of the public API.
=> quinn-proto v0.10.0 w/ rustls v0.21.0

quinn/src/tests.rs
This is unnecessarily racy, at least in principle.
=> Don't rely on sleeping in 0-RTT test

bench/src/lib.rs, perf/src/bin/perf_client.rs, perf/src/bin/perf_server.rs, quinn-proto/src/config.rs, quinn-proto/src/connection/datagrams.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/mtud.rs, quinn-proto/src/connection/pacing.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/connection/paths.rs, quinn-proto/src/connection/stats.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/benches/bench.rs, quinn/examples/client.rs, quinn/examples/common/mod.rs, quinn/examples/insecure_connection.rs, quinn/examples/server.rs, quinn/src/lib.rs
This PR resurrects @djc's old https://github.com/quinn-rs/quinn/pull/804. As of yet, it is just a draft. IMO it makes sense to look at the commits separately (we might want to squash them in the end, though).
Below are some bits of feedback from the original PR that I'm planning to include before considering this PR as ready for review (feel free to suggest more):
~~Looking at the original PR, there is one question that comes up: I am tracking ACKs for MTU probes manually (e.g. without using `PackageBuilder::finalize_and_track`), because otherwise things like automatic retransmission kick in. That seems different from what @djc did in the original PR (he seems to get ACK and packet loss detection automatically, without additional code). Am I working in the right direction, or did I miss a …
=> Initial support for PLPMTUD

quinn-udp/Cargo.toml, quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn-udp/src/windows.rs, quinn/src/endpoint.rs, quinn/src/runtime.rs, quinn/src/runtime/async_std.rs, quinn/src/runtime/tokio.rs
To avoid a dependency edge from -udp -> -proto.
=> Duplicate Transmit and EcnCodepoint across -proto and -udp

quinn-udp/Cargo.toml, quinn/Cargo.toml
It includes a fallback for old Linux and Android systems which do not support setting ECN flag on UDP packets.
=> Bump quinn-udp version to 0.4

perf/src/noprotection.rs
While profiling stuff with perf_server and perf_client, I discovered that the `no-protection` option was not working as expected (it did not disable packet encryption / decryption, as my flamegraphs revealed). It looks like the original feature did disable encryption after a key update, but forgot to do so right after the handshake. This PR fixes that.
In case you are curious, you can observe the problem by running the following commands:
1. `cargo run --release --bin perf_server`
2. `cargo run --release --bin perf_client -- --no-protection`
3. Watch the server and the client happily exchange packets (instead of failing to connect because of the mismatch in encryption)
=> Fix `no-protection` option in perf crate

bench/src/lib.rs, perf/src/bin/perf_client.rs, perf/src/bin/perf_server.rs, quinn-proto/src/config.rs, quinn-proto/src/congestion.rs, quinn-proto/src/congestion/bbr/mod.rs, quinn-proto/src/congestion/cubic.rs, quinn-proto/src/congestion/new_reno.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/mtud.rs, quinn-proto/src/connection/pacing.rs, quinn-proto/src/connection/paths.rs, quinn-proto/src/connection/stats.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs
This PR introduces a few self-contained improvements to make PLPMTUD work better.
We will probably want to discuss the API impact of the change to the congestion controller code:
* New `on_mtu_update` function on the `Controller` trait
* Removed `max_datagram_size` from all controller configs (the current MTU is used now instead)
* Removed `minimum_window` from all controller configs (it is now calculated on demand based on the current MTU)
With all this in place, running the top-level `bench` crate with a MTUD upper bound of 9000 results in sending rates of ~900 MiB/s (on my machine ™).
=> Tie up PLPMTUD's loose ends

quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/mtud.rs, quinn-proto/src/connection/paths.rs
This is a rebased and ready-to-merge version of #1551
=> Rename min_guaranteed_mtu to min_mtu for clarity

bench/src/lib.rs, perf/src/bin/perf_client.rs, perf/src/bin/perf_server.rs, quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn-udp/Cargo.toml, quinn-udp/src/fallback.rs, quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn-udp/src/windows.rs, quinn/benches/bench.rs, quinn/examples/client.rs, quinn/examples/common/mod.rs, quinn/examples/insecure_connection.rs, quinn/examples/server.rs, quinn/src/endpoint.rs, quinn/src/runtime.rs, quinn/src/runtime/async_std.rs, quinn/src/runtime/tokio.rs
Fixes https://github.com/quinn-rs/quinn/issues/664.
Some questions following from this work:
- Should MTU discovery configuration be on the endpoint, rather than the connection? It's hard to imagine a case where a user might want to vary this per-connection, and usually the main concern is whether the common socket has DONTFRAG set. On the other hand, the reduction in complexity from moving it to the endpoint seems slight. I guess you could use a single endpoint to communicate both on a jumbo-frame-capable LAN and also the internet...
- Setting IP_DONTFRAG might fail pre-Big Sur (version 11). As written, this PR will make endpoint creation fail if this occurs, probably with `EINVAL`. Are older macOS builds worth supporting?
- ~Can we reduce the amount of work required from users to create …
=> Fragmentation handling improvements

quinn-udp/src/unix.rs
Currently `main` branch does not compile on FreeBSD 13.2
<details>
<summary>build log</summary>
```➜  quinn git:(main) cargo build
Compiling quinn-proto v0.10.0 (/usr/home/maksimv/quinn/quinn-proto)
Compiling quinn-udp v0.4.0 (/usr/home/maksimv/quinn/quinn-udp)
Compiling clap v3.2.25
Compiling serde v1.0.162
error[E0425]: cannot find value `SYS_sendmmsg` in crate `libc`
--> quinn-udp/src/unix.rs:319:35
|
319  |       let ret = libc::syscall(libc::SYS_sendmmsg, sockfd, msgvec, vlen, flags) as libc::c_int;
|                                     ^^^^^^^^^^^^ help: a function with a similar name exists: `sendmmsg`
|
::: /home/maksimv/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.142/src/unix/bsd/freebsdlike/freebsd/mod.rs:5162:5
|
5162 | /     pub fn sendmmsg(
5163 | | …
```
=> Fix: build and tests on `FreeBSD 13.2`

.github/workflows/rust.yml
FreeBSD CI Action gives false success results. Here is possible explanation: [#1556](https://github.com/quinn-rs/quinn/issues/1556)
Removing fuzz tests is not ideal, but better than getting false success CI check results on every run
=> Fail FreeBSD CI if any step fails

.github/workflows/rust.yml, bench/Cargo.toml, fuzz/Cargo.toml, perf/Cargo.toml, quinn-udp/Cargo.toml, quinn-udp/src/fallback.rs, quinn-udp/src/lib.rs, quinn-udp/src/windows.rs, quinn/Cargo.toml
This should be okay now that we've bumped our MSRV?
=> Upgrade socket2 to 0.5

perf/Cargo.toml, quinn-proto/Cargo.toml, quinn/Cargo.toml
This commit updates the existing Quinn sub-crate dependencies to remove the explicit `webpki` v0.22 dependency. It's not used by directly anywhere and can be a transitive dependency through rustls as required.
=> deps: remove webpki dependency.

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/state.rs, quinn-udp/src/fallback.rs, quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn-udp/src/windows.rs, quinn/src/endpoint.rs, quinn/src/recv_stream.rs, quinn/src/tests.rs
This pull request fixes a few typos.
=> Fix some typos

.github/workflows/book.yml, .github/workflows/codecov.yml, .github/workflows/rust.yml
Updates the `actions/checkout` action used in the GitHub Actions workflows to its newest major version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.5.2
> - Fix api endpoint for GHES
>
> ## v3.5.1
> - Fix slow checkout on Windows
>
> ## v3.5.0
> - Add new public key for known_hosts
>
> ## v3.4.0
> - Upgrade codeql actions to v2
> - Upgrade dependencies
> - Upgrade @actions/io
>
> ## v3.3.0
> - Implement branch list using callbacks from exec function
> - Add in explicit reference to private checkout options
> - Fix comment typos
>
> ## v3.2.0
> - Add GitHub Action to perform release
> - Fix status badge
> - Replace datadog/squid with ubuntu/squid Docker image
> - Wrap pipeline commands for submoduleForeach in quotes
> - Update @actions/io to 1.1.2
> - …
=> Update actions/checkout in GitHub Actions workflows to v3

quinn-proto/src/lib.rs
Right now, if `quinn-proto` is built without `--features=arbitrary`, one gets an error about an unresolved import. The `compile_error` helps to clarify why.
An alternative would be to try and disentangle `--cfg fuzzing` and `--features=arbitrary`. But this change is less invasive.
=> Allow compilation with `--cfg fuzzing` but not `--features=arbitrary`

docs/book/src/quinn/certificate.md
Updates the guide book to suggest using `fullchain.pem` and not `cert.pem`.
Closes https://github.com/quinn-rs/quinn/issues/1573
=> Docs: Use fullchain.pem in the certbot example

.github/workflows/codecov.yml, .github/workflows/rust.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/quinn-rs/quinn/actions/runs/5100061676:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, Swatinem/rust-cache@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are …
=> Replace unmaintained actions-rs/* actions in CI workflows

quinn-proto/Cargo.toml, quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/packet.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/Cargo.toml, quinn/src/endpoint.rs
Straightforward improvements extracted from #1578.
=> Miscellaneous cleanup

quinn-proto/src/endpoint.rs
Leftovers from https://github.com/quinn-rs/quinn/pull/1581.
=> Update obsolete doc comment

quinn-proto/src/endpoint.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/src/endpoint.rs
Closes #1584
This commit adds a new function that refuses new connections without impacting existing connections. Internally, this just sets the connection limit to 0, which causes incoming connections to be rejected. This is the same approach that was taken in 0.8.5 when `Incoming` was dropped.
Let me know if I should also add a unit test to the `quinn` crate. Since it's a simple pass-through, I elected not to initially.
=> Added Endpoint::reject_new_connections

.github/workflows/book.yml, .github/workflows/codecov.yml, .github/workflows/rust.yml, quinn-proto/src/endpoint.rs, quinn-proto/src/tests/mod.rs, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/send_stream.rs
Started a branch from the 0.10.1 tag and backported:
* #1588
* #1585
* #1581 (only the commit that removed `Endpoint::reject_new_connections()`)
* #1579
* #1571
=> 0.10 backports

quinn/src/endpoint.rs
Wrapping the std socket with either  `TokioRuntime` or `AsyncStdRuntime` returns `Box<dyn AsyncUdpSocket>`.  Creating an endpoint with an abstract socket requires `impl AsyncUdpSocket` and it is therefore not possible to use a wrapped socket together with `new_with_abstract_socket`.
This MR fixes this inconsistency by using `Box<dyn AsyncUdpSocket>` in `new_with_abstract_socket`.
=> Use boxed AsyncUdpSocket when creating abstract endpoint

quinn/src/endpoint.rs
In my previous [MR](https://github.com/quinn-rs/quinn/pull/1534/files) I accidentally made the constructor private. This MR fixes this.
=> fix: Make new_with_abstract public again

quinn-proto/src/range_set/array_range_set.rs, quinn-proto/src/range_set/btree_range_set.rs
=> Replace `.rev().next()` with `.next_back()`

quinn/src/lib.rs
This PR makes quinn reexport all `rustls` types as discussed in #300. This change helps fix the issue described in [this example](https://github.com/jonatanzeidler/quinn-rustls-issue) by allowing it to use the reexported types.
=> Reexport rustls types

quinn-proto/src/config.rs, quinn-proto/src/connection/ack_frequency.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_crypto.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/connection/stats.rs, quinn-proto/src/connection/timer.rs, quinn-proto/src/frame.rs, quinn-proto/src/lib.rs, quinn-proto/src/packet.rs, quinn-proto/src/shared.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn-proto/src/transport_parameters.rs
Overview of the feature:
* The ack frequency extension allows one to control the ACK frequency of the remote peer.
* Quinn provides an `AckFrequencyConfig` to control the parameters, which are sent to the peer in an `ACK_FREQUENCY` frame at the beginning of the connection (technically, the extension allows modifying the ack frequency parameters multiple times during a connection, but then you would need to come up with an algorithm to automatically tune the parameters, which IMO is out of scope for this first implementation).
* On the other side of the connection, Quinn will receive and process the `ACK_FREQUENCY` frame, updating the local ack frequency parameters based on the new parameters sent by the peer.
* If the local peer has requested a custom ack frequency from the remote peer, …
=> Implement acknowledgement frequency

quinn-proto/src/config.rs
As of 092a7686a4dc95f888b9b2338f9d9a4a3936295b, MTUD is enabled by default on all major platforms, and automatically disabled regardless of configuration otherwise.
=> Update docs for UDP fragmentation configuration support

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs
Inspired by quic-go's behavior as documented in https://mailarchive.ietf.org/arch/msg/quic/glen5JXVLU9BhmIB73E2UOUOp6M/.
=> Perform a key update early in a connection's lifetime

quinn-udp/Cargo.toml, quinn-udp/src/fallback.rs, quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn-udp/src/windows.rs, quinn/Cargo.toml, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/runtime.rs, quinn/src/runtime/async_std.rs, quinn/src/runtime/tokio.rs
Allows knowledge of UdpState to be isolated entirely within AsyncUdpSocket implementations, simplifying quinn::Endpoint and the poll_send API, and exposing more control over UDP feature checks to implementers.
Fixes #1609.
=> Fold UdpState into AsyncUdpSocket

quinn-proto/src/config.rs
Drastically reduces the size and sparsity of the quinn receive buffer for no performance cost in typical applications.
Fixes #1608. Alternative to #1611 with less impact on endpoints that are heavily loaded by many peers. Not certain which we should prefer yet; `recvmmsg` might not be buying us all that much, but neither is supporting jumbo frames (outside of loopback). Maybe we should even do both!
=> Reduce default maximum UDP payload size to the ethernet MTU

quinn/src/endpoint.rs
The EndpointDriver is spawned in a task.  Unless the span is copied into this task the current span is lost.
Copying the current span means any tracing calls inside the driver, from e.g. a custom AsyncUdpSocket, are preserved in the span.  This makes it easy to use different parent spans for different endpoints and have log messages appear with their parent span.  Otherwise these log messages are not attached to a span.
----
An alternative is to create a new span using `tracing::info_span!("endpointdriver")` instead of copying the current span.  This new span would also be correctly attached to the current span as a child.
=> Preserve the tracing span in the EndpointDriver task

quinn-proto/src/config.rs
Drastically reduces the size and sparsity of the quinn receive buffer for no performance cost in typical applications.
=> Backport to 0.10.x: Reduce default maximum UDP payload size to the ethernet MTU

quinn-proto/src/connection/streams/state.rs, quinn-proto/src/transport_parameters.rs
This was a footgun for custom crypto session implementers.
=> Privatize TransportParameters::default()

quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn-udp/src/windows.rs, quinn/src/runtime/async_std.rs, quinn/src/runtime/tokio.rs
[fix issue](https://github.com/quinn-rs/quinn/issues/1624)
=> set may_fragment based on whether setting IP_DONTFRAG fails with ENOPROTOOPT.

quinn-udp/src/unix.rs
These are occasionally expected now that we're generating MTU probes, and have been observed to cause unnecessary concern from users.
=> udp: don't log EMSGSIZE errors

quinn-udp/src/unix.rs
Linux 5.15 was observed to emit an EINVAL when attempting to transmit UDP with GSO over IPv6 on a virtio net interface, which apparently only supports UDP GSO on IPv6 as of Linux 6.2. 6.1 was also observed to emit EINVAL, though only after EIO. In both cases, EINVAL was suppressed by disabling GSO.
Companion change to #1636. I don't fully understand why Linux is returning EINVAL in these cases, so I'm not 100% certain this is the correct fix, but at the very least it won't hurt.
=> udp: disable GSO on EINVAL

quinn-proto/Cargo.toml, quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs, quinn-udp/Cargo.toml, quinn-udp/src/unix.rs
Backport of #1636 and #1637 to the release branch. Should block on review of those.
=> Backport gso mitigations

quinn-proto/Cargo.toml
=> proto: bump to 0.10.3

quinn/src/connection.rs, quinn/src/tests.rs
Follow-up for #1616, which finally lets us get easily intelligible interleaved logs for single-process tests.
=> Propagate current tracing span to spawned connection drivers

quinn-proto/src/config.rs, quinn-proto/src/congestion.rs, quinn-proto/src/congestion/bbr/mod.rs, quinn-proto/src/congestion/cubic.rs, quinn-proto/src/congestion/new_reno.rs, quinn-proto/src/connection/mod.rs
Allows callers who already have a trait object to pass it on without yet more boxing.
This propagates a lesson we've learned a few times at the `quinn` layer.
=> proto: Fix double-boxing of congestion::ControllerFactory 

quinn-proto/src/endpoint.rs
A panic here was reported by a user when testing under very scarce CPU conditions. The root cause is not yet well understood (perhaps a connection emitting `Drained` twice for some reason?), but we can still reduce the blast radius.
=> proto: don't panic when draining an unknown connection

Cargo.toml, quinn-proto/src/endpoint.rs, quinn-proto/src/range_set/btree_range_set.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/src/endpoint.rs
Fixes #1648 and cleans up new warnings from Rust 1.72.
=> Require explicit timestamp for Endpoint::connect(), Rust 1.72

quinn/src/lib.rs
A pub export for type proto::AckFrequencyConfig is missing in quinn.
=> Add missing export for proto::AckFrequencyConfig.

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/stats.rs
Since this field exists for both tx and rx, we might as well make use of it.
=> Generalize UdpStats::transmits to ios

quinn-proto/src/config.rs, quinn-proto/src/connection/ack_frequency.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/timer.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs
Alternative to #1654. Reduces the amount of communication required compared to the status quo when the RTT is not varying wildly.
This preserves the pre-existing behavior where `max_ack_delay` is effectively clamped below the current RTT. It might be useful to also offer an escape hatch to force it higher, although such a configuration is contrary to the "SHOULD" recommendation of the ack frequency draft.
=> Send ACK_FREQUENCY frames intelligently rather than spamming IMMEDIATE_ACK

quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs
Hi,
we love quinn but we recently had a hard time with GSO and fly.io hosting and quinn 0.9.4!
This errors are piling up in the logs:
> sendmsg error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, Transmit: { destination: [dead:0:beef:a7b:17b:0101:2345:2]:11111, src_ip: None, enc: Some(Ect0), len: 1291, segment_size: Some(1200) }
After some research we concluded that quinn's GSO detection returns a false-positive - at least on fly.io machines!
Our reasoning:
1. The problem went away by disabling GSO with patch a06838.
2. fly.io support confirmed GSO is not supported on their platform!
short term: backport a06838 to allow manual disabling GSO
long term: backport a fix for the feature detection
maybe the solution should be ported to 0.10 too
=> backport to 0.9: Allow GSO to be manually disabled

.github/workflows/rust.yml, README.md, bench/Cargo.toml, perf/Cargo.toml, quinn-proto/Cargo.toml, quinn-proto/src/connection/spaces.rs, quinn-udp/Cargo.toml, quinn/Cargo.toml
Reflects the logic change in https://github.com/quicwg/ack-frequency/pull/222. See also discussion in https://github.com/quicwg/ack-frequency/issues/183.
=> Fix ACK frequency extension corner case

quinn-proto/src/connection/mod.rs, quinn-proto/src/frame.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/src/connection.rs
Received a private bug report from @QUICTester. Thanks!
This should probably have a test, which I don't have energy for right now. @Ralith any suggestion for where such a test should live?
I don't love that this equates "no frames" to "empty payload" which feels like a potential conceptual jump, but the for-loop formulation makes the alternative a decent bit more verbose...
=> Yield protocol violation for packets without frames

quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/Cargo.toml, quinn/src/connection.rs, quinn/src/endpoint.rs
`quinn-proto::{Connection, Endpoint}` structs call `StdRng::from_entropy()` in their implementation. It makes it hard to reproduce errors in an otherwise deterministic test case.
This PR addresses the issue by adding a `StdRng` argument to the respective `new` functions. For other functions that may create an endpoint/connection, an argument of type `impl FnOnce() -> StdRng` is added. This avoids eager calls to generate fresh entropy. e.g. the `Endpoint::handle` function is frequently called but we'd only need the rng when handling a new incoming connection.
Fixes an unrelated lint error.
Closes #1684
=> Make `quinn-proto::{Connection, Endpoint}` deterministic

quinn-proto/LICENSE-APACHE, quinn-proto/LICENSE-MIT, quinn-udp/LICENSE-APACHE, quinn-udp/LICENSE-MIT, quinn/LICENSE-APACHE, quinn/LICENSE-MIT
This PR adds symbolic links for the `LICENSE-APACHE` and `LICENSE-MIT` files into the `quinn`, `quinn-proto`, and `quinn-udp` workspace members so that `cargo package` / `cargo publish` picks them up and includes them when publishing crates.
Both the Apache-2.0 and the MIT license requires that (re)distributed sources contain a copy of the license text. Not including the license text is a problem, especially for Linux distributions that package this crate as a dependency, for example, for the HTTP/3 support in the `reqwest` crate.
I have not added a symlink into workspace members that have `publish = false` set in their cargo metadata.
=> ensure LICENSE files are present in all published crates

quinn-proto/src/config.rs, quinn-proto/src/connection/mtud.rs
Previously the binary search algorithm used during the MTU discovery phase was stopping itself if the discovered MTU was within -20 / +20 of the previous detected one.
This could lead to finding a MTU 40 bytes smaller of the real one in the worst case.
This change allow changing the default minimum change value if more precision is needed.
=> proto: add a way to configure the minimum MTU change needed to stop the binary search used during the MTU discovery phase.

quinn-proto/Cargo.toml, quinn-proto/src/connection/mod.rs
The same as https://github.com/quinn-rs/quinn/pull/1705 + version bump
=> Backport to 0.10.x: Downgrade duplicate packet message to debug level

.github/workflows/rust.yml
As recommended in [release notes](https://github.com/vmactions/freebsd-vm/releases/tag/v1.0.0) for v1 of the Action.
=> Run FreeBSD workflow on Ubuntu

quinn-proto/src/config.rs
It is not used since
<https://github.com/quinn-rs/quinn/pull/134>
(commit bdc9ac76a453208848a58bf3b24a633ade8b299a)
was merged in 2018.
RFC 9002 also does not mention Tail Loss Probe
except that it has been integrated into the PTO (Probe Timeout)
mechanism.
=> Remove "max_tlps" configuration variable

quinn/src/endpoint.rs
Most packets (under good conditions), let alone most wakeups, don't require a response from the endpoint, so this was very wasteful. `BytesMut::new` [is guaranteed](https://docs.rs/bytes/latest/bytes/struct.BytesMut.html#growth) to grow automatically when needed.
=> Don't allocate an endpoint response buffer for every driver wakeup

quinn-udp/tests/tests.rs
Inspired by #1701. Should substantially reduce risk of breakage and ease supporting new platforms.
=> Test UDP layer in isolation

quinn-udp/src/fallback.rs, quinn-udp/src/unix.rs, quinn-udp/src/windows.rs
Use `io::Result<>` in `quinn-udp` module. This was found as non blocking in #1701
=> udp: use io::Result<> where possible

quinn-udp/src/lib.rs
We've had a few users unclear on quinn-udp's role.
=> udp: Expand crate documentation

quinn-proto/Cargo.toml, quinn-proto/src/config.rs, quinn/Cargo.toml
rustls-platform-verifier doesn't seem to support rustls 0.22 yet, so we might want to hold off on this in the hopes of not complicating #1715. Still, long-term, this seems like a safer default to promote.
=> Replace rustls-native-certs with rustls-platform-verifier

quinn/Cargo.toml, quinn/src/lib.rs, quinn/src/runtime.rs, quinn/src/runtime/async_io.rs, quinn/src/runtime/async_std.rs
Support [`smol`](https://github.com/smol-rs/smol) async runtime.
=> Support `smol` runtime

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/paths.rs, quinn-proto/src/connection/stats.rs
We previously always sent these on the active path, which undermines a peer's validation of the return direction of a candidate new path.
=> Send path validation responses to the correct remote

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs
PacketBuilder::max_size previously subtracted out the start index and header size of the packet, and therefore described the admissible size of the packet's frames. However, most of our logic operates in terms of absolute buffer positions instead. This was confusing, and led to erroneous double-counting of space use in close packets.
Discovered while drafting #1767.
=> Don't double-count buffer consumption in close length checks

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/tests/mod.rs
=> Improve behavior when only one peer sends ACK-eliciting packets

quinn-proto/src/frame.rs
Both the draft and the IANA registry say the current value for frame_type IMMEDIATE_ACK is 0x1F.
https://www.iana.org/assignments/quic/quic.xhtml
https://datatracker.ietf.org/doc/html/draft-ietf-quic-ack-frequency#section-10.2
=> Fix constant of frame_type IMMEDIATE_ACK

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/connection/paths.rs
Fixes #1775, theoretically. @nemethf can you confirm?
RFC9000 §9.4:
> The capacity available on the new path might not be the same as the old path. Packets sent on the old path MUST NOT contribute to congestion control or RTT estimation for the new path.
We accomplish this by tracking the first packet number on each path, which allows the logic that removes acked/lost packets from congestion control counters to determine which, if any, known path a packet was sent on.
=> Maintain in-flight counters separately per path

quinn-udp/src/unix.rs
We're using the info obtained with `PKT_INFO`, particularly the destination IP, on multiple platforms including on android.
Most of the socket options used for linux, save for GRO, are available on android, so it's simply adding it to the conditional compilation.
=> Enable packet info and related flags for quinn-udp on Android

quinn/src/send_stream.rs
=> Expose SendStream::poll_write and poll_finish methods

quinn/src/recv_stream.rs
=> Expose RecvStream::poll_read & poll_read_chunk

quinn-udp/src/unix.rs
It appears that IPv4-only is [broken on iOS](https://github.com/firezone/firezone/issues/4276).
Enabling the same code paths for ios that exist for macos fixes all issues. In our testing, we've found the network stacks to be nearly identical between iOS and macOS.
This fork has been tested on 3 physical iOS devices with IPv4-only, IPv6-only, and dual stack configurations on iOS 17.
Thanks for the great library. Happy to do any further testing!
=> Enable `ios` for the same os_type checks as `macos`

quinn-proto/src/transport_parameters.rs
Follow-up from #1791, these looked a little weird to me.
=> Tweak comment alignment for transport parameter validation

quinn-proto/src/connection/mod.rs
I've just bumped into this.  I'm not confident this is really a bug, but using the MTU of a different path seems a wrong thing to do.
=> Use the correct MTU for prev_path

quinn-proto/src/connection/mod.rs, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/lib.rs
The server switches to a new CID as well, but it sends a path-challenge on the old path with the new CID.  So it is still possible to trace back the connection to the old path after the client switches to a new socket.
=> Break linkability on client-side after planned migration

quinn/src/endpoint.rs
With Rust 1.63.0 one can initialize a `std::array` via `std::array::from_fn`.
https://doc.rust-lang.org/std/array/fn.from_fn.html
Thus there is no need to start with an uninitialized array via `MaybeUninit`, initialize it and then use `unsafe` to `assume_init`. Instead one can initialize the array with the concrete elements right away.
---
Meta: `quinn-udp` has been very helpful in https://github.com/mozilla/neqo/pull/1741. Thanks!
=> refactor(endpoint): use array::from_fn instead of unsafe MaybeUninit

quinn/src/endpoint.rs, quinn/src/incoming.rs
Threading buffers through alongside the `Incoming` does not reduce the number of allocations.
=> Allocate Incoming response buffers as needed

quinn-proto/src/cid_generator.rs, quinn-proto/src/congestion.rs, quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/connection/streams/state.rs, quinn-proto/src/crypto.rs, quinn-proto/src/tests/mod.rs
The only things preventing these types from already being `Sync` were a lack of `Sync` bounds on trait objects they were storing, and a `RefCell` that was only being used to work around a limitation in the API of `BinaryHeap`.
Adding `Sync` bounds to the relevant traits was simple enough and didn't cause any warnings or errors, but to remove the `RefCell` it was necessary to rework the way that pending stream IDs were stored.
The specific motivation for this PR was so that I could store these types as components directly in the [Bevy ECS](https://bevyengine.org/), which requires component types be `Send + Sync` for multi-threaded system scheduling. The alternative would be to wrap the types in a `Mutex` or other synchronization primitive, but removing the limitation entirely seemed like …
=> Make `quinn_proto::Connection` and `quinn_proto::Endpoint` impl `Sync`

quinn-proto/src/config.rs, quinn-proto/src/connection/cid_state.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/tests/util.rs, quinn-proto/src/transport_parameters.rs, quinn/src/endpoint.rs, quinn/src/incoming.rs
allows server to provide a preferred address to clients.
=> preferred address

quinn-proto/src/connection/datagrams.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/tests/mod.rs, quinn/src/connection.rs, quinn/src/tests.rs
Resolves https://github.com/quinn-rs/quinn/issues/1738
Not sure about the name.
=> add Connection::send_datagram_wait

.github/workflows/codecov.yml
This has been failing intermittently on main. Originally IIRC the token did not need to be passed for public repositories but this changed at some point in the past.
=> ci: pass codecov token explicitly

quinn/src/endpoint.rs
During a planned connection migration allow the client to receive
trafic via the old, abandoned socket until the first packet arrives on
the new socket.
---
I wrote this PR in a "cargo cult"-style without really knowing what I do. It seems to work as the client starts to acknowledge stream frames of the old path on the new path.  However, the server does not send stream frames right after it notices the new path even if  I modify the server to process acknowledgements when there's an outstanding path challenge [here](https://github.com/quinn-rs/quinn/blob/990203b4776c19a259e9b41fe6298ef0e17a2a08/quinn-proto/src/connection/mod.rs#L1431).  
Packet No. 1828, below, is the first packet arriving to the server on the new path.  The server sends path-challenges in 1891 (allowing linkability) and …
=> Socket rebind: drain old socket

quinn-proto/src/connection/datagrams.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/connection/streams/state.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/frame.rs, quinn-proto/src/packet.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn-udp/Cargo.toml, quinn-udp/src/fallback.rs, quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn-udp/src/windows.rs, quinn-udp/tests/tests.rs, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/lib.rs, quinn/src/runtime.rs, quinn/src/runtime/async_io.rs, quinn/src/runtime/tokio.rs, quinn/src/tests.rs
This allows outgoing data to parallelize perfectly. Initial informal testing suggests a performance improvement for bulk data, likely due to reduced allocation and cross-task messaging. A larger performance benefit should be expected for endpoints hosting numerous connections.
I'd left the original userspace-multiplexed transmit strategy in place for a long time because I assumed the UDP socket had a mutex-guarded send buffer, so leaning into task-parallelism for sending would just lead to contention. This turns out to be complete nonsense, at least on Linux: outgoing UDP datagrams are buffered by the kernel with dynamically allocated memory, and the primitive NIC queuing operation is apparently scalable, as borne out by empirical testing. The following minimal test scales almost linearly …
=> Transmit directly from connection tasks

quinn-proto/Cargo.toml, quinn-udp/Cargo.toml, quinn/Cargo.toml
I don't think describing these as "experimental" makes sense, and badges are pretty much deprecated:
> Note: [crates.io](https://crates.io/) previously displayed badges next to a crate on its website, but that functionality has been removed. Packages should place badges in its README file which will be displayed on [crates.io](https://crates.io/) (see [the readme field](https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field)).
https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section
=> Remove badges from metadata

quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/shared.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/src/endpoint.rs, quinn/src/incoming.rs, quinn/src/lib.rs
Closes #1820
The fix:
- Endpoint now maintains a slab with an entry for each pending Incoming to buffer received data.
- ConnectionIndex now maps initial DCID to that slab key immediately upon construction of Incoming.
- If Incoming is accepted, association is overridden with association with ConnectionHandle, and all buffered datagrams are fed to newly constructed Connection.
- If Incoming is refused/retried/ignored, or accepting errors, association and slab entry are cleaned up to prevent memory leak.
Additional considerations:
- The Incoming::ignore operation can no longer be implemented as just dropping it. To help prevent incorrect API usage, proto::Incoming is modified to log a warning if it is dropped without being passed to Endpoint::accept/refuse/retry/ignore.
- To help protect …
=> Fix race condition between 0-RTT and Incoming

quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/mutex.rs, quinn/src/runtime.rs, quinn/src/runtime/tokio.rs, quinn/src/work_limiter.rs
Allows end-to-end testing with a simulated flow of time, improving determinism and allowing extreme latencies to be modeled more easily. Inspired by @marcblanchet's multi-day experiments with simulated latencies for deep space networking.
=> Look up the time through trait Runtime

quinn-proto/src/connection/datagrams.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs
Noticed while exploring solutions to #1832. Also tossing in any other simple wins I stumble across.
=> Fix minor datagram send bugs

quinn-proto/src/connection/datagrams.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/tests/mod.rs
Fixes #1832.
~Still working on~ how to handle the case where a datagram is queued but won't fit with the current segment size. We need to either detect this in advance and finish the GSO batch before beginning another packet, or gracefully abandon packet assembly after failing to fit any frames. ~Currently leaning towards the latter.~ This will need careful testing.
~Also still TODO: End the GSO batch early if the amount of padding in the current packet would be excessive.~
=> Match GSO segment size to the first datagram, not the MTU

bench/src/lib.rs, perf/src/bin/perf_client.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/connection/streams/recv.rs, quinn-proto/src/connection/streams/send.rs, quinn-proto/src/connection/streams/state.rs, quinn-proto/src/lib.rs, quinn/benches/bench.rs, quinn/examples/client.rs, quinn/examples/server.rs, quinn/src/connection.rs, quinn/src/lib.rs, quinn/src/recv_stream.rs, quinn/src/send_stream.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
Followup to https://github.com/quinn-rs/quinn/pull/1699. `SendStream::finish` as a future has proved to be a footgun, so this converts it into a synchronous method, delegating "wait until received" duties to `SendStream::stopped`. We expect that to rarely be required in real applications, though it does come up several times in our tests where we specifically want some data to be received before we drop a connection or take a time measurement.
=> Make SendStream::finish synchronous

quinn/Cargo.toml
Required for `Endpoint::{client, server}` and various other helpers intended to simplify getting started.
`"ring"` was previously implied by `"tls-rustls"`, but that dependency was lost in the update to 0.23. We could add it back directly, but this seems more granular and future-proof.
=> Add ring to default features

quinn-proto/Cargo.toml, quinn-proto/src/connection/mod.rs, quinn-proto/src/tests/mod.rs
Fixes https://github.com/quinn-rs/quinn/issues/1850.
This bug caused occasional panics in debug builds in applications which send large application datagrams. The `debug_assert` did not account for the possibility of ACK-only packets arising due to queued non-ACK being too large to fit into the same packet, which became a problem when 6a8758ade2b81c2fc529a425722288dcca21130f introduced the possibility of ACK frames being sent alongside application data (such as large application datagrams) at times when it would be illegal to send an ACK frame spontaneously on its own.
=> Suppress ACK-only packet sanity-check when datagrams are queued

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/mtud.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/connection/paths.rs
=> Reduce black hole detection false positives

quinn-proto/src/connection/mod.rs, quinn-udp/src/lib.rs, quinn/src/connection.rs, quinn/src/tests.rs
Fixes https://github.com/quinn-rs/quinn/issues/1864 by establishing a single source of truth in quinn-udp.
=> Centralize and update `local_ip` platform support documentation

quinn-proto/src/connection/streams/mod.rs
Technically breaking, but spectacularly unlikely to break any real use, and arguably a mistake, so I think we can justify it.
=> Relax unnecessary unique borrow

quinn/src/recv_stream.rs
This was counting the number of bytes read in the current `poll` invocation, rather than the lifetime of the future.
Fixes #1861
CC @rom1v
=> Fix bytes read count in ReadExactError::FinishedEarly

quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn-udp/tests/tests.rs, quinn/src/tests.rs
This makes Quinn compile on openbsd and the test suite passes as well.
As far as I understand ECN is not supported as part of a control message on recvmsg.  So I disabled the ECN tests for it.
=> Support openbsd

quinn-proto/Cargo.toml, quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/crypto/rustls.rs, quinn-udp/Cargo.toml, quinn/Cargo.toml, quinn/src/connection.rs, quinn/src/lib.rs, quinn/src/recv_stream.rs, quinn/src/send_stream.rs
`hickory-proto::ProtoErrorKind`, which will include this, implements `Clone`.
Downstream PR: https://github.com/hickory-dns/hickory-dns/pull/2217.
=> proto: make NoInitialCipherSuite Copy

quinn-proto/src/connection/assembler.rs, quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/connection/streams/recv.rs, quinn-proto/src/connection/streams/state.rs
Fixes #1818 (probably). Second commit isn't necessary but feels a bit tidier.
=> Fix stopped recv stream flow control underflow under reordering

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/recv.rs, quinn-proto/src/connection/streams/state.rs
Noticed this looked like a redundant approximation while working on #1873. Careful review desired. The original logic here seems to date back to 2021 or earlier, but e.g. a3b35f93c25045b00849e846713cb9b94bc681c5 looks like a somewhat shorter-sighted hack around this same quirk. See commit description for additional rationale.
=> Simpler and more precise ID flow control update check in Chunks

quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/connection/streams/recv.rs, quinn/src/recv_stream.rs
Fixes #1870. I'm pretty sure I handled the state cleanup and flow control implications properly, but close review desired there all the same.
=> Introduce RecvStream::reset

fuzz/fuzz_targets/packet.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/packet.rs, quinn-proto/src/shared.rs
Context: #1860.
This PR did a bit more than just expose symbols to public, a trait `ConnectionIdValidator` was introduced, due to the fact that a QUIC Load balancer have to support different kind of Connection ID Schemes, per [QUIC-LB-DRAFT Secion 4.1]( https://www.ietf.org/archive/id/draft-ietf-quic-load-balancers-19.html#section-4.1). 
Also some documents was added to suppress the clippy warning after those symbol being made public.
=> proto: make PartialDecode API public

quinn-proto/src/config.rs, quinn-proto/src/packet.rs, quinn-proto/src/shared.rs
Groundwork to eventually make `ConnectionIdGenerator` require or somehow expose `ConnectionIdParser`, towards eventually supporting variable-length CIDs in Quinn. Further changes in this direction will be breaking so we shouldn't pursue them immediately, but getting this in before the next release will reduce the magnitude of that breakage.
CC @thynson
=> Make ConnectionIdParser object-safe, and accept trait object impls

quinn/examples/insecure_connection.rs
Fixes #1881.
We could also call `CryptoProvider::get_default` lazily, but that would be more work to adapt for users who want a non-default provider, and more verbose besides.
=> Fix panic in example due to unset default crypto provider

quinn-proto/src/endpoint.rs, quinn/src/tests.rs
Noticed some fishy business when working on #1879.
=> Fix zero-length connection IDs

quinn-udp/src/cmsg/mod.rs, quinn-udp/src/cmsg/unix.rs, quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn-udp/tests/tests.rs, quinn/src/tests.rs
This adds support for NetBSD.  As mentioned in the commit, it does not support DONTFRAG or ECN for IPv4, but does for IPv6.  It has recvmmsg so I implemented that recv branch.
Also included is a fix for OpenBSD which also does not have IP_DONTFRAG for IPv4.  Not sure how that slipped into #1863 / 98d8513e656467b32898402a372e33ea2108c478.
I have tested this on all of OpenBSD, NetBSD and FreeBSD and all pass the test suite now.
=> Add support for NetBSD, fix OpenBSD

quinn/src/recv_stream.rs, quinn/src/send_stream.rs
If a connection is lost before a stream becomes closed, these would otherwise never complete.
=> Resolve stopped/received_reset futures on lost connections

quinn-proto/src/config.rs
Per discussion in Discord [[link]](https://discord.com/channels/976380008299917365/1063547094863978677/1249100084117770272), the actual extent to which setting ack_frequency_config to `None` disables the acknowledgement frequency extension is less than the documentation seems to imply. An endpoint with the ack frequency config set to `None` will still:
- advertise support for the extension by populating the `min_ack_delay` field of its transport parameters with `Some`
- process ACK_FREQUENCY and IMMEDIATE_ACK frames if it receives them
- send IMMEDIATE_ACK frames if the peer advertises support for the extension
The only thing it will not do is send the peer an ACK_FREQUENCY frame.
This PR updates the docs to reflect the behavior more closely.
=> docs(quinn): Clarify effects of setting AckFrequencyConfig

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/state.rs
Minor optimization to reduce outgoing traffic when receiving large numbers of streams. Mirrors existing logic for data flow control, e.g.
https://github.com/quinn-rs/quinn/blob/7b97a3fbd875903568249862f6d2ef4b7d30cfe8/quinn-proto/src/connection/streams/state.rs#L849-L855
=> Only send MAX_STREAMS when >1/8 of flow control window is consumed 

Cargo.toml, bench/Cargo.toml, perf/Cargo.toml, quinn-proto/Cargo.toml, quinn-udp/Cargo.toml, quinn/Cargo.toml
Various `quinn*` crates depend on `tracing`. `tracing` in its default feature set includes `tracing-attributes` in order to expose `#[instrument]` procedural macro in `tracing::instrument`.
None of `quinn*` make use of the `#[instrument]` macro. Thus the `tracing-attributes` dependency is unused.
To remove the dependency from the tree, this commit:
1. Restricts `tracing`'s `features` to `std`, effectively removing the `attributes` feature.
2. Consolidates the various `tracing*` imports across `quinn*` crates into workspace dependencies.
Let me know if you don't want to use workspace dependencies?
---
Context:
- Mozilla is currently using NSPR to send and receive QUIC datagrams.
- There is an ongoing effort to replace NSPR with `quinn-udp`, see …
=> fix: remove unused dependency tracing-attributes

quinn-proto/src/config.rs, quinn-proto/src/endpoint.rs
=> proto: make initial destination cid configurable 

quinn-proto/src/config.rs, quinn-proto/src/endpoint.rs
@Ralith this is based on your [suggestion](https://discord.com/channels/976380008299917365/1063547094863978677/1247827802896470046) from a while ago
=> Allow configuring rng seed through `EndpointConfig`

quinn/src/connection.rs
Fixes #1904. CC @gretchenfrage for testing.
=> Wake blocked streams on 0-RTT rejection

quinn-proto/Cargo.toml, quinn/Cargo.toml
I checked all uses and I don't think this appear in our public API at all.
=> Upgrade to rustc-hash 2

quinn-proto/src/crypto/rustls.rs, quinn/src/connection.rs, quinn/src/send_stream.rs
I had a hard time getting 0-RTT actually working in practice. It escalated to me forking rustls so I could put in a bunch of print statements. Although I did find the 0-rtt tests, there were some subtle enough pitfalls that I didn't notice the relevant ways my attempts were diverging.
In hopes of improving understandability and discoverability of this, this PR adds notes about these pitfalls to some of the doc comments, and also largely rewrites the doc comment for `Connecting::into_0rtt` to make its behavior more clear,  especially across various edge cases.
This PR does not change any code or APIs.
=> Revise and add additional 0-rtt doc comments

quinn-udp/src/unix.rs
`sendmmsg` has been dropped in https://github.com/quinn-rs/quinn/commit/ee0882657a16a8ffd7ff5844f355caca519e63ce.
This commit removes left-over references to sendmmsg.
=> docs: remove reference to sendmmsg

quinn-proto/src/connection/mtud.rs
Fixes https://github.com/quinn-rs/quinn/issues/1889.
On careful examination, I think @tthebst's instinct was correct: the assert was fundamentally wrong, and our logic works as intended without it. I've hence removed the assert and attempted to better document why this is okay, but please double-check my thinking.
=> Fix debug assert with reordered ACKs

Cargo.toml, quinn-udp/Cargo.toml, quinn/Cargo.toml, quinn/src/endpoint.rs, quinn/src/tests.rs
Following a conversation in the crate discord [[link]](https://discord.com/channels/976380008299917365/1063547094863978677/1230352131924688926) in which @Ralith mentioned:
> maybe `Endpoint::client` should do this by default? I suspect real applications inevitably need to use a lower level constructor, but it's one less footgun
This PR makes makes `quinn::Endpoint::client` use `socket2` to automatically try to set `IPV6_V6ONLY` to false if binding to a V6 address. Modifies the documentation to match. If the call to `set_only_v6` errors, it logs the error as a warning, but proceeds with the rest of the `client` method anyways.
Removes the OS-based gating from `quinn`'s `tests::echo_dualstack` test. Unfortunately(?), that tests seems to work on main for me anyways on my current system, so …
=> quinn: Make `Endpoint::client` dual-stack V6 by default

quinn-udp/Cargo.toml, quinn-udp/benches/throughput.rs
This commit adds a basic benchmark, measuring the time to transfer 10 MiB with and without GSO on localhost.
```
gso_false/throughput    time:   [23.455 ms 25.230 ms 27.004 ms]
thrpt:  [370.31 MiB/s 396.35 MiB/s 426.35 MiB/s]
gso_true/throughput     time:   [1.0168 ms 1.1239 ms 1.2496 ms]
thrpt:  [7.8153 GiB/s 8.6889 GiB/s 9.6044 GiB/s]
```
```
$ cat /proc/cpuinfo
model name      : 12th Gen Intel(R) Core(TM) i9-12900HK
```
---
Given various optimizations for `localhost` traffic on Linux, we were wondering whether GSO actually has  an impact on `localhost`. According to this benchmark: Yes it does.
For what a `localhost` network benchmark is worth, here it is. Feel free to close in case it isn't useful.
=> bench(udp): measure non-GSO & GSO on localhost

quinn/src/lib.rs
ConnectionStats and ResetError are now reexported for use with the public interface, they weren't before.
Respecfully, please take better care of your libeary. I encountered these issues and thought I had something wrong because surley something as obvious as not reexporting your own types would have been cought and fixed before publishing the latest release of quinn, but I guess not. But regaurdless, there it is, it's fixed.
=> Fix lack of reexport of ConnectionStats and ResetError

Cargo.toml, quinn-proto/Cargo.toml, quinn-udp/Cargo.toml, quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn/Cargo.toml
Alternative to https://github.com/quinn-rs/quinn/pull/1921.
Implementation of @Ralith suggestion in https://github.com/quinn-rs/quinn/pull/1921#issuecomment-2237230567.
Not breaking `quinn-udp`. I.e. only bumping patch version to `v0.5.3`.
=> [non-breaking] deps(udp): make tracing optional and add optional log

quinn-udp/Cargo.toml, quinn-udp/src/windows.rs
8712910a made `tracing` optional and added optional `log`, but forgot to update `quinn-udp/src/windows.rs`. This commit fixes the oversight and bumps the `quinn-udp` version to `v0.5.4`.
---
Discovered in https://github.com/mozilla/neqo/pull/2002.
I assume that this is not an issue for most `quinn` users as they don't run `quinn-udp` with `default-features = false"`.
I am sorry for the oversight. I can look into a GitHub CI workflow that prevents this in the future tomorrow.
=> fix(udp): feature flag tracing in windows.rs

quinn-proto/src/config.rs
Recommended in RFC9308 § 3.2 for use on the public internet when a NAT may be on the path.
=> Raise default idle timeout to 30 seconds

quinn-proto/src/connection/mod.rs, quinn-proto/src/packet.rs
Attempting to parse frames from these non-frame-bearing packets was responsible for some spurious connection failures in interop testing under high packet loss.
=> Discard pre-handshake packets after the handshake

quinn/src/endpoint.rs
The `socket2` imports are only used by the feature flagged `client` function. Feature flag the imports as well.
Avoids the following warning:
```
--> quinn/src/endpoint.rs:28:15
|
28 | use socket2::{Domain, Protocol, Socket, Type};
|               ^^^^^^  ^^^^^^^^  ^^^^^^  ^^^^
|
= note: `#[warn(unused_imports)]` on by default
```
=> chore(quinn): feature flag socket2 imports

Cargo.toml, quinn-proto/Cargo.toml, quinn-udp/Cargo.toml, quinn/Cargo.toml
Follow-up to suggestion in https://github.com/quinn-rs/quinn/pull/1939#discussion_r1690309715. //CC @Ralith
Feel free to close if not needed.
=> refactor: move rust-version to workspace Cargo.toml

Cargo.toml, quinn-proto/Cargo.toml, quinn-udp/Cargo.toml, quinn/Cargo.toml
Follow-up to https://github.com/quinn-rs/quinn/pull/1940.
=> chore: move common package data to workspace Cargo.toml

quinn-proto/src/endpoint.rs, quinn/src/endpoint.rs
In Anza, we need to get more insight into the resources being used by quinn in servicing quic handshakes. This PR seeks to add an initial interface to the Endpoint struct to allow for getting more detailed stats than just the open connections, and some initial data relevant to the handshakes. On a side note to the Quinn devs, if there is a good way to support getting the current number of open handshakes, we would be interested in know it. Currently, it seems that the Endpoint is not signaled when a Connecting future finishes, and to add such an event would require some refactoring, not to mention handling an extra event, locking, etc.
=> Endpoint stats interface

quinn-proto/src/connection/mod.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/src/connection.rs
This is convenient for some client authentication use cases, and for tests to know when it's safe to force a key update.
=> Expose the Handshake Confirmed state

quinn-proto/src/endpoint.rs, quinn-proto/src/tests/mod.rs
This could also cause other packets received before the server accepts the connection to be lost.
Noticed while checking some unrelated assumptions.
=> Fix incorrect initial DCID indexing on retried connections

quinn-proto/src/connection/packet_builder.rs
This unwrap can be hit by a bad custom `Session` implementation. Add the message suggested in #1928 give a hint as to what went wrong.
Fixes #1928.
=> Add expect message to unwrap in PacketBuilder

quinn-proto/src/connection/mod.rs
This condition can arise due to packet loss or reordering.
This reverts commit 470b2134c4cb54c18f6ae858de2a25005a97c255.
=> Revert "proto: yield transport error for Initial packets with no CRYPTO"

quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn-udp/src/windows.rs
Add `log` facade that either dispatches to `tracing` or `log`, or to a no-op implementation.
As suggested in https://github.com/quinn-rs/quinn/pull/1932#pullrequestreview-2192415008.
=> refactor(udp): introduce log facade

Cargo.toml, quinn-proto/Cargo.toml, quinn-udp/Cargo.toml, quinn/Cargo.toml
After publishing quinn-proto 0.11.4, building downstream crates (even quinn itself) fails with:
```
error: failed to download `quinn-proto v0.11.4`
Caused by:
unable to get packages from source
Caused by:
failed to parse manifest at `/home/ralith/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quinn-proto-0.11.4/Cargo.toml`
Caused by:
error inheriting `lints` from workspace root manifest's `workspace.lints`
Caused by:
failed to find a workspace root
```
This reproduces on cargo nightly, 1.80, and 1.79. quinn-proto 0.11.4 has been yanked.
=> No workspace lints

quinn-proto/Cargo.toml, quinn-proto/src/connection/mod.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn/src/connection.rs
This was an unintended breaking change. We can bring it back in the next major release, but there's some bugfixes I'd like to get into 0.11 first. Alternatively, we could branch 0.11 off before this was committed and cherry-pick everything into it.
This reverts commit 391824b9df07973b0ce4f90794820406c0717c81.
=> Revert "Expose the Handshake Confirmed state"

quinn-proto/src/transport_parameters.rs
This was updated in the draft alongside the frame ID. Currently causing some interop failures.
=> Fix min_ack_delay transport parameter ID

quinn/src/connection.rs
In the new API the finish call no longer returns a future and to achieve the same behaviour the future from stopped needs to be used.
=> Update Connection::close docs for new API

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/stats.rs
* For debugging and performance analysis purposes we need to inspect path MTU discovered by the connection.
* The commit exposes current path MTU discovered in connection stats.
=> exposes current path MTU discovered in connection stats

.github/workflows/rust-android-run-tests-on-emulator.sh, .github/workflows/rust.yml, quinn/src/tests.rs
Runs unit tests on Android emulator for both `x86` and `x86_64`.
---
Tracking issue: https://github.com/quinn-rs/quinn/issues/1778
Foundation to test https://github.com/quinn-rs/quinn/issues/1947.
=> ci: add Android job

Cargo.toml
It's required for the `vacant_key` function to exist.
See https://github.com/quinn-rs/quinn/blob/1e48a703d5a7d7c7594acca2068cd6bd68e224c5/quinn-proto/src/endpoint.rs#L407
See https://github.com/tokio-rs/slab/blob/f7b621f6cf2bc84f32214029b32d587d18277e3d/CHANGELOG.md?plain=1#L16-L18
=> Require slab `0.4.6` or higher

quinn-udp/Cargo.toml, quinn-udp/src/unix.rs, quinn-udp/tests/tests.rs
This allows build on Solaris. Unfortunately at this moment tests are failing like this:
```
Running unittests src/lib.rs (target/debug/deps/quinn-94a8797a83ab1c78)
running 18 tests
test work_limiter::tests::limit_work ... ok
test tests::local_addr ... ok
test tests::close_endpoint ... ok
test tests::handshake_timeout ... ok
test tests::zero_rtt ... FAILED
test tests::export_keying_material ... FAILED
test tests::rebind_recv ... FAILED
test tests::stress_stream_receive_window ... FAILED
test tests::echo_v4 ... FAILED
test tests::stress_both_windows ... FAILED
test tests::read_after_close ... FAILED
test tests::echo_v6 ... FAILED
test tests::stress_receive_window ... FAILED
test tests::echo_dualstack ... FAILED
test tests::ip_blocking ... FAILED
test …
```
=> Allows build on Solaris (#1877)

.github/workflows/rust.yml
This pull request adds a GitHub job, testing all feature permutations (including optional dependencies), across all default workspace members. It uses [`cargo hack`](https://github.com/taiki-e/cargo-hack).
This workflow would for example have caught the following recent bugs before landing in `main`:
- https://github.com/quinn-rs/quinn/pull/1932
- https://github.com/quinn-rs/quinn/pull/1933
Right now this job takes 5m 1s on Ubuntu, 4m 42s on MacOS  and 8m 29s Windows. In case you consider that too long, we could drop `--optional-deps` or exclude some features (`--exclude-features`).
=> ci(rust.yml): add job testing feature permutations

.github/workflows/rust-android-run-tests-on-emulator.sh, .github/workflows/rust.yml
When extracting the emulator script into a separate file, the `matrix.target` substitution wasn't replaced with an environment variable.
Follow-up to https://github.com/quinn-rs/quinn/pull/1950.
Also the `ecn_*` unit tests are failing with any Android API version < v26 with:
```
2024-08-22T14:41:30.636494Z  WARN quinn_udp: sendmsg error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, Transmit: { destination: 127.0.0.1:50196, src_ip: None, enc: Some(Ect0), len: 5, segment_size: None }
```
=> fix(.github/android): pass matrix.target and increase api to v26 

quinn-proto/src/endpoint.rs, quinn-proto/src/tests/mod.rs
This regressed in 83111249e829a2f367e15376b207d787473b88c2.
=> Fix and test validation of IDCID length

quinn/Cargo.toml
Now crates like `wtransport`, that only depend on `quinn` and use `quinn-proto` via `quinn::proto`, can point to a [patched](https://github.com/quinn-rs/quinn/security/advisories/GHSA-vr26-jcq5-fjj8) version.
=> Version bump `quinn` to enforce patched `quinn-proto`

quinn-udp/Cargo.toml, quinn-udp/src/unix.rs
This reverts commit e6f184489e703bcf70850f99373c88746c250662.
e6f18448 called `sendmmsg` and `recvmmsg` through `libc::syscall` instead of `libc::sendmmsg` and `libc::recvmmsg`, thus preventing linking issues on old Android systems where `libc::sendmmsg` and `libc::recvmmsg` isn't available.
In https://github.com/quinn-rs/quinn/issues/1503#issuecomment-2285962727 the suggestion was made to no longer support these old Android systems (API level 16).
This commit reverts e6f18448. Given that `sendmmsg` support was previously dropped in ee088265, only the `recvmmsg` calls are reverted.
---
Alternative to https://github.com/quinn-rs/quinn/pull/1964. Given the additional simplicity, my preference is for this change.
=> Revert "Implement fallback for `sendmmsg` and `recvmmsg`"

quinn-proto/src/endpoint.rs, quinn/src/incoming.rs
Expose the original dest cid, which is generated by client when connecting.
The use case is described in #1896, and it would be convenient to expose it for logging and e2e testing.
=> Expose orignial dest cid

.github/workflows/rust.yml, Cargo.toml, deny.toml, quinn-proto/Cargo.toml, quinn-proto/src/cid_generator.rs, quinn-proto/src/config.rs, quinn-proto/src/crypto.rs, quinn-proto/src/crypto/ring.rs, quinn-proto/src/crypto/ring_like.rs, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/lib.rs, quinn-proto/src/packet.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn-proto/src/token.rs, quinn/Cargo.toml, quinn/examples/common/mod.rs, quinn/src/endpoint.rs, quinn/src/lib.rs, quinn/src/tests.rs, quinn/tests/many_connections.rs
Still needs a CI workflow to ensure that this actually works.
=> Enable use of aws-lc-rs instead of ring

quinn/src/lib.rs
This is retunred by the public API but was not being provided.  This export this publicly.
Normally the compiler catches these kinds of errors, possibly it is confused by pin_project.
=> Export SendDatagram struct to the public API

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/recv.rs, quinn-proto/src/lib.rs
closes #1703
closes #1531 
cc @djc
=> remove panic-on-drop in `quinn_proto::Chunks`

quinn-proto/src/connection/datagrams.rs
=> proto: update DatagramState::outgoing_total on drop_oversized()

quinn-udp/src/unix.rs
Just enable the same code blocks than on iOS.
=> Add visionOS support

quinn-proto/src/connection/mod.rs
=> #2008: Make max_idle_timeout negotiation commutative.

quinn-proto/src/config.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/connection/streams/state.rs
Solana leader slots are 400ms. When sending and ingesting transactions, minimizing latency is therefore key. Quinn currently tries to implement fairness when writing out send streams, which is a good default, but not great for our use case.
We want to pack as many transactions in a datagram as possible, without any fragmentation if not at the very end if a transaction doesn't fit in the remaining space. In that case, we want the end (fin) of the transaction to come _immediately after_ in order to minimize latency. The current round-robin algorithm doesn't allow this, and in fact leads to very high latency if the stream receive window is large.  
This PR tries to address this problem. It introduces a `TransportConfig::send_fairness(bool)` config. When set to false, streams are still …
=> Add alternative - unfair but lower latency - send stream scheduling strategy

.github/workflows/rust.yml, quinn-proto/Cargo.toml, quinn/Cargo.toml
Adds support for aws-lc-rs FIPS mode using a feature flag in quinn and quinn-proto.
=> feat(quinn, quinn-proto): add aws-lc-rs-fips feature flag

quinn-proto/src/connection/assembler.rs, quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/connection/streams/recv.rs, quinn-proto/src/connection/streams/state.rs
The solana blockchain uses uni streams to deliver transactions. A transaction can be up to 1232 bytes, each transaction is a stream. A validator accepts thousands of connections and each connection sends millions of streams.
The Solana validator Agave uses Quinn for transaction processing, with jemalloc as the global allocator. We're encountering an issue where, due to the high volume of allocations while ingesting transactions, jemalloc struggles during network spikes. It blows out the tcache, spends excessive time managing arenas, allocating large amounts of memory, and then attempting to free it during decay. This results in a significant amount of time spent on syscalls and arena locking, leading to contention and random stalls in other threads.
Quinn is one of the largest source of …
=> Reduce memory allocations on servers that process a large number of streams

quinn-proto/Cargo.toml, quinn-proto/src/crypto/rustls.rs, quinn-proto/src/packet.rs, quinn-proto/src/tests/mod.rs, quinn/Cargo.toml, quinn/examples/connection.rs, quinn/examples/insecure_connection.rs, quinn/examples/single_socket.rs, quinn/src/tests.rs
In the current Rust editions, if a dependency is declared as optional and it also exists a feature with the same name, `dep:name` will activate both the feature and the optional dependency.
That is the case for the `rustls` feature, so sadly 
```toml
rustls-aws-lc-rs = ["dep:rustls", "rustls/aws-lc-rs", "aws-lc-rs"]
```
will also activate the `rustls` feature, which also activates `ring`.
There is a zulip discussion about this surprising behavior [here](https://rust-lang.zulipchat.com/#narrow/channel/246057-t-cargo/topic/Odd.20cargo.20resolver.20behavior/near/449102225).
Hopefully, in Rust 2024 edition, with [this change](https://doc.rust-lang.org/edition-guide/rust-2024/cargo-remove-implicit-features.html), the behavior will be less surprising.
The PR introduce a breaking change, but as …
=> fix `rustls-aws-lc-rs` feature

.github/workflows/rust.yml, quinn-udp/Cargo.toml, quinn-udp/benches/throughput.rs
- Benchmark all permutations of GSO, GRO and `recvmmsg`.
- Add support for all platforms.
- Add test-run (i.e. `cargo test --benches`, single execution in debug mode) to CI.
=> bench(udp): run GSO, GRO and recvmmsg permutations

quinn-udp/Cargo.toml, quinn-udp/benches/throughput.rs, quinn-udp/build.rs, quinn-udp/src/cmsg/unix.rs, quinn-udp/src/unix.rs
This uses Apple's private [`sendmsg_x`](https://github.com/apple-oss-distributions/xnu/blob/94d3b452840153a99b38a3a9659680b2a006908e/bsd/sys/socket.h#L1457-L1487) and [`recvmsg_x`](https://github.com/apple-oss-distributions/xnu/blob/94d3b452840153a99b38a3a9659680b2a006908e/bsd/sys/socket.h#L1425-L1455) system calls for multi-packet UDP I/O.
CC @mxinden
=> feat: Faster UDP/IO on Apple platforms

quinn-udp/src/fallback.rs, quinn-udp/src/unix.rs, quinn-udp/src/windows.rs
=> feat: introduce `UdpSocketState::try_send` APIs

quinn-proto/src/crypto/rustls.rs
As title.
I am not totally convinced by that `.expect("cipher is negotiated")`. 
It makes sense to me: as AFAIK reaching that point always implies the cipher is negotiated, but I might have missed a edge scenario
=> crypto: expose negotiated_cipher_suite in the hadshake data

Cargo.toml
`quinn-udp` depends on the `windows-sys` crate, more specifically `windows_sys::Win32::Networking::WinSock`:
https://github.com/quinn-rs/quinn/blob/a5d9bd1154b7644ff22b75191a89db9687546fdb/quinn-udp/src/cmsg/windows.rs#L6
https://github.com/quinn-rs/quinn/blob/a5d9bd1154b7644ff22b75191a89db9687546fdb/quinn-udp/src/windows.rs#L13
Previously `quinn-udp` was using `windows-sys` `v0.52`. https://github.com/quinn-rs/quinn/pull/1960 updated `quinn-udp` to `v0.59`. Note that `windows-sys` went straight from `v0.52` to `v0.59`. There are no versions in between.
`quinn-udp` does not depend on any `windows-sys` `v0.59` features. In other words, it can support both `windows-sys` `v0.52` and `v0.59`.
https://github.com/microsoft/windows-rs/releases/tag/0.59.0
This commit allows downstream users of …
=> feat(quinn-udp): support both windows-sys v0.52 and v0.59

quinn-udp/Cargo.toml
Would you mind cutting a new release of `quinn-udp`?
In addition to https://github.com/quinn-rs/quinn/pull/2021/, a patch release would allow us to easily experiment with https://github.com/quinn-rs/quinn/pull/1993.
=> chore(quinn-udp): increase crate patch version to v0.5.6

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/varint.rs
Fixes the failure identified in #2020.
=> Fix header space check

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/mtud.rs, quinn-proto/src/connection/paths.rs
This gives the proto state the ability to be externally notified about network path changes it might not be aware off.  In this case it will re-set the RTT, Congestion Controller and MTU settings to the initial states based on the TransportConfig.
This addresses the quinn-proto part of #2018.
=> feat(quinn-proto): Allow notifying of network path changes

.cargo/config.toml, .github/workflows/rust.yml, Cargo.toml, quinn-proto/Cargo.toml, quinn-proto/src/cid_generator.rs, quinn-proto/src/config.rs, quinn-proto/src/congestion.rs, quinn-proto/src/congestion/bbr/bw_estimation.rs, quinn-proto/src/congestion/bbr/mod.rs, quinn-proto/src/congestion/cubic.rs, quinn-proto/src/congestion/new_reno.rs, quinn-proto/src/connection/ack_frequency.rs, quinn-proto/src/connection/cid_state.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/mtud.rs, quinn-proto/src/connection/pacing.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/connection/packet_crypto.rs, quinn-proto/src/connection/paths.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/connection/stats.rs, quinn-proto/src/connection/timer.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn-proto/src/shared.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/util.rs, quinn-proto/src/token.rs
- Use `web_time` dependency instead of `std::time` & re-export `Instant`, `Duration`, `SystemTime` and `UNIX_EPOCH` in `lib.rs` so imports are simpler
- Adjust imports to use `crate::{Instant, Duration, ...}` instead of `std::time::{Instant, Duration, ...}`
- Added `wasm-bindgen-test` to enable running tests from a Wasm build
- Added a CI task to test quinn-proto tests in Wasm with node.js
```sh
$ cargo install wasm-bindgen-cli
$ cargo test -p quinn-proto --target wasm32-unknown-unknown
```
<details>
<summary>Old open questions, now resolved</summary>
- Should the added code/dependencies additionally be feature-gated?
I personally don't think so. As far as I know, there's practically no one asking for wasm32-unknown-unknown compilability who isn't targeting nodejs/browsers/cloudflare …
=> feat(quinn-proto): Make compilable in wasm32-unknown-unknown and run wasm tests in CI

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/state.rs, quinn-proto/src/frame.rs, quinn-proto/src/lib.rs, quinn-proto/src/transport_error.rs, quinn/src/lib.rs
Closes #2012 
In that issue, we noted that there doesn't seem to exists any automated tooling to automatically detect types from external crates which are visible in a crate's public API but which the crate does not re-export. So I went ahead and attempted to create such a tool: [[cargo should-be-public-checker]](https://github.com/gretchenfrage/cargo-should-be-public-checker). It's still pretty crude right now but it was enough to detect a handful of items that I confirmed were missing reexports in Quinn and proto. That said, it's possible that there are some things it missed.
should-be-public-checker output for quinn-proto (on main):
```
visible but not importable:
- quinn_proto::Chunk::bytes::Bytes
- quinn_proto::ClientConfig::with_root_certificates::RootCertStore
- …
```
=> Fix missing re-exports

.github/workflows/rust.yml, quinn-udp/src/unix.rs
this fixes https://github.com/quinn-rs/quinn/issues/2033
=> quinn-proto: fix unable to build for netbsd (the name "recv" is defined multiple times)

.github/workflows/rust.yml
We've previously had this workaround in CI for `cc` versions between version `1.1.32` and `1.1.37` which broke the `ring` build for wasm32-unknown-unknown in github actions.
Version `1.2.0` is now released and doesn't break `ring` anymore.
Related PRs:
- https://github.com/rust-lang/cc-rs/pull/1284
- https://github.com/rust-lang/cc-rs/pull/1286
=> chore(ci): Remove workaround for broken `cc` version

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/connection/spaces.rs
Fixes another bug found in #2020.
When a datagram is a loss probe, it must be at most 1200 bytes. This limit must be accounted for before we judge whether there's enough space to coalesce another packet.
=> Account for probe size limits before coalescing

quinn-udp/src/unix.rs, quinn-udp/src/windows.rs
This PR is a proposal to remove the two `ERROR` logs that we currently have in `quinn-udp`. Rationale is explained separately in each commit message.
=> chore(quinn-udp): tweak log levels

.github/workflows/rust.yml, README.md
Djc bumped MSRV to 1.70 in #1939 in July. However, the README still claims that the MSRV is 1.66. This PR fixes the README and adds a note to the CI config.
=> docs: Correct MSRV in README

.github/workflows/rust.yml, Cargo.toml, README.md
This is the MSRV current rustls has adopted (on the back of current env_logger requiring 1.71).
=> Bump MSRV to 1.71

quinn-proto/src/transport_parameters.rs
I propose to remember the order in which write of the params should be performed when `TransportParameters` are crated. Then this order is used to write to wire format.
PR currently split into two commits:
1. Do the permutation using hard-coded IDs of prams;
2. Some refactoring to store the IDs into enum.
=> #2057: Shuffle outgoing transport parameters.

quinn-udp/src/unix.rs
Both resolve to `3`, thus not an actual bug.
Caught thanks to @marten-seemann's [DF draft](https://github.com/marten-seemann/draft-seemann-tsvwg-udp-fragmentation).
=> fix(udp): use IPV6_PMTUDISC_PROBE instead of IP_PMTUDISC_PROBE on v6

quinn-udp/src/unix.rs
With https://github.com/quinn-rs/quinn/pull/2017, the concrete `send` implementations per platform are supposed to propagate `io::Error`s. Those errors are then eiter logged and dropped in `UdpSocketState::send` or further propagated in `UdpSocketState::try_send`.
The `fast_apple` `send` implementation added in
https://github.com/quinn-rs/quinn/pull/1993 does not follow this pattern.
This commit adjusts the `fast_apple` implementation accordingly.
=> fix(udp): propagate error on apple_fast

quinn-udp/src/unix.rs
On Linux and Android, `quinn-udp` will retry a send on `ErrorKind::Interrupted`:
https://github.com/quinn-rs/quinn/blob/e318cc4a80436fd9fa19c02886d682c49efca185/quinn-udp/src/unix.rs#L305-L312
Do the same on all other unix platforms.
=> fix(udp): retry on ErrorKind::Interrupted

quinn/src/runtime/async_io.rs
This PR replaces Quinn's use of `Async::new` with [`Async::new_nonblocking`](https://docs.rs/async-io/latest/async_io/struct.Async.html#method.new_nonblocking), a constructor introduced in version 2.0 of `async_io`, which assumes the socket has already been put into non-blocking mode. For Quinn this is indeed the case, as `quinn_udp` configures the socket as non-blocking already.
As for the Tokio runtime implementation, that uses [`UdpSocket::from_std`](https://github.com/quinn-rs/quinn/blob/31a0440009afd5a7e29101410aa9d3da2d1f8077/quinn/src/runtime/tokio.rs#L33), which [already makes this assumption](https://docs.rs/tokio/latest/tokio/net/struct.UdpSocket.html#notes).
=> Use `Async::new_nonblocking` to avoid redundant socket configuration

Cargo.toml, quinn-udp/Cargo.toml, quinn-udp/src/windows.rs
On Windows on ARM with Windows Subsystem for Linux (WSL) `WSA_RECVMSG` does not return the segment size of coalesced UDP datagrams. See https://github.com/quinn-rs/quinn/issues/2041 for details.
While lacking a fix for the root cause, don't enable URO, i.e. don't coalesce UDP datagrams, on Windows on ARM.
=> fix(udp): do not enable URO on Windows on ARM

quinn-proto/src/coding.rs, quinn-proto/src/lib.rs
It turned out currently the `coding` mod is already public, simply hidden from the docs.
It seems to be the minimal change to allow using this functionality for `VarInt` is to document it and not hide it.
Fixes #1277
=> feat(quinn-proto): unhide `quinn_proto::coding`

.github/workflows/rust.yml, quinn/src/tests.rs
Per [Discord messages](https://discord.com/channels/976380008299917365/1063547094863978677/1310833978957234228), ignores long-running stress tests by default.
With this commit, `cargo test` runs in less than 2 seconds on my machine, whereas on main it takes over 60.
=> tests(quinn): Ignore stress tests by default

quinn/src/connection.rs, quinn/src/recv_stream.rs, quinn/src/send_stream.rs
Various future types had boilerplate `must_use` annotations. Rust now does that automatically for futures. Removes all of them that didn't have some more specific message.
Noted in #1757.
=> quinn: Remove obsolete must_use for futures

quinn-proto/src/config/mod.rs, quinn-proto/src/endpoint.rs, quinn/src/incoming.rs
RFC 9000 presents some unfortunate complications to naming things. It introduces a concept of a "token" that may cause a connection to be validated early. In some ways, these tokens must be treated discretely differently based on whether they originated from a NEW_TOKEN frame or a Retry packet. It also introduces an unrelated concept of a "stateless reset token".
If our code and documentation were to constantly use phrases like "token originating from NEW_TOKEN frame," that would be extremely cumbersome. Moreover, it would risk feeling like leaking spec internals to the user.
As such, this commit tries to move things towards the following naming convention:
- A token from a NEW_TOKEN frame is called a "validation token", or "address validation token", although the shorter form should be …
=> Adjust terminology regarding tokens

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/endpoint.rs
Some notable differences from how I approached this in #1912:
- Calling it `ConnectionSide` rather than `SideState`
- Call the field `Connection.side` rather than `Connection.side_state`. The causes changes to be necessary to a different, but smaller set of lines of code, since now every existing instance of `self.side.is_client()` or `self.side.is_server()` just works as-is. And it's terser.
- Offloaded more logic to methods on `SideArgs` and an `impl From<SideArgs> for ConnectionSide`, in the interest of taking some complexity load off of `Connection::new`, which is already over 100 lines.
=> proto: Connection side enum

quinn-proto/src/config/mod.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/lib.rs, quinn/src/lib.rs
- Adds trait SystemTimeClock
- Adds default implementation RealSystemTimeClock
- Adds ServerConfigParameter system_time_clock: Arc<dyn SystemTimeClock>
- Replaces all SystemTime::now calls in proto with SystemTimeClock.now calls (there were 2)
This is a backwards-compatible change.
=> Make SystemTime mockable via object

quinn-udp/src/unix.rs
No need to `return Ok(())` early, given the final `return Ok(())` at the end of the function. Makes it consistent with other `send` implementations. Makes it consistent with early returns being errors only.
Follow-up to https://github.com/quinn-rs/quinn/pull/2074#discussion_r1863944160. I have not yet been able to come up with a better refactoring.
=> refactor(udp): remove unnecessary `return`

.github/workflows/rust-android-run-tests-on-emulator.sh, .github/workflows/rust.yml, quinn-udp/Cargo.toml, quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn-udp/tests/tests.rs
Android API level < 26 does not support the `libc::IP_TOS` control message. `sendmsg` calls with `libc::IP_TOS` return `libc::EINVAL`.
https://github.com/quinn-rs/quinn/pull/1516 added a fallback, not setting `libc::IP_TOS` on consecutive calls to `sendmsg` after a failure with `libc::EINVAL`. The current datagram would be dropped. Consecutive datagrams passed to `sendmsg` would succeed as they would be sent without `libc::IP_TOS` through the fallback.
Instead of dropping the first datagram on `libc::EINVAL`, this commit adds a retry for it without `libc::IP_TOS`.
This is e.g. relevant for Neqo. When establishing a QUIC connection, dropping the first datagram [delays connection establishment by 100ms](https://github.com/mozilla/neqo/blob/3001a3a56f2274eaafaa956fb394f0817f526ae7/neqo-transp …
=> fix(udp): retry send on first EINVAL

Cargo.toml, quinn-udp/Cargo.toml, quinn-udp/src/windows.rs
We have multiple bug reports for GRO (i.e. URO) on Windows with no solution in sight.
- https://github.com/quinn-rs/quinn/issues/2041
- https://bugzilla.mozilla.org/show_bug.cgi?id=1916558
While it previously seemed like this might be bound to _Windows on ARM_ only, that assumption can no longer be made, see e.g. https://github.com/quinn-rs/quinn/issues/2041#issuecomment-2542435062 and [Bugzilla comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1916558#c54). Thus our previous attempt (https://github.com/quinn-rs/quinn/pull/2071) is not enough.
I suggest by default disabling GRO (i.e. URO) on all of Windows, with an advanced option for users to enable it via `UdpSocketState::set_gro(true)`.
Users that control their hardware, i.e. know the hardware supports URO, can enable it.
Users …
=> fix(udp): make GRO (i.e. URO) optional on Windows, off by default

quinn-proto/src/endpoint.rs, quinn-proto/src/token.rs
Improved decoupling between modules, makes code flow easier to understand IMO, and sets us up to have an easier time adding more internal variants to `RetryToken`, for NEW_TOKEN stuff.
=> Factor out `IncomingToken`

perf/src/stats.rs, quinn-proto/src/lib.rs
=> proto: replace hidden field with From impl

quinn-proto/src/connection/streams/mod.rs, quinn/src/send_stream.rs
This allows us to remove the `#[doc(hidden)] pub fn new() -> Self`.
---
See #2097
=> Implement Default for ClosedStream

quinn-proto/src/config/mod.rs
- Removes `#[doc(hidden)]`
- Adds hyperlink
- Demotes most of the doc comment to non-doc comment, as it seems more like an internal note than something the user needs to see.
---
See #2097
=> Un-hide get_max_udp_payload_size

quinn/src/send_stream.rs
Previously, this method was public, but marked as `#[doc(hidden)]`. However, nothing anywhere was using it. This commit makes it private.
---
See #2097
=> quinn: Make SendStream::poll_stopped private

quinn-proto/src/token.rs
Follow-up from #2094.
r? @gretchenfrage
=> Token tweaks

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/tests/mod.rs, quinn/src/connection.rs
See #2097.
~~Note: `initiate_key_update` (the one in proto) is called from various places internally, which is the primary reason for differences in their names and comment.~~
=> Un-hide force_key_update / initiate_key_update

quinn-proto/src/shared.rs, quinn-udp/src/lib.rs
See #2097
~~I took the liberty of committing b11f2bf5e71daeac93827541183be1e0a1fdab9c. Unfortunately, it is semver breaking for everything. Users must convert `x.is_ce()` to `x == EcnCodepoint::Ce`.~~
=> Unhide ecn variants

quinn-proto/src/lib.rs
The module is already `#[cfg(fuzzing)]`, which should make it not appear in docs.
---
See #2097 
I manually confirmed that the module doesn't appear when running `cargo doc` locally. However, I'm aware that docs.rs does some stuff about annotating which conditions different items are feature-gated behind, platform-gated behind, etc, which running `cargo doc` doesn't. I don't know how that works, whether it's a feature of cargo doc or something docs.rs has hacked on top, or how to recreate it locally. I'm hoping that it being `#[cfg(fuzzing)]`--notably, not a feature--will make it just not appear. But if we notice that it's popped up on the next release then we might have to revert.
=> proto: Remove superfluous `#[doc(hidden)]` fuzzing

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/paths.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/token.rs
Changes all `&SocketAddr` to `SocketAddr`. Per [previous discussion](https://github.com/quinn-rs/quinn/pull/2094#discussion_r1887198528). Note: This repo contains no occurrences of `&IpAddr`.
=> proto: Pass `SocketAddr` by value

quinn-proto/src/connection/mod.rs, quinn-proto/src/frame.rs, quinn-proto/src/lib.rs, quinn-proto/src/packet.rs, quinn-udp/src/lib.rs, quinn/src/recv_stream.rs, quinn/src/runtime.rs, quinn/src/runtime/async_io.rs, quinn/src/send_stream.rs
I noticed this was occurring here and there in the repo. I don't recall if there was a motivation for it in some old Rust version, but I don't think there is now.
=> Remove `use self::` occurrences

quinn-proto/src/endpoint.rs
Please see individual commits.
=> proto: Minor refactors to `Endpoint.handle`

quinn-proto/src/crypto/rustls.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/packet.rs, quinn-proto/src/token.rs
Same idea as #2107 but for `ConnectionId`. `ConnectionId` is, and probably always will be, `Copy`. `ConnectionId` is not remotely large enough to trigger stack overflows or severe performance hazards by being copied. So, we should just simplify the code and let the compiler figure out if it wants to optimize it elsewise.
~~Plus, this shaves off a few lines by convincing the rustfmt to collapse some multi-line method signatures into one line.~~
Edit: Changes this PR to only do so internally, and not change the API.
=> proto: Pass `ConnectionId` by value internally

quinn-proto/src/endpoint.rs
IMO, `Endpoint.handle` is currently too large. This PR contains refactors relating to making it smaller by shunting more of its logic to `handle_first_packet`.
=> proto: Reduce size of `Endpoint.handle`

quinn-proto/src/frame.rs
Noticed this old TODO while reviewing #1912. Minor simplification/cleanup, no behavior change.
=> proto: remove redundant cursors

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/pacing.rs, quinn-proto/src/tests/util.rs, quinn-proto/src/token.rs
Replaces them with more modern and appropriate constructors or constants.
=> proto: Replace calls to Duration::new

quinn-udp/src/windows.rs
On Windows, to enable ECN reporting, one sets the `IPV6_RECVECN` socket option. The Windows IP stack will then report ECN markings via the `IPV6_ECN` message type.
Previously `quinn-udp` would use `IPV6_ECN` for both. With this commit `IPV6_RECVECN` is used to set the socket option and `IPV6_ECN` is used to read the option.
Given that both constants evaluate to the same value (i.e. `50`) the previous behavior does not result in an actual bug.
See also:
- https://learn.microsoft.com/en-us/windows/win32/winsock/ipproto-ipv6-socket-options
- https://www.ietf.org/archive/id/draft-duke-tsvwg-udp-ecn-01.html
- https://docs.rs/windows-sys/latest/windows_sys/Win32/Networking/WinSock/constant.IPV6_RECVECN.html
- https://docs.rs/windows-sys/latest/windows_sys/Win32/Networking/WinSock/constant.IPV6_E …
=> fix(udp/windows): set socket option IPV6_RECVECN

quinn-udp/src/windows.rs
Equivalent to https://github.com/quinn-rs/quinn/pull/2125 for IPv4.
On Windows, to enable ECN reporting on IPv4, one sets the `IP_RECVECN` socket option. The Windows IP stack will then report ECN markings via the `IP_ECN` message type.
Previously `quinn-udp` would use `IP_ECN` for both. With this commit `IP_RECVECN` is used to set the socket option and `IP_ECN` is used to read the option.
Given that both constants evaluate to the same value (i.e. `50`) the previous behavior does not result in an actual bug.
See also:
- https://learn.microsoft.com/en-us/windows/win32/winsock/ipproto-ipv6-socket-options
- https://www.ietf.org/archive/id/draft-duke-tsvwg-udp-ecn-01.html
- https://docs.rs/windows-sys/latest/windows_sys/Win32/Networking/WinSock/constant.IP_RECVECN.html
- …
=> fix(udp/windows): set socket option IP_RECVECN

.github/workflows/rust.yml
I suggest we test the feature introduced in https://github.com/quinn-rs/quinn/pull/1993 on CI.
---
Related, we are currently integrating it into Neqo (https://github.com/mozilla/neqo/pull/2302). On our localhost Download benchmark it shows ~10% throughput improvement.
=> ci: run quinn-udp tests with fast-apple-datapath

.github/workflows/codecov.yml, perf/Cargo.toml, quinn-proto/Cargo.toml, quinn-udp/Cargo.toml, quinn/Cargo.toml
An attempt to fix https://github.com/quinn-rs/quinn/actions/runs/11562272211/job/32183071070 on `main` and (unreleased) `0.5.6`
=> fix(.github/codecov): Ignore aws-lc-rs-fips for codecov

.github/workflows/rust.yml, Cargo.toml, quinn-udp/Cargo.toml, quinn-udp/build.rs, quinn-udp/src/lib.rs, quinn/Cargo.toml, quinn/build.rs, quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/lib.rs, quinn/src/mutex.rs, quinn/src/runtime.rs, quinn/src/tests.rs, quinn/src/work_limiter.rs
- Adds a `cfg_alias` `wasm_browser` for `all(target_family = "wasm", target_os = "unknown")` (matching `wasm*-*-unknown`)
- Makes `socket2` a target-dependent dependency
- Code depending on `std::net::UdpSocket` (e.g. `Runtime::wrap_udp_socket` or `Endpoint::rebind`) becomes gated as `not(wasm_browser)`
- adds `web_time` as target-dependent dependency in `quinn` to replace `std::time::{Instant, Duration}`, which panic in Wasm otherwise.
- These changes were verified outside this PR with a custom `Runtime` implementation in the browser and nodejs.
I'm not contributing this test (yet?) as discussed.
- The "test (wasm32-unknown-unknown)" github action job was adjusted with a check making sure there's no `(import "env" ...)` in the `quinn` `.wasm` file when built.
This is a good, even if not …
=> feat(quinn,quinn-udp): Avoid `socket2` and `std::net::UdpSocket` dependencies in `wasm32-unknown-unknown` target

quinn-proto/src/tests/mod.rs
#871 seems to have added a test with this code:
```rust
let next_retire_prior_to = active_cid_num + 1;
pair.client_conn_mut(client_ch).ping();
// Server retires all valid remote CIDs
pair.server_conn_mut(server_ch)
.rotate_local_cid(next_retire_prior_to);
pair.drive();
assert!(!pair.client_conn_mut(client_ch).is_closed());
assert!(!pair.server_conn_mut(server_ch).is_closed());
assert_matches!(
pair.client_conn_mut(client_ch).active_rem_cid_seq(),
_next_retire_prior_to
);
```
Note on the last line that `_next_retire_prior_to` is a new identifier, which does not actually reference the earlier binding `next_retire_prior_to`. Because this is is `assert_matches!()`, I think the intended semantics here are a little unclear, and this was probably be intended as `assert_eq!(.., …
=> Simplify weirdly broken test code

quinn-proto/src/config/mod.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/paths.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/connection/stats.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/frame.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/tests/token.rs, quinn-proto/src/tests/util.rs, quinn-proto/src/token.rs, quinn/src/incoming.rs, quinn/src/lib.rs
The server now sends the client NEW_TOKEN frames, and the client now stores and utilizes them.
The main motivation is that this allows 0.5-RTT data to not be subject to anti-amplification limits. This is a scenario likely to occur in HTTP/3 requests, as one example: a client makes a 0-RTT GET request for something like a jpeg, such that the response will be much bigger than the request, and so unless NEW_TOKEN frames are used, the response may begin to be transmitted but then hit the anti-amplification limit and have to pause until the full 1-RTT handshake completes.
For example, here's some experimental data that should be similar in the relevant ways:
- The client sends the server an integer and the server responds with that number of bytes
- They do it in 0-RTT if they can
- For each …
=> Utilize NEW_TOKEN frames

quinn/src/send_stream.rs
We don't actually need the `runtime-tokio` feature to implement `tokio::io::AsnycWrite`, as we import enough of tokio for that already.
In a similar way, there already exists an `impl tokio::io::AsyncRead for RecvStream`, so this would just make the implementations between `SendStream` and `RecvStream` consistent.
=> fix(quinn): `impl tokio::io::AsyncWrite for SendStream`

deny.toml
This is newly required for libfuzzer-sys 0.4.9. It is a permissive license similar to the MIT or 3-claused BSD licenses.
=> Allow the NCSA license

.cargo/config.toml, Cargo.toml, quinn-proto/Cargo.toml, quinn-proto/src/cid_generator.rs, quinn-proto/src/config/mod.rs, quinn-proto/src/congestion/bbr/mod.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/connection/spaces.rs, quinn-proto/src/endpoint.rs, quinn-proto/src/tests/mod.rs, quinn-proto/src/token.rs, quinn-proto/src/transport_parameters.rs, quinn/tests/many_connections.rs
=> Upgrade to rand 0.9

quinn-udp/Cargo.toml, quinn-udp/src/cmsg/unix.rs
On MacOS < 14, with `fast-apple-datapath` feature, calls to `libc::CMSG_NXTHDR` might continuously return empty (i.e. all zero) `libc::cmsghdr` instead of a null pointer. This results in a busy loop in `decode_recv`:
``` rust
let cmsg_iter = unsafe { cmsg::Iter::new(hdr) };
for cmsg in cmsg_iter {
match (cmsg.cmsg_level, cmsg.cmsg_type) {
```
https://github.com/quinn-rs/quinn/blob/b4378bb39dab4b58a1e6a3fea4fff9f87033dab6/quinn-udp/src/unix.rs#L685C1-L687C50
This commit fixes the above, returning a `null_mut()` pointer on an empty `libc::cmsgdhr`, thus terminating the `cmsg_iter`.
See also https://github.com/mozilla/neqo/pull/2427 for details.
=> fix(udp/fast-apple): ignore empty cmsghdr

quinn-proto/src/congestion/bbr/bw_estimation.rs
This was the only case where `Instant::now()` is used in quinn-proto or quinn-udp for anything other than tests or logging. Making this change to keep these two crates more IO-agnostic.
=> Remove use of Instant::now() in BBR bandwidth estimation code

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/spaces.rs
This reverts the change that tries to avoid sending a PING frame if there are user datagrams to send.  The problem is that the user dataram might not fit in the probe that will be sent.
It is possible to do this better, but the quick thing is to accept the extra ping frame, the space wasted because of this is rather minimal. And if a user was sending user datagrams at just the right MTU size it is unlikely they would fit in the next packet anyway since typically the probe packet will end up with a smaller size-limit compared to the MTU.
Reverts part of #2169.
=> Prefer sending extra ping again

quinn-proto/src/connection/mod.rs, quinn-proto/src/tests/mod.rs
When needing to send tail-loss probes and building a GSO batch the tail-loss probe should not exceed the GSO segment size.  At the same time a GSO batch needs to be broken when the segment size exceeds the maximum size for a tail-loss probe.
Somehow we have a reliable reproducer of this in https://github.com/n0-computer/callme/tree/no-graceful-close, but that is quite a bit away from Quinn main.  Applying this fix solves it, but I am not really sure how to test this in the test suite.  There isn't any example in the file of tests constructing their state to test particular poll_transmit behaviours.  Any hints on how I might be able to add tests to this?
=> fix: Do not produce tail-loss probes larger than segment size

Cargo.lock, perf/src/lib.rs, quinn-udp/Cargo.toml, quinn-udp/src/fallback.rs, quinn-udp/src/unix.rs, quinn-udp/src/windows.rs, quinn-udp/tests/tests.rs
Add `UdpSocketState::set_send_buffer_size` and `UdpSocketState::set_recv_buffer_size`, which allow resizing the respective socket buffers.
CC @mxinden
=> feat: Allow changing the UDP send/receive buffer sizes

Cargo.lock, quinn-proto/src/connection/pacing.rs, quinn-proto/src/connection/send_buffer.rs, quinn-proto/src/connection/streams/recv.rs
Fixes #2186.
The deranged maintainer appears to be [unlikely](https://github.com/jhpratt/deranged/issues/18#issuecomment-2749704917) to revert the new `PartialEq` impls that are causing this. I'm guessing this is not causing downstream issues because only dev-dependencies are pulling in the deranged crate, so there should be no urgent need for a release.
=> Avoid inference hazard for integer comparisons

quinn-proto/src/connection/mod.rs, quinn-proto/src/tests/mod.rs, quinn/src/connection.rs
Hello,
I've been playing with quinn-proto recently and I noticed that, sometimes, when the maximum segment is large enough quinn will go over the max_datagrams limit of poll_transmit. I believe this PR will fix this issue.
Also, considering that quin-proto is a low level crate, it feels like this code:
https://github.com/quinn-rs/quinn/blob/434c35861e68aac1da568bcd0b1523603f73f255/quinn-proto/src/connection/mod.rs#L454-L457
should be removed and left for the upper level code to decide what max limit they truly want to use.
=> fix: respecting max_datagrams in poll_transmit

quinn-udp/src/unix.rs
This is based on top of https://github.com/quinn-rs/quinn/pull/2199 so ignore the first commit when reviewing. Will rebase once that is merged.
As part of dealing with this code, I figured it could be easier to understand if it were more consistent and used early-returns to reduce indentation.
=> quinn-udp: refactor control-flow in `send` and `recv` impls

.github/workflows/rust.yml, quinn-udp/src/cmsg/mod.rs, quinn-udp/src/cmsg/unix.rs, quinn-udp/tests/tests.rs
This is an alternative version to #2207 that has a smaller change to the API surface.
Resolves: #2206
=> fix(quinn-udp): move cmsg-len check to Iterator

quinn/src/recv_stream.rs
Looks to the following for writing inspiration:
- https://docs.rs/tokio/latest/tokio/io/trait.AsyncRead.html#tymethod.poll_read
- https://doc.rust-lang.org/stable/std/io/trait.Read.html#tymethod.read
Achieves:
- Reflowing to 100 columns.
- Style-consistency with code-escaping and initial-line period.
- Distinguishing first lines between the two methods' doc comments.
- Hyperlink to SendStream::finish
- General writing style.
=> docs(quinn): Copy edit poll_read(_buf?) docs

Cargo.lock, quinn-proto/Cargo.toml
Bumping the version to be able to get a patch release of `quinn-proto`, in order to have a version with the fix for #2167 on crates.io. I think we only need `quinn-proto` for this, not `quinn` itself, right?
I'm not sure if there is any other ceremony around releases? I saw nothing interesting in the history, and no contributions-file.
=> Bump the quinn-proto version to 0.11.11 for release

Cargo.lock, quinn-udp/Cargo.toml, quinn-udp/src/unix.rs
`quinn-udp` with fast-apple-datapath previously did not initialize the control message array memory before passing it to `recvmsg_x`.
On MacOS 10.15 `recvmsg_x` does not seem to set `msg_controllen`. Thus `CMSG_NXTHDR` reads beyond the control messages written by `recvmsg_x`, into the unitinialized memory region.
With this commit, the control message array is initialized (with zeroes) before passing it to `recvmsg_x`, thus no longer reading unset control messages.
See https://github.com/quinn-rs/quinn/issues/2214 for details.
//CC @larseggert
=> fix(udp): zero control message array on fast-apple-datapath

Cargo.lock, Cargo.toml, quinn-proto/Cargo.toml, quinn-proto/src/config/mod.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests/util.rs, quinn-proto/src/token_memory_cache.rs, quinn/src/lib.rs
Implements `TokenMemoryCache`, and makes it the default `TokenStore` for clients.
=> Add `TokenMemoryCache`

.github/workflows/codecov.yml, Cargo.lock, Cargo.toml, quinn-proto/Cargo.toml, quinn-proto/src/bloom_token_log.rs, quinn-proto/src/config/mod.rs, quinn-proto/src/lib.rs, quinn-proto/src/tests/util.rs, quinn/Cargo.toml, quinn/src/lib.rs
- Adds default optional dependency on [`fastbloom`](https://lib.rs/crates/fastbloom)
- Adds `BloomTokenLog`, a new `TokenLog` implementation:
- At first, it just stores elements in a hash set. In this phase, it experiences linear memory growth and neither false positives nor false negatives.
- When the hash set would consume more memory than a configurable limit, it converts it to a bloom filter. This essentially makes it so that, rather than more elements causing it to consume more memory, more elements cause its false positive rate to keep going up. This way, its memory usage stays constant, and it treats old and newly added elements "fairly" rather than say, discarded new elements or something more questionable.
- The `fastbloom` crate is a popular bloom filter implementation with SIMD …
=> Add `BloomTokenLog`

Cargo.lock, quinn/Cargo.toml
Bump the version of `quinn` so that #2221 may be fixed. Feel free to ping me if you need me to do anything else.
=> Bump quinn version to 0.11.8

Cargo.lock, quinn-proto/Cargo.toml, quinn/Cargo.toml
In order to release quinn 0.11.8 (see #2222, #2221), we need to bump quinn-proto to 0.11.12 (since #2136 landed in the mean time):
```rust
djc-2021 main quinn $ cargo publish
Updating crates.io index
Packaging quinn v0.11.8 (/Users/djc/src/quinn/quinn)
Updating crates.io index
error: failed to prepare local package for uploading
Caused by:
failed to select a version for `quinn-proto`.
... required by package `quinn v0.11.8 (/Users/djc/src/quinn/quinn)`
versions that meet the requirements `^0.11.10` are: 0.11.11, 0.11.10
the package `quinn` depends on `quinn-proto`, with features: `bloom` but `quinn-proto` does not have these features.
```
=> proto: bump version to 0.11.12

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/mod.rs, quinn-proto/src/connection/streams/send.rs, quinn-proto/src/lib.rs
There are no public APIs that accept BytesSource. This commit makes it not be re-exported publically.
---
I am cherry-picking this commit from #2230. Djc and Ralith [both seemed to agree](https://github.com/quinn-rs/quinn/pull/2230#issuecomment-2869218721) in that PR that, although this is technically a breaking change, we're ok with acting like it's not because we assume nobody is using `BytesSource` (because we provide no way to use it and seemingly made it public by accident).
I am splitting this out from 2230 because that way we don't have to think about that quirk of the change in 2230.
Closes #2228.
=> proto: Make BytesSource private

quinn/src/connection.rs
[`Side` is exported in `quinn`](https://docs.rs/quinn/latest/quinn/enum.Side.html) but there's no actual way to get it from `Connection`. Seems like a simple oversight. 
Otherwise, this means it must be passed around separately to do any kind of client- or server-specific logic, which gets quite annoying.
=> expose `Connection::side()` in `quinn`

quinn/src/runtime.rs, quinn/src/runtime/async_io.rs
For some reason I'm not getting a "`UdpSocket` is unused" when I run `cargo check -p quinn --no-default-features --features async-io", even though cfg-ing it out totally works and it fails in conjunction with other changes (see #2259).
Previous discussion: https://github.com/quinn-rs/quinn/pull/2259#discussion_r2127726193
=> refactor(quinn): Configure out `async_io::UdpSocket` when unused

Cargo.lock, quinn-udp/Cargo.toml
Thanks to @inetic `quinn-udp` no longer falsely detects GSO support in kernel <4.18 (https://github.com/quinn-rs/quinn/pull/2248).
Any objections shipping this patch as a new `quinn-udp` patch release?
Background: I am working on GSO support in Firefox's QUIC stack. See https://github.com/mozilla/neqo/pull/2593 for details.
=> chore(udp): increase patch version to v0.5.13

quinn/src/connection.rs
Comments on behaviour when calling said function on a full datagram queue
=> Updated quinn::Connection::send_datagram() docs

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs
Fixes #1695 at long last. Nothing serious or production-relevant, fortunately.
=> Fix flaky key update test

quinn-proto/src/endpoint.rs
This comment being in the wrong place makes reading this code a bit confusing.
=> Tiny clean up of a comment that was in the wrong place

quinn-proto/src/connection/mod.rs, quinn-proto/src/frame.rs
Fixes #2310.
This code was first added in
- #124
Later it was updated in
- #394 
but we neglected to update the size bound.
Introduce a constant to see if we can do better.
Also checked for other constants being compared to -- the only ones remaining seem to be `PATH_CHALLENGE` and `PATH_RESPONSE` which are written more directly and are still correct.
=> proto: fix NewConnectionId size bound

perf/Cargo.toml, perf/src/bin/perf_client.rs, perf/src/bin/perf_server.rs, quinn-proto/Cargo.toml, quinn-proto/src/config/mod.rs, quinn-proto/src/config/transport.rs, quinn-proto/src/congestion.rs, quinn-proto/src/congestion/bbr/mod.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/packet_builder.rs, quinn-proto/src/connection/paths.rs, quinn-proto/src/connection/qlog.rs, quinn-proto/src/lib.rs, quinn/Cargo.toml, quinn/src/connection.rs, quinn/src/lib.rs
Follow-up for https://github.com/quinn-rs/quinn/pull/2278.
This reworks qlog configuration to be consistent with other connection configuration, allows it to be specified when connections are first created, and allows users to control whether a qlog file is exclusive to a connection or arbitrarily shared.
Future work could include adding a `QlogStream` option to `EndpointConfig` for non-connection-related events, subject to the same optional sharing.
=> Configure qlog in TransportConfig

.github/workflows/codecov.yml
github action still use __qlog
=> cov: fix qlog feature name

quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/streams/state.rs, quinn/src/connection.rs
We have a desire to limit the amount of bandwidth used for a given peer in both directions, but by the nature of the application, we can't decide that limit is until we're already connected to the peer and have verified their identity.
We already make use of backpressure throughout the application, so we can use the connection itself to limit the bandwidth used without everything backing up elsewhere.
I think we can most easily affect this by setting the `receive_window` to our desired bandwidth times the RTT, but that only gives us control over inbound bandwidth; we don't currently have a way to set the `send_window` after the connection is established.
Looking through the implementation, the handling of `send_window` doesn't look to be _nearly_ as complex as `read_window` since it's a …
=> feat: add `Connection::set_send_window()`

perf/src/bin/perf.rs, perf/src/client.rs, perf/src/lib.rs, perf/src/server.rs
I've been using `perf_client` and `perf_server` lately, but the split-binary design feels cumbersome.
It'd be much more convenient—like `iperf3` or msquic's perf—to have a single binary that supports both client and server modes via command-line flags.
Converted the previous top-level options into Perf subcommands. All other behavior remains consistent with the prior implementation.
old version:
```bash
$ ./perf_server --no-protection
$ ./perf_client ip:4433 --no-protection
```
new version:
```bash
$ ./perf server --no-protection
$ ./perf client ip:4433 --no-protection
```
=> perf: move client and server on one binary

perf/Cargo.toml
As title suggest, renamed perf binary to quinn-perf to prevent name clash with linux perf profiler
=> perf: rename perf binary to quinn-perf to prevent name clash with linux perf

Cargo.lock, perf/Cargo.toml, perf/src/bin/perf.rs, quinn/src/runtime.rs
This requires a compilation with tokio_unstable flag :
`RUSTFLAGS="--cfg tokio_unstable" cargo build -r -p perf -F tokio-console`
You can then run perf server and client like that :
```
TOKIO_CONSOLE_BIND=127.0.0.1:6669 ./target/release/quinn-perf server --listen 127.0.0.1:4433
TOKIO_CONSOLE_BIND=127.0.0.1:6668 ./target/release/quinn-perf client --duration 60 127.0.0.1:4433
```
Then attach [tokio-console](https://github.com/tokio-rs/console) to both process :
```
tokio-console http://127.0.0.1:6669
tokio-console http://127.0.0.1:6668
```
=> perf: add a feature to enable profiling with tokio-console

Cargo.lock, deny.toml, quinn/Cargo.toml, quinn/src/lib.rs, quinn/src/runtime.rs, quinn/src/runtime/async_io.rs
async-std has been deprecated upstream in favor of smol.
=> quinn: drop async-std support

Cargo.lock, Cargo.toml, perf/Cargo.toml, perf/src/server.rs, quinn/Cargo.toml, quinn/examples/server.rs
Could potentially be backported to `0.11.x`.
=> Use newer rustls-pki-types PEM parser API

.github/workflows/codecov.yml, .github/workflows/rust.yml, quinn-proto/Cargo.toml, quinn-udp/Cargo.toml, quinn-udp/src/lib.rs, quinn/Cargo.toml
Previously `quinn*` would provide the `log` feature to log events via `log` if no `tracing` subscriber exists.
Later https://github.com/quinn-rs/quinn/pull/1923 allowed `quinn-udp` to log via `log` directly, making `tracing` an optional dependency. For that, it introduced the `direct-log` feature, a workaround name in order to not introduce a breaking change.
This commit cleans up the above, renaming the `log` feature to `tracing-log` and the `direct-log` to `log`. This is a breaking change and thus `quinn-udp` is bumped to `v0.6.0`.
See https://github.com/quinn-rs/quinn/pull/1921 for the full history.
---
Only merge before the next breaking change of `quinn`.
I am opening this up early as it is (a) still fresh in my mind, (b) in order to keep track of it and (c) make the next breaking …
=> refactor!: rename log feature to tracing-log

quinn/src/connection.rs, quinn/src/endpoint.rs, quinn/src/lib.rs, quinn/src/runtime.rs, quinn/src/runtime/async_io.rs, quinn/src/runtime/tokio.rs
This PR contains some changes to the `AsyncUdpSocket` trait. In short:
- `poll_recv` now takes `&mut self` instead of `&self`
- `try_send` is removed from `AsyncUdpSocket`
- `create_io_poller` and the `UdpPoller` trait are now replaced with `create_sender` and the `UdpSender` trait
- the `UdpSender` trait has a `try_send` as well as a `poll_send` function (that takes `self: Pin<&mut Self>`) instead of a `poll_writable` function
The final traits look like this:
```rs
pub trait AsyncUdpSocket: Send + Sync + Debug + 'static {
fn create_sender(&self) -> Pin<Box<dyn UdpSender>>;
fn poll_recv(
&mut self,
cx: &mut Context,
bufs: &mut [IoSliceMut<'_>],
meta: &mut [RecvMeta],
) -> Poll<io::Result<usize>>;
fn local_addr(&self) -> io::Result<SocketAddr>;
fn max_receive_segments(&self) -> usize;
fn …
```
=> feat(quinn): Pass in `&mut self` for `AsyncUdpSocket`'s `poll_recv` and re-introduce `poll_send`

quinn-udp/src/fallback.rs, quinn-udp/src/lib.rs, quinn-udp/src/unix.rs, quinn-udp/src/windows.rs
I wanna use `quinn-udp`, but I also need the interface index information.
Currently `quinn-udp` reads the `IP_PKTINFO` header and extracts only `destination_ip`, discarding `interface_index`.
This PR adds `interface_index` to `RecvMeta`
=> Add interface_index to RecvMeta

quinn-udp/src/lib.rs
Mark `RecvMeta` as non exhaustive such that subsequent field additions are not breaking changes.
Fixes https://github.com/quinn-rs/quinn/issues/2378.
=> feat!(udp): mark RecvMeta as non_exhaustive

quinn-udp/build.rs
Fix #2386 
Depends on https://github.com/briansmith/ring/pull/2702 Tested in the dependant PR.
=> Add watchOS to BSD-like OS target list

quinn-proto/src/congestion.rs, quinn-proto/src/congestion/bbr/mod.rs, quinn-proto/src/congestion/cubic.rs, quinn-proto/src/congestion/new_reno.rs, quinn-proto/src/connection/mod.rs, quinn-proto/src/connection/spaces.rs
Benchmarks in the cloud between two Linux machines on a 10ms/1Gbps link revealed that `quinn` performs consistently worse than `msquic`. Plotting the congestion window for both implementations shows that `msquic` reaches higher congestion window sizes, in part because [it implements spurious loss recovery](https://github.com/microsoft/msquic/blob/2623c07df62b4bd171f469fb29c2714b6735b676/src/core/loss_detection.c#L1400) (as described in [rfc8312bis](https://datatracker.ietf.org/doc/html/draft-ietf-tcpm-rfc8312bis-15#section-4.9) which is now [rfc9438](https://datatracker.ietf.org/doc/html/rfc9438#section-4.9)).
This PR implements a similar spurious loss recovery mechanism (`quinn` implements `rfc8312`)
Lost packets are stored in the `PacketSpace` and used on ACK reception to determine if …
=> Implement spurious loss recovery
