quinn-rs/quinn

- quinn-proto/src/coding.rs
- quinn-proto/src/frame.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/transport_error.rs
> Rename Value trait to Codec

- .travis.yml
- quinn-proto/src/connection.rs
- quinn-proto/src/crypto.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/range_set.rs
- quinn-proto/src/stream.rs
- quinn/src/lib.rs
I've found that relying on people to apply rustfmt is painful because it means my formatting fixes when trying to fix up my own diffs get intertwined with existing diffs left from pull requests. This way PRs will get flagged if they haven't been formatted.
I'm curious what you think of the Clippy fixes here. It's not huge value, but I like to learn new things about language and standard library from it.
> Use rustfmt in CI and apply more Clippy suggestions

- quinn-proto/src/connection.rs
- quinn-proto/src/endpoint.rs
So we don't have to keep passing it around.
> Store ConnectionHandles in Connections

- quinn-proto/Cargo.toml
- quinn-proto/src/crypto.rs
- quinn-proto/src/frame.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/packet.rs
> Remove ArrayVec in favor of a simple array

- quinn/src/lib.rs
This was already supported by the endpoint state machine, but was defeated by the high-level API.
I swapped in the sync version of mpsc because it had a helpful method the unsync version didn't, and because per gitter discussion we expect to be experimenting with multithreading in the future anyway.
> Implement backpressure on incoming connections

- quinn-proto/src/connection.rs
- quinn-proto/src/transport_parameters.rs
This implements all the new transport parameters and factors out a lot of the error-prone duplication with macros.
> Implement draft 15 transport parameters

- quinn/src/lib.rs
Simple RefCell borrow error. Could have corrected this with a clone to get a much smaller diff, but this saves the clone and keeps information where it needs to be anyway.
Thanks to @icefoxen for reporting the issue.
> Fix panic on Endpoint::connect

- quinn/src/lib.rs
Fruits of some discussion on obviousness of semantics in IRC.
> Clarify some high-level documentation

- quinn-proto/src/connection.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/stream.rs
Hope this doesn't interfere (too much) with any work you've done.
> Clarifications for the streams API

- README.md
- quinn-proto/Cargo.toml
- quinn-proto/src/connection.rs
- quinn-proto/src/crypto.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/frame.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/tests.rs
- quinn-proto/src/transport_error.rs
- quinn/Cargo.toml
- quinn/examples/client.rs
- quinn/examples/server.rs
- quinn/src/lib.rs
Independent fixes on the path towards updating the handshake state machine. I may add more to this as I pursue that goal.
> Draft 15 updates

- quinn-proto/src/connection.rs
- quinn-proto/src/crypto.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/stream.rs
- quinn-proto/src/transport_parameters.rs
Clippy has quite a lot to say about the code base.
This intended to be a gradual cleanup.
Feel free to reject if there are other ideas or policies on clippy, or pickup up commits incrementally if deemed useful.
I'll be adding more work here as time permits.
> WIP: clippy cleanup

- quinn-proto/src/tests.rs
> Fix incorrect assert!()

- quinn-proto/Cargo.toml
- quinn-proto/examples/connect.rs
- quinn-proto/src/coding.rs
- quinn-proto/src/connection.rs
- quinn-proto/src/crypto.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/frame.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/range_set.rs
- quinn-proto/src/stream.rs
- quinn-proto/src/tests.rs
- quinn-proto/src/transport_error.rs
- quinn-proto/src/transport_parameters.rs
- quinn/Cargo.toml
- quinn/examples/client.rs
- quinn/examples/interop.rs
- quinn/examples/server.rs
- quinn/src/lib.rs
I don't think compatibility with older compilers will be an issue for us.
> Convert to 2018 edition

- quinn-proto/src/connection.rs
- quinn-proto/src/dedup.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/frame.rs
- quinn-proto/src/lib.rs
This implements support for decoding the new frame types, but does not yet implement any substantial parts of the associated logic. I'm going to continue working on that, starting with ECN.
> Draft 16 frames

- .travis.yml
> Fix travis nightly rustfmt

- README.md
Make it clearer how to run the example across the network.  Supersedes PR #105.
> Update example documentation in Readme

- quinn-proto/src/connection.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/tests.rs
Stumbled on this while debugging physical ECN bindings.
> Fix bugs in retransmit

- quinn-proto/src/connection.rs
- quinn-proto/src/frame.rs
- quinn-proto/src/lib.rs
And a minor correctness fix, per https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#retransmission-of-information
> Draft 17 frames

- quinn-proto/src/connection.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/tests.rs
This resolves the issues I've identified so far in the course of interop testing. Some missed draft-17 changes, mostly logic errors.
> Assorted bugfixes

- .travis.yml
- quinn-proto/src/connection.rs
- quinn-proto/src/crypto.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/packet.rs
- quinn/examples/interop.rs
- quinn/examples/server.rs
- quinn/src/lib.rs
This brings us to VHDC interop with ngtcp2 server.
> Fix header protection sampling, premature key discard

- quinn-proto/Cargo.toml
- quinn-proto/src/connection.rs
- quinn/Cargo.toml
This fixes the interop tool's second handshake.
> Fix malformed resumption handshake

- README.md
- quinn-proto/src/connection.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/tests.rs
- quinn/examples/interop.rs
- quinn/src/lib.rs
My first idea worked after all, I was just doing it wrong.
Fixes #172
Fixes #176
> Test resumption and key update in interop tool

- quinn-proto/src/connection.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/tests.rs
Highlight of this PR is successful address migration by the picoquic client against our server.
> Assorted fixes

- README.md
This wording was from a bit of history that got rewritten before I submitted the PR, whoops!
> Fix confused README

- quinn-proto/Cargo.toml
- quinn-proto/src/connection.rs
- quinn-proto/src/crypto.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/tests.rs
- quinn/Cargo.toml
- quinn/src/lib.rs
This *should* work, but it will be difficult to test until rustls supports 0-RTT in servers. Something's weird with picoQUIC interop too; might have introduced an issue with Handshake encryption. Bulk of this should be more or less right, though.
> Implement 0-RTT data

- quinn-proto/src/connection.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/tests.rs
- quinn/src/builders.rs
- quinn/src/lib.rs
Extracted from #198. Semantic changes to make the quinn-proto API a little saner and more useful.
> Event tweaks

- quinn-proto/src/connection.rs
- quinn-proto/src/tests.rs
0-RTT stream IDs were being leaked.
> Fix incomplete stream state reset on 0-RTT rejection

- quinn/src/platform/cmsg.rs
- quinn/src/platform/linux.rs
No semantic changes, just additional insurance against UB.
> More cmsg cleanup

- quinn/src/lib.rs
When the CPU is much slower than the link (for example, due to Quinn being built in debug mode and running on an Atom), large requests could cause the `Driver` future to do nothing but send packets until the (peer-controlled, often large) flow control window is filled. Note that the congestion control window will tend to grow without bound in this case, because outgoing packet loss is unlikely. In testing, this lead to `recv` not being called for several seconds at a time, resulting in incoming packet loss.
> Reduce send/recv starvation when CPU bound

- quinn-proto/src/connection.rs
Per https://github.com/quicwg/base-drafts/pull/2355
> Relax 0-RTT frame type restrictions

- quinn-proto/Cargo.toml
- quinn-proto/src/connection.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/tests.rs
- quinn/src/lib.rs
- quinn/src/tests.rs
Please have a look at this early attempt.
(Handling these events in `poll_io()` may be somewhat unnatural, but was nice because it's part of the test driver code already.)
> Event-based communication from Connections to Endpoints

- quinn-proto/src/connection.rs
- quinn-proto/src/stream.rs
- quinn-proto/src/tests.rs
I accidentally an attempt to optimize the assembler. Would you mind comparing the benchmarks, since I don't have a nightly environment setup?
> Optimize stream assembler (see #258)

- quinn-proto/src/connection.rs
- quinn-proto/src/stream.rs
- quinn-proto/src/tests.rs
> Handle stream control frame reordering

- quinn-proto/src/connection.rs
- quinn-proto/src/stream.rs
Follow through on my plan to build `Streams` into more of an abstraction.
> Streams abstraction

- quinn/src/connection.rs
- quinn/src/endpoint.rs
- quinn/src/tests.rs
> Drop debugging

- interop/src/qif.rs
- quinn-h3/src/qpack/dynamic.rs
- quinn-proto/src/assembler.rs
- quinn-proto/src/connection.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/range_set.rs
- quinn/src/builders.rs
- quinn/src/platform/unix.rs
Following internals discussion I've decided to help improve `if let` usage in this project. I think it makes code smaller and more readable.
> if let cleanup

- quinn/src/connection.rs
- quinn/src/endpoint.rs
- quinn/src/lib.rs
- quinn/src/tests.rs
> Endpoint::close helper, related debugging

- quinn-proto/src/connection.rs
Expecting some further revision (and robustness improvements) to the recovery code due to https://github.com/quicwg/base-drafts/pull/2590, but this gets us in sync with the intention of the currently-published draft for now.
> Minor correctness fixes

- .travis.yml
- quinn/Cargo.toml
- quinn/tests/many_connections.rs
Rebased #284 and improved diagnostics.
> Many-connections test redux

- README.md
- interop/src/main.rs
- quinn-proto/src/connection.rs
- quinn/src/connection.rs
- quinn/src/endpoint.rs
- quinn/src/lib.rs
- quinn/src/streams.rs
- quinn/tests/many_connections.rs
So far lacks the interop changes, and thus is completely untested other than for regressions.
> Initial attempt at backporting 0-RTT API

- quinn-proto/src/crypto.rs
- quinn-proto/src/transport_parameters.rs
Missed this in the version negotiation changes.
> Draft 19 transport parameter encoding

- quinn-proto/src/connection.rs
- quinn-proto/src/crypto.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/frame.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/shared.rs
- quinn-proto/src/stream.rs
- quinn-proto/src/transport_error.rs
This is just an initial kick to make the docs for quinn-proto a bit more friendly (motivated in part by comments about this comparing us to quiche) for folks that need/want the lower-level API.
> Initial attempt at documenting public quinn-proto API

- quinn/Cargo.toml
- quinn/examples/common/mod.rs
- quinn/examples/connection.rs
- quinn/examples/insecure_connection.rs
- quinn/examples/single_socket.rs
Client/Server examples are great. They demonstrate that the project works, I can wireshark the traffic, see the quinn API, etc. But they are not so great for newbies when I want as less context as possible to see how to use quinn.
I was playing around with the library and made a couple of examples to get a better understanding. Seems like a valuable asset to share :)
> More examples

- interop/src/qif.rs
- quinn-h3/src/frame.rs
- quinn-h3/src/lib.rs
- quinn-h3/src/qpack/block.rs
- quinn-h3/src/qpack/decoder.rs
- quinn-h3/src/qpack/dynamic.rs
- quinn-h3/src/qpack/encoder.rs
- quinn-h3/src/qpack/tests.rs
- varint for FrameType, StreamType, SettingId.
- reorder frame layout to Type-Length-Value
- reserved stream type pattern change
- settings default value
> Update H3 / QPack code to draft-19

- README.md
- quinn-proto/src/connection.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/shared.rs
- quinn-proto/src/transport_error.rs
- quinn-proto/src/transport_parameters.rs
> Draft 20 updates, fixes

- quinn-proto/src/lib.rs
- quinn/src/connection.rs
I'll also see about banging out an end-to-end 0/0.5-RTT test, but this should be able to go in ahead of that if desired.
> Stream open documentation, bugfix

- quinn-proto/src/connection.rs
- quinn-proto/src/stream.rs
The way this previously redirected through `Connection` didn't make much sense.
> Handle stream cleanup after reading inside Streams

- quinn-proto/src/connection.rs
- quinn-proto/src/streams.rs
- quinn-proto/src/tests/mod.rs
- quinn/src/streams.rs
Not as clear a win as on the futures side, but I think it's still an improvement. Evaluated the sentinel value approach, too, but with the consistency issue with unordered reads I think this is still nice.
> Make stream finishing not an error

- quinn-h3/src/qpack/decoder.rs
- quinn-h3/src/qpack/encoder.rs
- quinn-proto/src/connection.rs
- quinn-proto/src/crypto.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/shared.rs
- quinn-proto/src/transport_parameters.rs
Fixes new warnings from 1.35.0.
> Move some code around

- quinn-h3/src/body.rs
- quinn-h3/src/client.rs
- quinn-h3/src/frame.rs
- quinn-h3/src/lib.rs
- quinn-h3/src/proto/connection.rs
- quinn-h3/src/proto/headers.rs
- quinn-h3/src/qpack/field.rs
- quinn-h3/src/server.rs
- quinn-proto/src/connection.rs
- quinn/src/connection.rs
@stammw please take note, there are a few recurring patterns here that you should try to avoid in the future. 👍
> Assorted clippy + style fixes

- quinn-h3/src/client.rs
- quinn-h3/src/lib.rs
- quinn-proto/src/connection.rs
- quinn-proto/src/crypto.rs
- quinn-proto/src/crypto/ring.rs
- quinn-proto/src/crypto/rustls.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/shared.rs
- quinn-proto/src/tests/mod.rs
- quinn-proto/src/transport_parameters.rs
- quinn/src/builders.rs
This is required by hyper, and seems fairly reasonable for these types.
> Implement Clone and Debug for builder types

- interop/src/main.rs
- quinn-proto/src/connection.rs
- quinn-proto/src/tests/mod.rs
- quinn/examples/client.rs
- quinn/examples/common/mod.rs
- quinn/examples/connection.rs
- quinn/examples/insecure_connection.rs
- quinn/examples/server.rs
- quinn/examples/single_socket.rs
- quinn/src/builders.rs
- quinn/src/connection.rs
- quinn/src/streams.rs
- quinn/src/tests.rs
Trying to reproduce the erratic 0-RTT failures in a controlled environment. No luck yet, but got some cleanup done along the way.
> Zero rtt testing

- quinn/src/streams.rs
> Fix ReadToEnd size limit

- quinn-h3/examples/h3.rs
- quinn-h3/src/body.rs
- quinn-h3/src/client.rs
- quinn-h3/src/headers.rs
- quinn-h3/src/lib.rs
- quinn-h3/src/server.rs
> H3 client receive body stream

- azure-pipelines.yml
I misinterpreted the default value for this earlier, but we added this in Travis before.
> Check benchmark code in CI

- quinn-h3/Cargo.toml
- quinn-h3/examples/h3.rs
- quinn-h3/examples/shared/mod.rs
- quinn-h3/examples/simple_client.rs
- quinn-h3/examples/simple_server.rs
- quinn-h3/src/body.rs
- quinn-h3/src/client.rs
- quinn-h3/src/connection.rs
- quinn-h3/src/frame.rs
- quinn-h3/src/headers.rs
- quinn-h3/src/proto/frame.rs
- quinn-h3/src/server.rs
> H3 stream body for sending

- quinn-proto/src/connection.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/transport_error.rs
- quinn-proto/src/transport_parameters.rs
More work to be done, but these are some independent steps in the right direction.
> Partial draft 23 updates

- quinn-proto/src/connection.rs
- quinn-proto/src/tests/mod.rs
- quinn-proto/src/transport_parameters.rs
I think this covers all the draft 23 changes to the transport draft, plus some incidental fixes/cleanup. Still TODO are the version/salt changes and the recovery draft changes.
> Draft 23 transport updates

- azure-pipelines.yml
- interop/Cargo.toml
- interop/src/main.rs
- quinn-h3/Cargo.toml
- quinn-h3/examples/h3.rs
- quinn-h3/examples/simple_client.rs
- quinn-h3/examples/simple_server.rs
- quinn-h3/src/body.rs
- quinn-h3/src/client.rs
- quinn-h3/src/connection.rs
- quinn-h3/src/frame.rs
- quinn-h3/src/headers.rs
- quinn-h3/src/lib.rs
- quinn-h3/src/proto/frame.rs
- quinn-h3/src/server.rs
- quinn/Cargo.toml
- quinn/benches/bench.rs
- quinn/examples/client.rs
- quinn/examples/connection.rs
- quinn/examples/insecure_connection.rs
- quinn/examples/server.rs
- quinn/examples/single_socket.rs
- quinn/src/builders.rs
- quinn/src/connection.rs
- quinn/src/endpoint.rs
- quinn/src/lib.rs
- quinn/src/streams.rs
- quinn/src/tests.rs
- quinn/src/udp.rs
- quinn/tests/many_connections.rs
> Std futures redux

- interop/src/main.rs
- quinn/src/connection.rs
- quinn/src/tests.rs
Fixes #436. CC @jean-airoldie.
> Expose 0-RTT handshake completion and success to applications

- quinn-proto/src/connection.rs
See https://github.com/quicwg/base-drafts/pull/3035
> Allow PING at every encryption level

- quinn/benches/bench.rs
- quinn/src/connection.rs
Reworks the existing benchmarks for concision and run the client and server on different threads, and fixes what I'm pretty sure was the issue behind the second benchmark all along: accepting a stream wasn't waking up the connection driver to issue new stream ID credit, which could lead to deadlocks if the receiver manages to ACK an entire window's worth of stream IDs before the application accepts any, and has no other reason to send packets.
> Refactor benchmarks, bugfix

- interop/Cargo.toml
- interop/src/main.rs
- quinn-h3/Cargo.toml
- quinn-h3/examples/h3.rs
- quinn-h3/examples/shared/mod.rs
- quinn-h3/examples/simple_client.rs
- quinn-h3/examples/simple_server.rs
- quinn-proto/Cargo.toml
- quinn-proto/src/connection.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/frame.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/shared.rs
- quinn-proto/src/streams.rs
- quinn-proto/src/tests/mod.rs
- quinn-proto/src/tests/util.rs
- quinn-proto/src/timer.rs
- quinn-proto/src/transport_error.rs
- quinn/Cargo.toml
- quinn/benches/bench.rs
- quinn/examples/client.rs
- quinn/examples/server.rs
- quinn/src/builders.rs
- quinn/src/connection.rs
- quinn/src/endpoint.rs
- quinn/src/lib.rs
- quinn/src/tests.rs
- quinn/tests/many_connections.rs
No obvious impact on the benchmarks, though they're super noisy so it'd be easy to miss a small one.
> Replace slog with tracing

- quinn/benches/bench.rs
Improves comparison between streams and datagrams.
> Tweak benchmarks

- azure-pipelines.yml
- quinn-proto/src/connection.rs
- quinn-proto/src/crypto/ring.rs
- quinn-proto/src/shared.rs
> Switch CI back to stable

- quinn/benches/bench.rs
- quinn/src/tests.rs
Exercises packet processing without large numbers of frames or stream processing.
> Benchmark packet-sized application datagrams

- quinn/Cargo.toml
- quinn/src/builders.rs
> Replace webpki-roots with optional native certificate store use

- quinn/Cargo.toml
- quinn/src/connection.rs
- quinn/src/endpoint.rs
Still no clear performance impact.
> Remove lingering uses of FNV hashing

- quinn-proto/src/connection.rs
> Assorted cleanup

- interop/Cargo.toml
- interop/src/main.rs
- quinn-h3/Cargo.toml
- quinn-h3/examples/h3.rs
- quinn-h3/examples/shared/mod.rs
- quinn-h3/examples/simple_client.rs
- quinn-h3/examples/simple_server.rs
- quinn/Cargo.toml
- quinn/examples/client.rs
- quinn/examples/server.rs
Anyhow was already in our dev-depgraph and is more modern and actively maintained.
> Use anyhow instead of failure in examples

- README.md
- interop/src/main.rs
- quinn-proto/src/connection.rs
- quinn-proto/src/crypto/rustls.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/frame.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/shared.rs
- quinn-proto/src/spaces.rs
- quinn-proto/src/streams.rs
- quinn-proto/src/tests/mod.rs
- quinn-proto/src/transport_error.rs
- quinn/examples/common/mod.rs
Now covering all the changes. Fixes #483.
> Draft 24 updates

- README.md
[Rendered](https://github.com/djc/quinn/blob/crates/README.md).
> Clarify repository contents

- quinn-proto/src/connection.rs
Corrects behavior and improves documentation regarding concerns raised in #544.
> Don't generate StreamWritable events for dead streams

- quinn/src/endpoint.rs
Avoids zeroing on every receive and might improve cache friendliness.
This seems to give a few percent speedup in the bulk benchmark, and eliminates memset from the profile. We really need a proper benchmarking environment...
> Keep a reusable receive buffer on the heap

- quinn-h3/src/body.rs
- quinn-h3/src/client.rs
- quinn-h3/src/connection.rs
- quinn-h3/src/frame.rs
- quinn-h3/src/lib.rs
- quinn-h3/src/proto/frame.rs
- quinn-h3/src/server.rs
- quinn-h3/src/streams.rs
> H3 draft 24

- quinn-proto/src/connection.rs
Hopefully corrects an issue encountered by @stammw in #551. This is a (semi) known issue in the draft 24 RFC, which is expected to be obsoleted by https://github.com/quicwg/base-drafts/pull/3162, but since we're seeing it actually arise in practice this'll keep us working in the spirit of the current draft for now.
> Fix panic in anti-amplification corner case

- quinn/src/streams.rs
A successful read of less than the desired buffer size would result in `Poll::Pending` being returned without a waker having been registered.
This is a fairly typical hand-implemented future bug; mark down another point in favor of switching to anonymous, `!Unpin`, but more obviously correct async/await style implementations.
> Fix hang in ReadExact future

- quinn-proto/src/crypto/ring.rs
- quinn/src/connection.rs
> Mark things non-exhaustive where appropriate

- quinn/benches/bench.rs
- quinn/examples/server.rs
- quinn/src/connection.rs
Corrects an issue encountered by @stammw during concurrent testing.
> Fix double poll of internal channel

- quinn-proto/src/connection.rs
Addresses a doc issue identified in #574.
> Update poll method docs to reflect privatization of timers

- quinn/src/connection.rs
> Fix timer updates not being applied while a timer was active

- quinn-proto/src/connection.rs
- quinn/Cargo.toml
- quinn/examples/common/mod.rs
- quinn/examples/connection.rs
- quinn/examples/insecure_connection.rs
- quinn/examples/single_socket.rs
- quinn/src/connection.rs
- quinn/src/lib.rs
Fixes #588, plus assorted issues found in recent discussion with other users.
> Doc tweaks

- quinn-proto/src/streams.rs
> Expand stream error docs

- quinn-proto/src/connection.rs
> Rephrase some proto::Connection API docs in more concrete terms

- quinn/src/lib.rs
> Re-export public ParseError type

- interop/src/main.rs
- quinn/src/tests.rs
Thought I slipped this into #620 but I guess github raced it.
> Update style to rustfmt 1.41

- quinn-proto/src/connection.rs
- quinn-proto/src/streams.rs
- quinn-proto/src/tests/mod.rs
Fixes #617. Thanks to @DemiMarie-parity for identifying this bug!
> Stream finish ack

- quinn-proto/src/endpoint.rs
Fixes #627. Seeking feedback in particular on the final commit; I'm not sure how I feel about complicating the interface to further defend against downstream bugs which the second commit is able to trivialize for substantially less effort.
> Improvements to Endpoint::accept

- quinn-h3/Cargo.toml
- quinn-h3/benches/bench.rs
- quinn-h3/src/client.rs
- quinn-h3/src/frame.rs
- quinn-h3/src/server.rs
- quinn-h3/src/streams.rs
- quinn-h3/src/tests/mod.rs
First H3 benchmarks, along with an optimisation on frame header encoding when sending.
Also includes some tests for request body reception.
> H3 throughput benchmark

- quinn-h3/src/qpack/dynamic.rs
relates to #359 
This PR make headers acknowledgement possible for trailers. Until then, only one block of dynamic table references was possible per stream ID.
> QPACK untrack trailers references in dynamic table 

- quinn/examples/connection.rs
> Fix panic in connection example

- quinn/src/lib.rs
- quinn/src/streams.rs
> Fix Stream::finish hang on closed connections

- quinn-proto/src/connection.rs
- quinn-proto/src/streams.rs
- quinn-proto/src/tests/mod.rs
> Implement an `outbound_streams` function

- quinn/src/streams.rs
If the peer acknowledges the stream FIN and the the Finish future isn't polled between then and the connection becoming closed (guaranteed to be the case if the ACK and the CONNECTION_CLOSE are in the same packet, which is common) then the Finish future would yield an error even though the stream is guaranteed to have been finished.
CC @alecmocatta, this should drastically reduce (although cannot, in principle, eliminate) the frequency of a connection close error being reported when `finish`ing a stream that causes the peer to immediately close the connection.
> Fix spurious error when finishing while peer closes the connection

- quinn-proto/src/assembler.rs
Fixes #652
Duplicated various tests with added calls to defragment.
> Handle overlapping chunks during defragment

- quinn-proto/src/connection.rs
- quinn/src/connection.rs
In particular, 3fc384c5c3d15fde2a4a525846e8d87555625da5 is a possible fix for #670.
> Assorted connection ID handling fixes

- quinn-proto/src/shared.rs
> Document hazards of infinite idle timeouts

- quinn-proto/src/connection.rs
- quinn-proto/src/lib.rs
Fixes #670. This was ~a long-standing bug~ multiple long-standing bugs revealed by the stricter protocol requirements in draft 27.
> Fixed active connection ID window

- quinn/src/connection.rs
Found this while experimenting.
> Fix busyloop in timer handling

- interop/src/server.rs
Make the interop server listen on `4434` with stateless retry activated.
> Retry port for the interop server

- quinn-h3/benches/bench.rs
- quinn-h3/src/server.rs
- quinn-h3/src/tests/helpers.rs
A couple things that caught my eye while working on #680.
> Minor H3 API tweaks

- .github/workflows/rust.yml
- interop/src/server.rs
> Accept PEM format in interop server

- quinn-proto/src/connection.rs
- quinn-proto/src/tests/mod.rs
With this change, only flow control and the configured send window limit the amount of data we accept from the application. I think this is more consistent with familiar behavior from TCP, and should reduce the amount of stack thrashing when the congestion window is small. CC @stammw regarding performance tests.
> Don't block application writes on congestion

- interop/Cargo.toml
- interop/src/main.rs
- interop/src/server.rs
- quinn-h3/Cargo.toml
- quinn-h3/src/client.rs
- quinn-h3/src/proto/connection.rs
Adresses #702 
Introduces a feature flag to enable accessors in the private connection state.
> Interop d test

- interop/Cargo.toml
- interop/src/qif.rs
- quinn-h3/src/lib.rs
The [bin] entry has been commented so it was left behind and couldn't run.
> Fix the QPACK offline interop tool qif.

- interop/src/server.rs
This makes browsers talk to us in HTTP/3 !
> interop: send Alt-Svc from h2 and h1

- quinn-h3/Cargo.toml
- quinn-h3/benches/bench.rs
- quinn-h3/benches/helpers.rs
- quinn-h3/benches/request.rs
- quinn-h3/benches/throughput.rs
This PR adds benchmarks for upload and get request / sec with and without headers, compression and body.
> H3 Some more benches

- interop/src/main.rs
- interop/src/server.rs
- quinn-proto/src/transport_error.rs
See https://tools.ietf.org/html/draft-pardue-quic-siduck-00 for details.
> Support the siduck datagram test protocol in interop tools

- interop/src/server.rs
> Send 0.5-RTT responses from interop server

- quinn-h3/src/tests/mod.rs
Relates to #725. It was fixed in #724, but there was no unit test. This PR adds one.
> H3: test response canceling from server

- interop/src/server.rs
Eases testing of congestion window behavior.
> Reset interop server initial congestion window to default

- README.md
Matrix is an open, federated platform that Mozilla recently committed to, with a growing Rust presence. The room in question is bridged to gitter to avoid fragmentation, and provides a richer, more provider-independent alternative infrastructure and adds a number of client options.
> Mention matrix room in README

- quinn/src/platform/cmsg.rs
> Clarify soundness requirements for cmsg helpers

- quinn-proto/src/connection/assembler.rs
- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/streams.rs
- quinn/src/connection.rs
Simple changes extracted from #758.
> Minor refactoring

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/streams.rs
- quinn-proto/src/tests/mod.rs
> populate_packet refactor

- quinn-proto/src/connection/assembler.rs
- quinn-proto/src/connection/streams.rs
- quinn-proto/src/range_set.rs
- quinn/src/streams.rs
> Flow control debugging

- interop/src/main.rs
- interop/src/server.rs
- quinn-h3/src/lib.rs
- quinn-proto/src/cid_queue.rs
- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/streams.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/frame.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/retry_token.rs
- quinn-proto/src/shared.rs
- quinn-proto/src/tests/mod.rs
- quinn-proto/src/token.rs
- quinn-proto/src/transport_error.rs
- quinn-proto/src/transport_parameters.rs
- quinn/examples/common/mod.rs
Draft until complete because this contains breaking changes.
> Update to draft 28

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/streams.rs
- quinn-proto/src/tests/mod.rs
- quinn/src/connection.rs
- quinn/src/streams.rs
> Stopped stream lifecycle refactoring

- quinn-h3/examples/h3_client.rs
> H3: make the h3 client default port 443

- interop/src/server.rs
- quinn-h3/src/server.rs
- quinn-proto/src/connection/mod.rs
- quinn-proto/src/crypto.rs
- quinn-proto/src/crypto/rustls.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/tests/mod.rs
- quinn-proto/src/tests/util.rs
- quinn/examples/server.rs
- quinn/src/connection.rs
- quinn/src/endpoint.rs
Fixes #749. Will improve our performance on the quic-tracker interop tests.
>  Signal ALPN/SNI availability during handshake

- quinn-h3/Cargo.toml
- quinn-h3/src/client.rs
- quinn-h3/src/data.rs
- quinn-h3/src/proto/settings.rs
Addressing a bug that emerged from interop test against gQuic.
> H3: ignore any number of unknown settings

- quinn-proto/src/connection/mod.rs
Fixes #810. Associated refactoring may also be of use in #804.
> Split up poll_transmit, detect spurious migration

- Cargo.toml
- bench/Cargo.toml
- interop/Cargo.toml
- quinn-h3/Cargo.toml
- quinn-proto/Cargo.toml
- quinn/Cargo.toml
Still needs a rustls-native-certs update.
> Upgrade to rustls-0.18

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/paths.rs
The refactoring parts of #804 so we can get this out of the way.
> Move PathData/RttEstimator to a paths module

- quinn/src/lib.rs
I am assuming this was not intentionally missing.
> Reexport ReadUnordered

- quinn-proto/src/congestion.rs
- quinn-proto/src/congestion/new_reno.rs
- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/pacing.rs
- quinn-proto/src/connection/paths.rs
- quinn-proto/src/connection/timer.rs
This implements pacing as suggested by the latest RFC draft.  It also
attempts to batch packets wherever possible.
Fixes #180.
> Implement pacing

- quinn-h3/Cargo.toml
- quinn-h3/src/lib.rs
- quinn-h3/src/qpack/decoder.rs
- quinn-h3/src/qpack/dynamic.rs
- quinn-h3/src/qpack/encoder.rs
- quinn-proto/Cargo.toml
- quinn-proto/src/coding.rs
- quinn-proto/src/config.rs
- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/streams.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/transport_parameters.rs
- quinn-proto/src/varint.rs
- quinn/Cargo.toml
- quinn/src/builders.rs
- quinn/src/connection.rs
- quinn/src/streams.rs
thiserror is easier to use, has fewer dependencies and is more popular.
> Switch from err-derive to thiserror

- quinn-proto/src/connection/mod.rs
It wasn't super clear what `more` means here. The purpose of this
parameter is to signal whether a `MAX_STREAM_DATA` frame needs to be
sent. This change tries to improve that.
> Update add_read_credits parameter name to max_stream_data_update

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/paths.rs
- quinn/src/connection.rs
Give users access to our RTT/latency estimate.
Closes #888
> Add `Connection::rtt` method

- quinn/src/connection.rs
The idea behind this change is to minimize the overhead for configuring
timers. This is based on a few ideas:
- Most timers never expire. Some other event will happen before
their expiration.
- However we need an active timer most of the time. It isn't worth it
to deallocate timers and allocate them later on.
Based on those facts, we can save overhead of creating and resetting
timers by keeping old timers running, as long as their timeout is
lower than the new desired timeout. They typically still won't
expire. If they do expire, we can lazily check whether the expiration
is real and adjust the timer again.
Some stats for this CR show:
In a setup with 700 required timer changes
- only 1 timer really expired
- with this change we have to reset the timer 4-8 times forward
- we get 20-22 …
> Recreate and reset timers less often

- bench/src/bulk.rs
- quinn-proto/src/config.rs
- quinn/src/endpoint.rs
- quinn/src/platform/fallback.rs
- quinn/src/platform/mod.rs
- quinn/src/platform/unix.rs
- quinn/src/udp.rs
Surprisingly, this only seems to give about 1% better throughput when CPU-bound. Still, probably worth having.
> Batched receive support

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/streams.rs
This change equals #880, but targets the connection window which is
updated via `MAX_DATA` frames instead of the stream windows.
Similar as #880, frames will only be enqueued if the update is
significant enough.
Quinn had already before an optimization, which triggered MAX_DATA
frames not to be sent when the window was set to the maximum at
the start of the connection [1]. However the frame was still set as
`pending` [2], which triggered the connection logic to create a packet
for it [3]. Since the payload was suppressed, this lead the connection
to either send additional ACK-only packets or create empty packets.
This change fixes this behavior, and thereby impacts the amount
of packets and performance even if the maximum connection flow
control window is specified. Therefore the …
> Send only significant MAX_DATA frames

- quinn-proto/src/connection/mod.rs
Should help mitigate a common source of confusion.
> Tweak ConnectionError docs

- quinn/examples/README.md
Resolves some inconsistencies introduced during iteration on #908.
> Fix errors in example README

- quinn-proto/src/connection/mod.rs
- quinn/src/platform/cmsg.rs
- quinn/src/platform/unix.rs
This extracts a couple of fixes from #953 . Descriptions are in the commits messages
> Cmsg Encoding and buffer capacity fixes

- quinn-proto/src/connection/mod.rs
> Fix outdated docs

- bench/src/bulk.rs
This allows to determine the impact of particular changes a
bit easier.
Example output:
```
Overall stats:
Sent 1073741824 bytes on 1 streams in 4.04s (253.61 MiB/s)
Stream metrics:
│  Throughput   │ Duration
──────┼───────────────┼──────────
AVG  │  253.56 MiB/s │     4.04s
P0   │  253.50 MiB/s │     4.04s
P10  │  253.62 MiB/s │     4.04s
P50  │  253.62 MiB/s │     4.04s
P90  │  253.62 MiB/s │     4.04s
P100 │  253.62 MiB/s │     4.04s
Server connection stats:
ConnectionStats {
udp_tx: UdpStats {
datagrams: 26391,
bytes: 1110961,
},
udp_rx: UdpStats {
datagrams: 918524,
bytes: 1116003172,
},
frame_tx: FrameStats {
ACK: 26388,
CRYPTO: 6,
DATAGRAM: 0,
HANDSHAKE_DONE: 4,
MAX_DATA: 0,
MAX_STREAM_DATA: 4984,
MAX_STREAMS_BIDI: 0,
MAX_STREAMS_UNI: 1,
NEW_CONNECTION_ID: 16,
PATH_CHALLENGE: 0, …
```
> Allow to show connection stats in bulk benchmark

- quinn-proto/src/connection/cid_state.rs
> Tweak CidState::track_lifetime() style

- quinn-proto/src/connection/streams.rs
- quinn-proto/src/frame.rs
Plus assorted cleanup. Fixes #966.
> Fix missing flow control checks in RESET_STREAM final offset handling

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/streams.rs
Here's a proposal for a different way to handle the abstraction (feel free to fold this into your second commit).
> Different way of factoring out read logic

- bench/src/bulk.rs
The sending data on the benchmark failed it panicked due
to an unwrap and thereby showed no result. This propagates
the first client-side error instead of panicking - which will also
preserve the statistics.
> Fix bulk benchmark

- quinn-proto/src/connection/assembler.rs
The variable `defragmented` wasn't properly updated in the
`read_chunks` method, since it directly manipulated the map instead
of delegating to the `Assembler::pop` method. This caused an underflow
when trying to insert more data into the map.
This change fixes that, and adds a repro test for it.
Fixes #982
> Fix StreamAssembler panic/underflow

- bench/src/bulk.rs
- fuzz/fuzz_targets/streams.rs
- quinn-h3/benches/helpers.rs
- quinn-proto/src/config.rs
- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/streams.rs
- quinn-proto/src/tests/mod.rs
- quinn-proto/src/transport_parameters.rs
- quinn/benches/bench.rs
- quinn/examples/common/mod.rs
- quinn/examples/server.rs
> Limit concurrent streams rather than accept queue size

- bench/src/bulk.rs
- quinn-proto/src/connection/assembler.rs
- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/spaces.rs
- quinn-proto/src/connection/streams.rs
- quinn-proto/src/connection/streams/recv.rs
- quinn-proto/src/connection/streams/send.rs
- quinn-proto/src/frame.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/tests/mod.rs
- quinn/benches/bench.rs
- quinn/src/lib.rs
- quinn/src/streams.rs
> Unified reading

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/spaces.rs
- quinn-proto/src/connection/streams.rs
`SentPacket` stores information about data transmitted in each packet.
This includes lists for all possible frame types.
However only a tiny subset of frame types are used in most packets:
Those will only contain ACKs and STREAM frames. The frame types
tracked in Retransmits make up less than 1/100 of all other types in
a common setup. E.g. the benchmark which transmits 1GB of data
shows:
```
frame_tx: FrameStats {
ACK: 903061,
CRYPTO: 2,
NEW_CONNECTION_ID: 5,
STREAM: 903057,
// All other types are 0
}
```
We can exploit this property to only allocate tracking state for the
additional frame types if they are actually transmitted. This can be
done by boxing the `Retransmit` type in `SentPacket` and `SentFrames`.
Doing this reduces the sizes of the tracking data structures:
**Before**:
> …
> Minimize SentPacket size and allocations

- quinn/src/lib.rs
These futures occur in the public API.
> Reexport ReadChunk(s)

- quinn-proto/src/connection/streams.rs
- quinn-proto/src/connection/streams/send.rs
Simplifies reasoning about stream states.
> Remove unnecessary send stream state

- quinn-proto/src/tests/util.rs
The TestEndpoint so far tried to send a single big datagram instead of using
proper GSO sending to emit multiple datagrams.
In order to avoid relying on platform GSO support, this change will simply
split up GSO transmissions into multiple Transmits in the endpoint.
> Make TestEndpoint GSO compatible

- quinn-proto/src/connection/mod.rs
Since the loop was not exited after a close frame was transmitted,
other data in the same space could have been transmitted after
the frame. This adds a `break` to fix this.
> Do not send any packets after a close frame

- Cargo.toml
- perf/Cargo.toml
- perf/src/client.rs
- perf/src/server.rs
For https://github.com/quicwg/base-drafts/wiki/Performance-Hackathon
> Perf protocol implementation

- quinn-proto/src/connection/mod.rs
- quinn/src/platform/unix.rs
These will improve interoperability and forwards-compat of the release.
> Additional backports for point release

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/tests/mod.rs
- quinn/examples/server.rs
Fixes https://github.com/quinn-rs/quinn/issues/1074.
> Fix lost client ack deadlock

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/streams/mod.rs
- quinn-proto/src/connection/streams/state.rs
This contains 2 small logging changes which should aid debugging
> Logging improvements

- quinn-proto/Cargo.toml
- quinn/Cargo.toml
Preparing for a point release to get the flow control fixes out.
> Bump versions for 0.7.2

- quinn-proto/src/connection/mod.rs
> Allow returning keys before the next frame.

- quinn-proto/src/connection/mod.rs
The current implementation continously resizes the datagram buffer if
GSO is enabled and further datagrams are appended. Some benchmarking
and profiling showed that this doesn't have too much of an impact with
the glibc allocator, the strategy proved rather inefficient with pooling
memory allocators like jemalloc and mimalloc. For those, the cost of
calling `realloc` is rather high.
I benchmarked a bunch of strategies to determine the most efficient way forward:
1. Continously resize output buffer (Current approach)
2. Reserve maximum buffer size upfront
3. Reserve space for a single datagram to minimize over-allocation for
tiny transmits. If this is not enough, reallocate once for maximum size
Based on the results of those, I am proposing to go for approach 2) and
simply allocate the …
> Reserve the maximum transmit buffer capacity upfront

- fuzz/fuzz_targets/packet.rs
- quinn-proto/src/config.rs
- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/packet_builder.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/tests/mod.rs
Backports #1106 to the 0.7.x branch
> Allow overriding supported versions in EndpointConfig (#1106)

- interop/src/main.rs
- interop/src/qif.rs
- quinn-h3/src/connection.rs
- quinn-proto/src/cid_queue.rs
- quinn-proto/src/connection/mod.rs
> Rust 1.52 lint fixes

- quinn-proto/src/connection/mod.rs
This seems slightly more efficient than extending a `Vec`.
Would probably be even more efficient if there would be an intersection
method on `SentMap` insert of returning packet numbers one by one.
Peak perf before:
```
Sent 1073741824 bytes on 1 streams in 1.77s (577.02 MiB/s)
```
After:
```
Sent 1073741824 bytes on 1 streams in 1.75s (584.25 MiB/s)
```
> Use an `ArrayRangeSet` to store new ACKs

- quinn-proto/src/config.rs
- quinn/src/recv_stream.rs
> Misc. doc fixes

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/tests/mod.rs
As described in https://github.com/quinn-rs/quinn/issues/1082,
the current version of the anti-ampflication check is extremely strict
and usually only allows 2 outgoing datagrams to be sent during a handshake
due to rounding down.
This change relaxes the check to allow sending another datagram if any
anti-amplification budget is left. This method is used by a variety of
other implementations too.
Fixes #1082
> Relax anti-ampflication check

- quinn-proto/src/crypto/rustls.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/packet.rs
Still TODO:
- Audit persistent congestion logic. I'm not sure we're correctly considering only ack-eliciting packets here, or waiting for an RTT sample.
> Final draft updates

- quinn/Cargo.toml
- quinn/tests/many_connections.rs
Remove unwrap crate and replace `unwrap!` with `unwrap()`.
> remove unwrap!

- .github/workflows/rust.yml
https://github.com/marketplace/actions/rust-cache
> Cache dependencies for CI

- quinn-proto/src/config.rs
- quinn-proto/src/connection/mod.rs
- quinn-proto/src/tests/mod.rs
- quinn/examples/server.rs
Followup for: https://github.com/quinn-rs/quinn/commit/41ae9586790ec2ed21ed4751287ab2900e542edb
> followup: rename "stateless retry" -> "retry"

- quinn-proto/src/endpoint.rs
- quinn-proto/src/packet.rs
> Avoid unwrapping in Endpoint

- quinn-proto/Cargo.toml
This is downstream's problem as of the crypto configuration cleanup.
> Remove unnecessary dependency

- quinn-proto/Cargo.toml
- quinn-proto/src/connection/cid_state.rs
- quinn-proto/src/connection/spaces.rs
- quinn-proto/src/connection/streams/state.rs
- quinn-proto/src/endpoint.rs
- quinn/Cargo.toml
- quinn/src/connection.rs
- quinn/src/endpoint.rs
See https://github.com/cbreeden/fxhash/pull/11#issuecomment-974829372.
> Replace fxhash with rustc_hash, its successor

- quinn-proto/src/endpoint.rs
Minor simplification. Note that `ServerConfig` is fairly small and contains no interior mutability, so cloning it is cheap and not a significant change in behavior.
> Use config to reject connections rather than extra state

- quinn-udp/src/unix.rs
@TimonPost reports encountering this consistently on WSL, and observed it at least once in our CI at https://github.com/quinn-rs/quinn/actions/runs/1630318713, manifesting as a cmsg_len of 20 rather than the expected 17. It was observed for the echo_dualstack and echo_v4 tests, but apparently not for echo_v6. Looking around the kernel source, I'm not sure how this is possible; the only origin seems to be https://elixir.bootlin.com/linux/latest/source/net/ipv4/ip_sockglue.c#L73, which has a very clearly hardcoded size of 1.
Our current behavior should be correct in release builds on little-endian systems, and harmlessly broken on big-endian systems. Still, I'd like to be able to account for why this is necessary, if nothing else so we can narrow down and perhaps someday remove the …
> Tolerate wide IP_TOS cmsgs

- quinn-proto/src/connection/streams/mod.rs
> Clarify meaning of events.

- .github/workflows/rust.yml
- fuzz/fuzz_targets/packet.rs
- quinn-proto/Cargo.toml
- quinn-proto/src/config.rs
- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/packet_builder.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/frame.rs
- quinn-proto/src/lib.rs
- quinn-proto/src/packet.rs
- quinn-proto/src/transport_parameters.rs
- quinn/Cargo.toml
Draft backwards-compatible anti-ossification measure.
> Implement draft-ietf-quic-bit-grease-02

- docs/book/src/quinn/data-transfer.md
- Make send mutable because of fixes rust error.
- Fix typo
> Fix document example

- quinn-proto/src/cid_queue.rs
- quinn-proto/src/connection/assembler.rs
- quinn-proto/src/connection/streams/mod.rs
- quinn/examples/server.rs
Opinions on this refactoring loosely held.
Tool-aided by [comby-rust](https://github.com/huitseeker/comby-rust).
> chore: Clean up a few Result patterns that fit an std combinator

- quinn-proto/Cargo.toml
- quinn-proto/src/tests/mod.rs
Catches https://github.com/rustls/rustls/issues/1005.
> Assert connection success in 0-RTT test

- quinn-proto/src/congestion/bbr/bw_estimation.rs
- quinn-proto/src/congestion/bbr/min_max.rs
- quinn-proto/src/congestion/bbr/mod.rs
Started by fixing some clippy warnings, cleaned up some other things that stuck out at me.
> Clean up BBR code

- bench/src/lib.rs
- quinn-proto/src/config.rs
- quinn/src/tests.rs
- quinn/tests/many_connections.rs
> config: add ServerConfig::with_transport_config() builder method

- quinn-udp/Cargo.toml
Avoids duplicating the dependency with tokio
> Update mio to 0.8

- docs/book/src/quinn/certificate.md
> docs: Update the client certificates example to a working config

- docs/book/src/quinn/certificate.md
> Fix incorrect code in book

- quinn-proto/src/packet.rs
- quinn-proto/src/tests/mod.rs
Fixes https://github.com/quinn-rs/quinn/issues/1334.
> Fix handling of invalid retry token lengths

- README.md
https://dirkjan.ochtman.nl/files/quic-future-in-rust.pdf results in a 404
> [README] update talk slides link

- quinn/examples/insecure_connection.rs
> Backport ALPN fix for insecure_connection

- bench/src/bin/bulk.rs
- bench/src/lib.rs
- bench/src/stats.rs
Fixes on bench lib for 32-bit platforms. Change upload_size and download_size to u64.
> Fixes on bench lib for 32-bit platforms.

- docs/book/src/quinn/certificate.md
Address the issue https://github.com/quinn-rs/quinn/issues/1367
> fix: read PEM certificates/keys by rustls_pemfile

- quinn-udp/src/unix.rs
See discussion at https://github.com/aws/s2n-quic/pull/1358.
> Fix Linux DF bit setting for IPv6-mapped IPv4 addresses

- quinn-udp/Cargo.toml
- quinn-udp/src/lib.rs
- quinn-udp/src/windows.rs
> Disable IP fragmentation on Windows

- quinn-proto/Cargo.toml
- quinn/Cargo.toml
> Bump versions to 0.8.4

- docs/book/src/quinn/certificate.md
I found this while following the tutorial and wanted to give a tiny bit back to this amazing project. Thanks for your great work!
> Fix variable name

- quinn-proto/src/endpoint.rs
- quinn/src/connection.rs
- quinn/src/endpoint.rs
- quinn/src/runtime.rs
- quinn/src/tests.rs
Trivial improvements split out from https://github.com/quinn-rs/quinn/pull/1219.
> Miscellaneous cleanup

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/packet_builder.rs
- quinn-proto/src/connection/spaces.rs
Fixes https://github.com/quinn-rs/quinn/issues/1413.
> Outgoing ACK improvements

- quinn-proto/src/connection/streams/state.rs
Fixes https://github.com/quinn-rs/quinn/issues/1421.
Similar to existing logic handling finishing of a stopped stream in `StreamsState::received`. The missing credit would be issued if a stream is later closed through a different code path, but there is no guarantee that would happen.
> Fix stopped streams not issuing ID credit when reset

- bench/src/bin/bulk.rs
- bench/src/lib.rs
- docs/book/src/quinn/set-up-connection.md
- perf/src/bin/perf_client.rs
- perf/src/bin/perf_server.rs
- quinn/Cargo.toml
- quinn/benches/bench.rs
- quinn/examples/common/mod.rs
- quinn/examples/connection.rs
- quinn/examples/insecure_connection.rs
- quinn/examples/server.rs
- quinn/examples/single_socket.rs
- quinn/src/endpoint.rs
- quinn/src/lib.rs
- quinn/src/tests.rs
- quinn/tests/many_connections.rs
Simplification consistent with the new `Connection` API patterns introduced in https://github.com/quinn-rs/quinn/pull/1357.
> Introduce Endpoint::accept method for better ergonomics

- quinn-proto/Cargo.toml
- quinn-udp/Cargo.toml
- quinn/Cargo.toml
Fixes #1419. I believe all outstanding wishlist items for 0.9 have been addressed. Please also review the draft release notes.
> Bump version numbers for 0.9 release

- perf/src/bin/perf_client.rs
- perf/src/bin/perf_server.rs
client and server binaries to change the initial size of UDP packet payload.
> Add --initial-max-udp-payload-size command line option for perf

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/packet_builder.rs
- quinn-proto/src/tests/mod.rs
Fixes #1443, and tweaks padding of outgoing packets to follow the guidance of RFC 9000 §10.3 on minimum size.
> Improve handling of small stateless resets

- quinn-udp/Cargo.toml
- quinn-udp/src/unix.rs
Forward-port of https://github.com/quinn-rs/quinn/pull/1448.
> fix: don't bail if setting IP_RECVTOS fails

- quinn/src/recv_stream.rs
- quinn/src/send_stream.rs
Fixes: https://github.com/quinn-rs/quinn/issues/1459
> send-stream, recv-stream: cleanup any wakers on drop

- quinn-proto/Cargo.toml
- quinn-udp/Cargo.toml
- quinn/Cargo.toml
Preparing to release independent bugfixes affecting each crate.
> Bump versions

- quinn/src/endpoint.rs
I've never actually seen this get stuck, but it seems like it could.
> Fix racy Endpoint::wait_idle

- perf/src/bin/perf_server.rs
> Fix usage message

- perf/src/bin/perf_client.rs
- perf/src/bin/perf_server.rs
- quinn/benches/bench.rs
- quinn/src/endpoint.rs
- quinn/src/tests.rs
See #1530 and https://github.com/quinn-rs/quinn/pull/1496#discussion_r1142773904.
> quinn: take Arc<dyn Runtime> directly

- .github/workflows/rust.yml
- bench/Cargo.toml
- perf/Cargo.toml
- quinn-proto/Cargo.toml
- quinn-udp/Cargo.toml
- quinn/Cargo.toml
More than six months old, and required by time 0.3.20.
> Bump MSRV to 1.63

- quinn/src/connection.rs
- quinn/src/send_stream.rs
Obsoletes https://github.com/quinn-rs/quinn/pull/1575 which hasn't been updated in a while, plus bonus cosmetic cleanup.
> Fix panic on redundant finish calls

- README.md
Fixes https://github.com/quinn-rs/quinn/issues/1592
> Update README.md to say "see examples for usage" with link

- quinn-proto/src/endpoint.rs
- quinn/src/endpoint.rs
backport suppress stateless packets to 0.9.x
> backport suppress stateless packets to 0.9.x

- quinn-proto/Cargo.toml
- quinn/Cargo.toml
bump versions to 0.10.2 in 0.10.x release line
> bump versions to 0.10.2

- quinn-proto/Cargo.toml
- quinn/Cargo.toml
bum quinn and quinn-proto version to 0.9.4
> bump versions to 0.9.4

- quinn-udp/src/fallback.rs
- quinn-udp/src/unix.rs
- quinn-udp/src/windows.rs
- quinn/src/runtime/async_std.rs
- quinn/src/runtime/tokio.rs
This seems like pretty natural follow-up to #1612.
> udp: simplify socket state initialization

- quinn-udp/src/unix.rs
Clean up the changes from #1626 to make sure we still propagate other errors to the caller.
cc @jieliangma
> udp: use set_socket_option_supported() wrapper

- quinn-udp/src/lib.rs
This helps implementors of AsyncUdpSocket.
----
I'm happy to squash/rebase once review is done if desired, but will wait until the end so changes between review comments are easy to understand.  Just let me know.
> Add docs for RecvMeta

- quinn-proto/src/config.rs
- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/spaces.rs
- quinn-proto/src/tests/mod.rs
- quinn-proto/src/tests/util.rs
Fixes https://github.com/quinn-rs/quinn/issues/1628
I chose to make this option private and test-only since I don't see a good reason to expose it in general.
> Deflake ACK tests

- quinn-proto/src/connection/mod.rs
RFC9000 says: endpoints MUST treat any packet ending in a valid stateless reset token as a Stateless Reset
Previously, we did not detect stateless resets that appeared to be unprotected packets (e.g. Retry or Version Negotiation) or which were successfully decrypted (astronomically unlikely with TLS, but possible with custom cryptographic layers).
We didn't detect this before because all current standard QUIC versions only issue stateless resets as short-header packets.
> proto: detect stateless resets in authed and unprotected packets

- bench/src/bin/bulk.rs
- bench/src/lib.rs
> Minor bulk benchmark improvements

- quinn/src/recv_stream.rs
If `read_exact()` finishes early (end of stream), report the number of bytes actually read.
(note: this breaks the API)
Fixes #1663
> Pass byte read count to FinishEarly

- Cargo.toml
- quinn-proto/src/connection/streams/mod.rs
- quinn-proto/src/connection/streams/recv.rs
- quinn-proto/src/connection/streams/send.rs
- quinn-proto/src/connection/streams/state.rs
- quinn-proto/src/range_set/btree_range_set.rs
- quinn-proto/src/tests/util.rs
- quinn/src/connection.rs
> #1682 squashed + split

- quinn-proto/src/config.rs
Implement `Debug` for `IdleTimeout`. #1687
Fix typo.
> Implement `Debug` for `IdleTimeout`.

- quinn/src/connection.rs
If this is too link heavy, I can remove the links and just leave the plain backtick form.
> Update docs for `Connection::accept_bi()` and `Connection::open_bi()`

- quinn/src/recv_stream.rs
Prompted by #1742 and assorted prior support requests. Should serve as a good reminder for us as well.
> Document two more commonly-observed mistakes in `RecvStream` use

- quinn/examples/client.rs
Hi all! My name's Phoenix. I've been interesting in contributing to this project for a while and thought I'd start with trying to get the examples working on my machine. Let me know if you have any feedback :)
I'm running Ubuntu 22.04.3, and even after enabling IPV6, when running the examples in the way suggested in the README:
```sh
$ cargo run --example server ./
$ cargo run --example client https://localhost:4433/Cargo.toml
```
The client timed out. If I passed `--listen 127.0.0.1:4433` or `--listen 0.0.0.0:4433` when running the server, it worked fine. But weirder yet, if I passed `--listen [::]:4433` on the server, it also works fine. So it seems like my system allows `127.0.0.1` to connect to `[::]` but not to `[::1]`.
In any case, I figured that I should be able to get the client …
> Fix parsing of IPV6 URLs in client example

- quinn/src/recv_stream.rs
- quinn/src/send_stream.rs
> Document cancel-safety of stream I/O operations

- quinn-proto/src/transport_parameters.rs
As [required by the RFC](https://www.rfc-editor.org/rfc/rfc9000.html#section-18.2-8).
> Add missing transport parameter validation checks

- quinn-proto/src/endpoint.rs
Reduces the amount of work done for connection attempts that will be refused or ignored when the application layer can do so cheaply, e.g. using a blocked IP list.
> Defer initial packet payload decryption until after accept

- quinn-proto/Cargo.toml
- quinn-proto/src/crypto/rustls.rs
This wasn't released yet when we merged #1715.
> proto: take advantage of rustls::quic::Suite being Copy

- .github/workflows/rust.yml
- bench/Cargo.toml
- quinn-proto/src/cid_generator.rs
- quinn-proto/src/config.rs
- quinn/Cargo.toml
- quinn/src/endpoint.rs
- quinn/src/runtime.rs
Other workspace members enable some features, so check in isolation.
> Check compilation without default features in CI

- quinn-proto/src/connection/mod.rs
- quinn-proto/src/connection/packet_builder.rs
Fixes https://github.com/quinn-rs/quinn/issues/1803.
> Fix previous path validation allowing flows to be linked across migration

- quinn-udp/src/lib.rs
See `From` definitions right below the changes.
> docs(udp): replace AsRawFd and AsRawSocket with AsFd and AsSocket

- quinn-proto/Cargo.toml
- quinn/Cargo.toml
> Bump version numbers (quinn 0.11.2, -proto 0.11.3)

- quinn/src/connection.rs
Intended to make #1905 less repetitive.
> quinn: introduce waking helpers

- quinn/src/endpoint.rs
> Fix unnecessary Incoming warning on Endpoint drop

- quinn/src/endpoint.rs
The remaining counters are purely monotonic and more conveniently grouped.
Followup to #1900.
> Exclude metrics with freestanding getters from EndpointStats

- quinn-proto/Cargo.toml
Going to merge this without review in order to publish the release.
> proto: bump version to 0.11.8 for release

- quinn/src/lib.rs
> quinn: export endpoint::EndpointStats

- .codecov.yml
- .github/workflows/codecov.yml
In order to get the platform-specific code some coverage testing.
> ci: Check coverage on multiple platforms

- quinn-udp/benches/throughput.rs
- quinn-udp/src/unix.rs
- quinn-udp/src/windows.rs
- quinn-udp/tests/tests.rs
- quinn/examples/connection.rs
- quinn/examples/insecure_connection.rs
- quinn/examples/single_socket.rs
- quinn/src/tests.rs
- quinn/tests/many_connections.rs
Avoids a bunch of parsing and checking.
> chore: Replace IP strings with address types

- quinn-proto/Cargo.toml
- quinn/Cargo.toml
I needed to dig into what was going on within rustls. Somebody else might find this useful (and I might need it again in future).
This feature flag also works with `tracing_subscriber`.
> Feature flag for rustls logging

- quinn-proto/Cargo.toml
- quinn-proto/src/crypto/rustls.rs
- quinn/Cargo.toml
This will have:
- aws-lc-rs support
- WASM support
- Several other fixes, features and performance improvements
> Prepare proto 0.11.9

- quinn-proto/Cargo.toml
- quinn-udp/Cargo.toml
- quinn/Cargo.toml
Based on https://github.com/rustls/rustls/pull/1827/commits/005afd891f5f6da19f379d434f3ec765130e6a59.
> Avoid FIPS in docs.rs builds

- quinn-udp/src/unix.rs
- quinn-udp/tests/tests.rs
> Fix inconsistent GSO logic on Unix platforms

- quinn-proto/src/endpoint.rs
> Improve time accounting for Incoming

- .github/workflows/rust.yml
- quinn-udp/build.rs
- quinn-udp/src/unix.rs
- quinn-udp/tests/tests.rs
- quinn/src/tests.rs
This PR adds support for Illumos and tests on CI. Also fixes a warning on Solaris and Illumos.
> feat(quinn-udp): support illumos

- .gitignore
- quinn-proto/src/config/mod.rs
- quinn-proto/src/config/transport.rs
- quinn-proto/src/endpoint.rs
- quinn/src/endpoint.rs
- quinn/src/incoming.rs
- Adds .zed to gitignore
- Doc comments tweaks
- Consistent punctuation and width
- Documenting defaults
- Other tweaks
- Debug implementation tweaks
- Elide fields via finish_non_exhaustive
- Other tweaks
> Minor style changes

- quinn/src/connection.rs
Fixes two documentation flaws noted in #1757.
> docs(quinn): Tweak Connecting docs

- quinn-proto/src/connection/mtud.rs
> Gate PLPMTUD should_panic test on debug_assertions

- quinn-proto/src/endpoint.rs
Some very minor simplifications.
> proto: Refactor Endpoint::handle

- quinn-proto/src/tests/token.rs
> test(proto): Fix wasm CI

- quinn-proto/src/tests/token.rs
- This PR closes #2118.
- This PR adds test code to verify the expiration of the retry token.
> add test for retry token expired

- quinn/src/recv_stream.rs
> Makes poll_read_buf public

- Cargo.lock
- Cargo.toml
- docs/book/Cargo.toml
- docs/book/src/quinn/certificate-certs.rs
- docs/book/src/quinn/certificate-insecure.rs
- docs/book/src/quinn/certificate.md
- docs/book/src/quinn/data-transfer.md
- docs/book/src/quinn/data-transfer.rs
- docs/book/src/quinn/set-up-connection.md
- docs/book/src/quinn/set-up-connection.rs
context: https://github.com/quinn-rs/quinn/issues/2152
- set up docs/book so that example code in the document can be separated into .rs files and can be checked by the compiler
- update document to align with the latest version
> docs: update document with example code separated

- Cargo.lock
- quinn-proto/src/connection/streams/send.rs
- quinn-proto/src/endpoint.rs
- quinn-proto/src/tests/mod.rs
- quinn-proto/src/tests/util.rs
Addresses [RUSTSEC-2025-0023](https://rustsec.org/advisories/RUSTSEC-2025-0023.html), an unsoundness issue in tokio.
> Update semver-compatible dependencies

- quinn-udp/src/unix.rs
At present, each of the various `send` functions within `quinn-dup` handle the error case of `EMSGSIZE` individually. This code duplication can be avoided by moving this error handling to the `UdpSocketState::send` function.
Additionally, contrary to what the comment states, this error code can also be returned if the provided datagram is simply to large which can happen with some very big GSO batches.
> quinn-udp: handle EMSGSIZE in a common place

- quinn-udp/src/unix.rs
See commit message for a detailed explanation.
> fix(quinn-udp): sanitise `segment_size`

- .github/workflows/rust.yml
- quinn/src/runtime.rs
- quinn/src/runtime/async_io.rs
> Fix feature combination bugs and change powerset CI check

- quinn/src/send_stream.rs
We maintain explicit send stream future implementation structs for `Write`, `WriteAll`, `WriteChunk`, and `WriteAllChunks`. However, these are private. We can significantly simplify this code by instead leaning more directly on functionality such as async functions and `std::future::poll_fn`.
> quinn: Remove explicit write future structs

- .github/workflows/rust.yml
https://github.com/quinn-rs/quinn/issues/2218
> Solaris CI: workaround for spurious network issues

- .github/workflows/rust.yml
https://github.com/quinn-rs/quinn/issues/2218
> Solaris CI: better workaround for spurious network issues

- Cargo.lock
- Cargo.toml
- quinn-proto/src/bloom_token_log.rs
The MSRV issue that appeared in #2287 has been resolved.
> Upgrade to fastbloom 0.12

- deny.toml
We'll be addressing https://rustsec.org/advisories/RUSTSEC-2025-0052 in
- #2348
> Ignore async-std advisory for now

- perf/src/bin/perf.rs
> perf: move main() above Cli

- quinn-proto/src/endpoint.rs
We're doing breaking changes right now, right?
Closes #2252
Notes:
```
size_of::<AcceptError>() = 136
size_of::<ConnectionError>() = 56
size_of::<Option<Transmit>>() = 80
```
Alternatives considered:
1. Convert to `pub struct AcceptError(Box<AcceptErrorInner>); struct AcceptErrorInner { field1, field2 }` and `impl` accessors for `AcceptError`
**Cons:** `AcceptError` contains `Transmit` which is not even clone, meaning you might want to destructure it to take ownership of both fields at once, which makes accessors problematic. Also, big and ugly.
2. Convert to `pub struct AcceptError(pub Box<AcceptErrorInner>); pub struct AcceptErrorInner { pub field1, pub field2 }`
**Cons:** Big and ugly.
Migration for users should be very simple for this approach. Notably, quinn itself works unmodified. …
> refactor(proto): Box AcceptError

- Cargo.lock
- quinn/Cargo.toml
Fixes https://github.com/quinn-rs/quinn/issues/2384.
> Fix over-permissive proto dependency edge
